wri/gfw

- app/views/static/getinvolved.html.erb
Can we also make this sentence bold? For some reason the tags are not working. 
"The 2015 application period is now open. Please read below for information on how to apply."
> Get Involved: SGF text edits

- app/views/static/getinvolved.html.erb
We want the email box to be mandatory if the "yes" box is checked, but I'm not sure what that would look like in the code.
> Updated "provide feedback", words and links

- app/views/shared/_sources.html.erb
Updated the Date of Content to: 1997-2000, and updated the citation based on a request by UNEP-WCMC
> Updated data page text for the global mangroves

- app/views/static/keep.html.erb
Haven't added "interesting" sections or "pub" list yet
> updated get involved text

- app/views/static/howto.html.erb
I added the entire "What is tree cover canopy..." section - please check this code!
> Changes to all FAQ

- app/assets/javascripts/helpers/interestingHelper.js
Will also be adding more sections once this pull request is merged.
> Update to 'you may find this interesting'

- app/views/static/keep.html.erb
Added publication list with hyperlinks
> update pub list

- app/views/static/about.html.erb
@apercas PLEASE CHECK THIS FOR ERRORS!!
> updated contact info and text

- app/views/static/applications.html.erb
None of these are new, we'll use this later on to highlight a new app
> removed "official ribbon" from apps

- app/views/shared/_sources_map.html.erb
@apercas @mbarrenechea The "How To" links aren't working
> fixed small typos

- app/views/stories/_form.html.erb
@apercas @mbarrenechea Make sure to merge this w/ GFW-nav!
> change to submit story "hint"

- app/views/stories/_form.html.erb
> Revert "change to submit story "hint""

- app/views/static/explore.html.erb
Updated app name and description for Landsat and JGI tools
> app name update

- app/views/static/getinvolved.html.erb
@rachnp89 The apps are also updated on the "help improve data" page
> Updated apps on "Help improve data" page

- app/views/static/about.html.erb
- Please change name of "partners" list to "Partners & collaborators"
- While we're waiting for logos from some partners, can we just intersperse text with logos?  Everything should be in alphabetical order.
- Will add logos to Basecamp for BNPM, REDD+ Agency of Indonesia, and Digital Globe
- Waiting for logos from other partners, will upload to Basecamp as we get them
- Can we center everything on this page?
- Can we also add all of the logos that we have to the footer and put them in alphabetical order?
> changes to partner page

- app/views/static/getinvolved.html.erb
@mbarrenechea I made some of these changes last night and they were merged, but they're not showing up on GFW-nav.  Just want to make sure these changes show up!
> changes to help improve data

- app/assets/javascripts/countries/helpers/CountryConfig.js
- app/assets/javascripts/countries/views/CountryHeaderView.js
- app/assets/javascripts/countries/views/CountryOverviewView.js
- app/assets/javascripts/map/services/AnalysisService.js
- app/assets/javascripts/map/services/CountryService.js
- app/assets/javascripts/map/services/SitesService.js
- app/assets/javascripts/map/views/layers/PantropicalLayer.js
- app/assets/javascripts/map/views/maptypes/landsatMaptype.js
- app/assets/javascripts/map/views/maptypes/treeheightMaptype.js
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/javascripts/stories/views/StoriesEditView.js
- app/views/layouts/countries.html.erb
- app/views/layouts/map.html.erb
- jstest/helpers/analysis_service_response.js
- lib/assets/javascripts/gfw/gfw_lib.js.erb
- lib/assets/javascripts/gfw/helpers.js.erb
- lib/assets/javascripts/gfw/ui/analysis.js.erb
> Revert "Js env vars. Countries call is not working"

- app/assets/javascripts/countries/helpers/CountryConfig.js
- app/assets/javascripts/countries/views/CountryHeaderView.js
- app/assets/javascripts/countries/views/CountryOverviewView.js
- app/assets/javascripts/map/services/AnalysisService.js
- app/assets/javascripts/map/services/CountryService.js
- app/assets/javascripts/map/services/SitesService.js
- app/assets/javascripts/map/views/layers/PantropicalLayer.js
- app/assets/javascripts/map/views/maptypes/landsatMaptype.js
- app/assets/javascripts/map/views/maptypes/treeheightMaptype.js
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/javascripts/stories/views/StoriesEditView.js
- app/views/layouts/countries.html.erb
- app/views/layouts/map.html.erb
- jstest/helpers/analysis_service_response.js
- lib/assets/javascripts/gfw/gfw_lib.js.erb
- lib/assets/javascripts/gfw/helpers.js.erb
- lib/assets/javascripts/gfw/ui/analysis.js.erb
> Revert "Revert "Js env vars. Countries call is not working"" fckng crzy

- app/views/landing/index.html.erb
Remove "GFW's 1-year anniversary" slide
@d4weed @apercas @mbarrenechea Let me know if I'm not doing this correctly!
> Remove 1st carousel item

- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/javascripts/templates/download.handlebars
- app/assets/javascripts/templates/download_error.handlebars
- app/assets/javascripts/views/DownloadView.js
- app/assets/stylesheets/modules/countries/_overview.scss
- app/controllers/concerns/countries_concern.rb
- app/controllers/countries_controller.rb
- app/mailers/mobile_download.rb
- app/views/countries/_header.html.erb
- app/views/mobile_download/download_email.text.erb
- config/locales/en.yml
- config/routes.rb
- spec/concerns/countries_concern_spec.rb
- spec/controllers/countries_controller_spec.rb
- spec/mailers/mobile_download_spec.rb
Same as #1455 except with pretty modal boxes and actual commit messages! :dancers:
> Adds a download link mailer on mobile

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/router.js
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/views/layers/CarbonLayer.js
- app/views/shared/_sources.html.erb
- app/views/shared/_sources_map.html.erb
New carbon layer added to stagging
> new layer: carbonLayer added

- app/assets/javascripts/templates/share_iframe.handlebars
- app/assets/javascripts/views/SharePreviewView.js
- app/assets/javascripts/views/ShareView.js
- app/views/countries/show.html.erb
- app/views/shared/_embed_preview_iframe.html.erb
- app/views/shared/_sources_map.html.erb
Moved the iframe code out in to its own view so we can render it correctly (rather than just vomiting it in to the body on page load :grimacing:).
> Fixes iframe rendering for share popup

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/views/layers/CanLoggingLayer.js
> new local layer: canada logging

- app/assets/javascripts/map/presenters/tabs/CountriesPresenter.js
- app/assets/javascripts/map/views/tabs/CountriesView.js
Uses present pubsub instead of guesswork :).
> Country layer toggle fix

- app/views/shared/_sources.html.erb
changes layer names to match new names in drop-down menus
> changes to forest change info window text

- app/assets/stylesheets/modules/countries/_show.scss
- app/views/countries/_header.html.erb
> Limits length of Country show title

- app/views/shared/_sources_map.html.erb
this leave cmr_mining_layer info button with a endless url
> hotfixed: Can mining permits <a></a> closed

- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/javascripts/map/views/MapControlsView.js
- app/assets/javascripts/views/SharePreviewView.js
- app/assets/javascripts/views/ShareView.js
- app/assets/stylesheets/modules/_modal.scss
- app/views/countries/show.html.erb
Share preview closes and removes itself correctly
> Fix share preview

- app/views/shared/_sources_map.html.erb
This update follows the update which allows analysis for all polygon data layers
> Analysis: other data layers info window changes

- app/views/shared/_sources_map.html.erb
wrong text was included for citation
> fixed OSINFOR text

- app/views/shared/_footer_landing.erb
How to "Open Data Portal" is confusing, How to "Download data" makes more sense to users
> Changed How To Title for ODP

- app/assets/javascripts/map/views/maptypes/treeheightMaptype.js
> changed url for new tiles

- app/views/shared/_sources_map.html.erb
https://basecamp.com/1756858/projects/472471/todos/165539803
> imazon coverage text changed

- app/assets/javascripts/map/templates/navmobile.handlebars
- app/assets/javascripts/map/templates/tabs-mobile.handlebars
- app/assets/stylesheets/modules/map/_module-navmobile.scss
Please, make sure that this is what they are asking for. https://basecamp.com/1756858/projects/472471/todos/192792405
> Fix: title changed

- app/views/static/getinvolved.html.erb
Added text for Data Playbook, link will be added by Vizzuality.
> Added Data Playbook description.

- app/views/static/howto.html.erb
Added text about Data Playbook and edited text describing Open Data Portal to reflect new features. Link to be added by Vizzuality.
> Edited text to add Data Playbook description.

- app/assets/javascripts/map/cartocss/honduras_forest.cartocss
- app/assets/javascripts/map/templates/legend/hondurasForest.handlebars
- app/assets/stylesheets/modules/map/_module-legend.scss
Now this layer has a legend with 26 classes, we should change the layerspec when we deploy it to PRO.
It's not loading very well.
> Honduras layer

- app/assets/javascripts/countries/views/CountryOverviewView.js
We are now using the total_gain value.
> Tree cover gain list is now calculated correctly

- app/views/static/getinvolved.html.erb
> Changed link for Data Playbook to Amazon S3.

- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/stylesheets/modules/map/_module-legend.scss
Subtitles added to legend.
Some little fixes on legend styles.
> Legend: subtitles added to some layers

- app/views/static/about.html.erb
NOTE: logos need to be created for The Tilia Fund and Bobolink Foundation (we created ones before but I didn't know what to include for "class")
> updates to partnership page

- app/assets/javascripts/map/templates/tabs/countriesIso.handlebars
Updated text that shows when country data is not available.
> Updated Country Data text

- app/views/static/howto.html.erb
Changed link/text from country profiles to the interactive map.
> Updated How To Text for Visualize Country data

- app/views/static/howto.html.erb
Added a link to Submit a Story page from the How to Text and changed the text.
> Updated How to Text for Stories

- app/views/static/howto.html.erb
Changed "view country ranking" to "view country rankings".
> Updated How to Text title

- app/views/static/howto.html.erb
> Updated How to text for Country Statistics

- app/views/static/getinvolved.html.erb
Updated the Data Playbook pdf in S3 and added new link.
> Updated Data Playbook file

- app/views/landing/index.html.erb
Changed first and second carousel slides.
> Updated carousel slides

- app/views/static/howto.html.erb
Updated How To text for subscribing to alerts.
> Updated How to Text About Alerts

- app/assets/javascripts/static/helpers/applicationsHelper.js
Added tags to apps on the Explore page.
> Added tags to apps

- app/views/landing/index.html.erb
Slides had the incorrect text and links.
> Fixed carousel slide text

- app/views/shared/_sources_map.html.erb
Add an additional line in the cautions section in English and Spanish. Added line breaks between cautions paragraphs, and between the Overview and Resumen
> Update Honduras info window text on staging

- app/views/landing/index.html.erb
Updated first carousel slide with new Indonesia fires blog.
> Updated carousel slide text

- app/assets/javascripts/abstract/layer/TorqueLayerClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineDatePicker.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineSlider.js
- app/assets/javascripts/map/cartocss/LandsatAlertsTorque.cartocss
- app/assets/javascripts/map/presenters/TorqueLayerPresenter.js
- app/assets/javascripts/map/presenters/TorqueTimelinePresenter.js
- app/assets/javascripts/map/queries/default_torque.sql.hbs
- app/assets/javascripts/map/services/TorqueDateService.js
- app/assets/javascripts/map/views/layers/LandsatAlertsTorqueLayer.js
- app/assets/javascripts/templates/datePickerTorque-legend.handlebars
- app/assets/javascripts/templates/datePickerTorque.handlebars
- app/assets/javascripts/templates/timelineTorque-date.handlebars
- app/assets/javascripts/views/HeaderView.js
- app/assets/stylesheets/map.scss
- app/assets/stylesheets/modules/map/_timeline-torque-date-picker.scss
- app/assets/stylesheets/modules/map/_timeline-torque.scss
- bower.json
- config/requirejs.yml
* Adds the date pickers to the Torque timelines, using this not-to-terrible date picker: http://amsul.ca/pickadate.js/date/
* Styles the timeline to match the designs
* Fixes a few bugs and makes it harder for the user to break it 👮
Test it out [here](http://localhost:5000/map/3/15.00/27.00/ALL/grayscale/gfw_landsat_torque_alerts?begin=2015-01-06&end=2015-11-03)
> Torque timeline date picker

- app/views/shared/_sources.html.erb
We now have cambodia mining (on pro and staging)... please push to staging and then to Pro as soon as possible
> Add Cambodia to list of mining data countries

- app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineDatePicker.js
- app/assets/javascripts/map/cartocss/LandsatAlertsTorque.cartocss
- app/assets/javascripts/templates/datePickerTorque.handlebars
- app/assets/stylesheets/modules/map/_timeline-torque.scss
* Fixes a bug that broke the timeline when switching layers (thanks @apercas!)
* Updates the CartoCSS to make it easier (read: possible) to see individual points
* Fixes a bug so that the timeline layer name is update properly
> Torque timeline fixes

- app/assets/javascripts/abstract/layer/TorqueLayerClass.js
- app/assets/javascripts/map/cartocss/LandsatAlertsTorque.cartocss
Few small tweaks for https://basecamp.com/3063126/projects/10726176/todos/210384059
> Update cartocss for GLAD torque layer

- app/views/countries/_countries.html.erb
Updated citation for type of forest and carbon stocks to FAO 2015.
> Updated citation for 2015 FRA Data

- app/views/static/howto.html.erb
Removed Fires and Commodities buttons from "Visualize Global Data".
> Removed Fires and Commodities from How To

- app/views/landing/index.html.erb
Added carousel slide for GFW Climate.
> Updated carousel text for Climate

- app/views/landing/index.html.erb
> Added the link for the carousel slide

- app/assets/stylesheets/layouts/_landing.scss
Added Photo for Climate Carousel!
> Added Climate Carousel Photo

- app/assets/javascripts/abstract/layer/TorqueLayerClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
- app/assets/javascripts/map/cartocss/forma_250.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/views/layers/AsItHappensLayer.js
- app/assets/javascripts/map/views/layers/Forma250CoverLayer.js
A few fixes for the forma/glad layers:
* start animation at the end so you can see the full extent of the changes first
* speed up the torque animations to match up with the existing loss/gain layer timing
* show the correct geographic coverage layer for forma 250
> New layer fixes

- app/assets/javascripts/map/presenters/controls/SearchboxPresenter.js
- app/assets/javascripts/map/templates/controls/searchbox.handlebars
- app/assets/javascripts/map/views/controls/SearchboxView.js
- bower.json
I simplified a few other bits of code in the view while moving around, but the bit you'll be interested in is here: https://github.com/Vizzuality/gfw/compare/develop...fix/utm-coordinates?expand=1#diff-299ddb1e9a18720ec9416ca663a41867R173
Now we use proj4js for conversion, which I think is a bit more reliable, and also managed externally.
> Fixes UTM conversion in search

- app/assets/javascripts/map/cartocss/LoggingRoads.cartocss
- app/assets/javascripts/map/templates/legend/logging_roads.handlebars
subir cuanto antes a stagging!
> added colors to logging roads

- app/assets/stylesheets/layouts/_landing.scss
Added photo for Commodities Mill Points Data.
> Updated Carousel Photo

- app/assets/javascripts/map/templates/maptype.handlebars
- app/assets/javascripts/map/templates/tabs/basemaps.handlebars
- app/assets/javascripts/map/views/MapView.js
> added landsat 2013-2014

- app/assets/stylesheets/layouts/_landing.scss
Changed carousel photos for slide 5 and 7.
> Updated carousel photos

- app/assets/stylesheets/layouts/_landing.scss
> Changed photo for Palm Oil Mills

- app/assets/javascripts/abstract/layer/CanvasLayerClass.js
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/pantropical.handlebars
- app/assets/javascripts/map/views/layers/PantropicalLayer.js
- app/assets/stylesheets/modules/map/_module-legend.scss
- app/views/shared/_sources_map.html.erb
substituted pantropical old layer for Aboveground biomass layer from climate.
I had tested it on my local  it doesnt interfered with loss and gain layers
> udated pantropical and canvas layer

- app/views/shared/_sources.html.erb
Linking in the "cautions" text for loss and gain to new blog on accuracy: http://blog.globalforestwatch.org/2015/12/how-accurate-is-accurate-enough-examining-the-glad-global-tree-cover-change-data-part-1/
> Add link to accuracy blog

- app/assets/javascripts/abstract/layer/ImageLayerClass.js
- app/assets/javascripts/map/presenters/tabs/HighresolutionPresenter.js
- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/TabsView.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
This PR set the conditions of zoom for urthecast.
- if the zoom reaches level 7, urthecast layer will work
- if you are at zoom 7 with urthecast layer working, but you set the zoom under 7, the layer will be removed from selected layers.
> Urthecast zoom conditions

- app/assets/javascripts/map/presenters/tabs/HighresolutionPresenter.js
- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- app/assets/stylesheets/modules/map/_tab-highresolution.scss
- app/views/shared/_sources_map.html.erb
- Remove hres param from url when user disabled the layer. (It prevents this => When user reload the page, layer turns on if there is hres param in the url)
- Scroll added to hres tab
- Infowindows updated
> Infowindows, some behaviour fixes

- app/controllers/static_controller.rb
- config/routes.rb
- Created a new endpoint to manage the feedback across applications (jsonp).
> Feedback jsonp

- app/assets/javascripts/abstract/layer/CartoDbCanvasLayerClass.js
- app/assets/javascripts/helpers/canvasCartoCSSHelper.js
- app/assets/javascripts/map/cartocss/default_canvas_style.cartocss
- app/assets/javascripts/map/views/layers/AsItHappensLayer.js
The cache version will need to be bumped on Heroku for this
> GLAD layer accounts for multiple years

- app/views/static/getinvolved.html.erb
!!!!! Merge and deploy it on 6 JAN !!!!!!
> New small grats fund text (!!!!! Merge and deploy it on 6 JAN !!!!!!)

- app/assets/stylesheets/layouts/_landing.scss
Added photo for REDD+ blog slide.
> Updated photo for carousel slide

- app/views/landing/index.html.erb
Changed slides 5 and 7 for UrtheCast release.
> Added carousel slide for UrtheCast

- app/assets/stylesheets/layouts/_landing.scss
Changed out photos for slide 5 and 7.
> Added photo for UrtheCast

- app/assets/javascripts/map/helpers/guide.js
- app/assets/javascripts/map/helpers/guidetexts.js
- app/assets/javascripts/map/views/GuideView.js
- app/assets/stylesheets/modules/_guide.scss
- bower.json
- config/requirejs.yml
Bower install !!!!!!!!! It will install the js-cookie library (3.2kb)
Tour works the first time you enter the map and whenever there is the tour param at the map url. 
After that, we set a cookie and the tour doesn't open again on further visits.
> Tour with intro step. Cookie implemented. Remeber to bower install

- app/assets/javascripts/map/presenters/TabsPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/presenters/tabs/CountriesPresenter.js
- app/assets/javascripts/map/services/PlaceService.js
- app/assets/javascripts/map/views/tabs/CountriesView.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- app/assets/stylesheets/_header1600.scss
- Remove all triggers from other Views (only the ones which are at the 'Place/go' mps subscription).
- Little fix of the logo on the map
> Tabs are now saved in url.

- app/assets/javascripts/connect/routers/UserRouter.js
- app/assets/javascripts/connect/templates/subscriptionList.handlebars
- app/assets/javascripts/connect/templates/subscriptionListItemDeleteConfirm.handlebars
- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/javascripts/connect/views/SubscriptionListItemDeleteConfirmView.js
- app/assets/javascripts/connect/views/SubscriptionListItemView.js
- app/assets/javascripts/connect/views/SubscriptionListView.js
- app/assets/javascripts/connect/views/UserFormView.js
- app/assets/stylesheets/modules/_buttons1600.scss
- app/assets/stylesheets/modules/connect/_connect-form.scss
- app/views/layouts/connect.html.erb
- app/views/shared/_notifications.html.erb
Improves the design of the My GFW pieces, like the subscriptions list.
> My GFW design improvements

- app/helpers/map_helper.rb
- app/views/layouts/map.html.erb
- app/views/shared/_header_landing.erb
- app/views/shared/_js_config.html.erb
- app/views/shared/_js_footer.html.erb
> Fixes map embeds

- app/assets/javascripts/abstract/layer/CartoDbCanvasLayerClass.js
- app/assets/javascripts/map/services/CartoDbLayerService.js
Also refactors my animation code for the timeline so that it actually makes sense :grimacing:
> Use named maps for GLAD layer

- app/views/countries/_countries.html.erb
Remember to change the link to plantations layer before going to production.
> Typo changes

- app/assets/javascripts/abstract/layer/ImageLayerClass.js
- app/assets/javascripts/map/presenters/GuidePresenter.js
- app/assets/javascripts/map/views/layers/UrthecastLayer.js
- app/views/shared/_notifications.html.erb
- Spinner added to urthecast image loading process.
- Notification typo change
- Cleaning some code
> Spinner added to loading of urthecast images. Cleaning. typo change

- app/views/static/getinvolved.html.erb
- New text added
- We are expecting the new link of the Guidelines for Applicants.
> Small grants fund typo change

- app/assets/javascripts/abstract/layer/ImageLayerClass.js
- app/assets/javascripts/map/presenters/tabs/HighresolutionPresenter.js
- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/layers/UrthecastLayer.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- app/views/shared/_notifications.html.erb
- Minzoom lowered to 5.
- Notifications behaviour improved
> Urthecast: lower minzoom to 5. Notifications behaviour improved

- app/assets/javascripts/templates/sourceModal.handlebars
- app/assets/javascripts/views/SourceModalView.js
- app/assets/stylesheets/modules/_modal_new.scss
- app/assets/stylesheets/modules/_shared1600.scss
- Only show fields that exist
- Translated overview
- Spinner for info icons (Let's talk with Sergio about this)
> Some metadata amendments

- app/assets/images/countries/tree-mask.svg
- app/assets/javascripts/countries/views/CountryHeaderView.js
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/pantropical.handlebars
- app/assets/javascripts/map/views/layers/KhmProtectedAreasLayer.js
- app/assets/javascripts/map/views/layers/PerMiningLayer.js
- app/assets/stylesheets/_settings1600.scss
- app/assets/stylesheets/modules/countries/_show.scss
- app/controllers/countries_controller.rb
- app/views/countries/_countries.html.erb
- app/views/countries/show.html.erb
- app/views/shared/_sources_map.html.erb
New plantation layer and widget:
- It's located under land cover category and inside many countries (BRA, COL, IDN, KHM, LBR, MYS, PER).
- After deploying, we should change the display of the country layers to true (in layerspec). Then, increase the cache version.
- New widget added to country pages. (Loss outsides plantations)
> Disposable plantations (to be merged at 00:00)

- app/views/landing/index.html.erb
Added text for new plantations slide.
> Added Plantations Carousel

- app/assets/stylesheets/layouts/_landing.scss
Added photo for plantations carousel slide.
> Added plantations Carousel photo

- app/views/landing/index.html.erb
One of the tags was missing a closing bracket.
> Fixed text for UrtheCast

- app/views/landing/index.html.erb
Replaced "Explore" slide with a permanent slide for GFW Climate.
> Created permanent Climate slide

- app/assets/stylesheets/layouts/_landing.scss
Added Permanent Climate Carousel Slide Photo
> Added photo for Climate Slide

- app/assets/javascripts/map/templates/tabs/countriesIso.handlebars
Got rid of extra "View" in "View Global Datasets in this country".
> Removed extra word

- app/views/landing/index.html.erb
Switched Report and Climate slides so that Climate is next to Fires and Commodities.
> Switched slides 1 and 2

- app/assets/stylesheets/layouts/_landing.scss
Switched Climate and Report a Story slide photos.
> Changed photos for slides 1 and 2

- app/assets/javascripts/abstract/layer/ImageLayerClass.js
- app/assets/javascripts/abstract/layer/OverlayLayerClass.js
- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/layers/UrthecastLayer.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- Some bulletproofs to prevent javascript crashing.
- Sensor filter added.
- We still need to manage the maxZooms for each renderer + sensor
> Filter by sensor added

- app/assets/javascripts/map/views/layers/KhmEcoLandLayer.js
before your deploy and add to it please
> solved conflict with column names

- app/views/static/getinvolved.html.erb
Changed "Apply Now" section for Small Grants Fund since the application period is closed.
> Got rid of Apply Now for SGF

- app/views/landing/index.html.erb
Replaced the "Report a Story" slide with the "Explore the GFW Interactive Map" slide.
> Replaced Report Slide with Explore Slide

- app/assets/stylesheets/layouts/_landing.scss
Replaced "Report a Story" slide photo with "Explore Interactive Map" slide photo.
> Changed photo for Explore slide

- app/assets/javascripts/map/templates/layersNav.handlebars
> Prodes enabled

- app/views/landing/index.html.erb
Added link and text for GLAD preview blog.
> Added GLAD preview slide

- app/assets/stylesheets/layouts/_landing.scss
Added photo for GLAD preview blog link.
> Updated carousel photo for GLAD preview

- app/assets/javascripts/map/templates/legend/glad.handlebars
- app/assets/javascripts/map/views/LegendView.js
> GLAD: legend

- app/assets/stylesheets/layouts/_landing.scss
Added a photo for the GLAD release slide.
> Added photo for GLAD slide

- app/views/landing/index.html.erb
Added slide for GLAD Alerts launch.
> Added GLAD launch slide

- app/assets/stylesheets/layouts/_landing.scss
Uploaded a higher resolution image for the GLAD Alerts carousel slide.
> Added higher res Image for GLAD Slide

- app/assets/stylesheets/layouts/_landing.scss
The other photo was still blurry so I uploaded a new one.
> Changed Photo for GLAD Slide

- app/views/landing/index.html.erb
Added credit for new photo for GLAD Alerts slide.
> Added photo credit for new image

- app/views/static/about.html.erb
Added "for" to "Center for Global Development".
> Fixed Typo with CGD

- app/views/embed/countries_show_info.html.erb
Changed "appoximately" to "approximately"
> Fixed "appoximately" typo

- app/assets/javascripts/map/views/layers/CustomInfowindow.js
- Check if the popup element exists before attach it events
- Remove => always enable mousewheel scroll to map
> Map: ejn infowindows

- app/assets/javascripts/map/cartocss/concesiones_peru.cartocss
- app/assets/javascripts/map/cartocss/concesiones_peruTypes.cartocss
- app/assets/javascripts/map/templates/legend/concesiones_forestales.handlebars
- app/assets/javascripts/map/templates/legend/concesiones_forestalesType.handlebars
- app/assets/javascripts/map/views/layers/ConcesionesForestalesLayer.js
- app/assets/javascripts/map/views/layers/ConcesionesForestalesNotSupervisedLayer.js
https://basecamp.com/3063126/projects/10726176/todos/241276199
> modify peru concesions

- app/assets/javascripts/map/queries/as_it_happens_hybrid_raster.sql.hbs
> updated glad

- app/assets/javascripts/map/views/layers/UrthecastLayer.js
I just deployed the staging API with the Urthecast endpoint merged in and the correct API keys, so it should work whenever this PR gets deployed.
> Use pro/staging API for urthecast

- app/views/landing/index.html.erb
New carousel slide for tiger blog.
> Added carousel slide

- app/assets/stylesheets/layouts/_landing.scss
Added a photo for tiger blog carousel slide.
> Added photo for Tiger slide

- app/views/countries/_countries.html.erb
For "type of forest" graphic - edited info window text to include "naturally regenerated".
> Edited info window text

- app/assets/javascripts/countries/templates/burnedForestTooltip.handlebars
- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/stylesheets/modules/countries/_show.scss
Some improvements that will make our life easier :smile:
> Country: burned graph improved

- app/helpers/stories_helper.rb
- app/views/stories/show.html.erb
The story page would break if no media was present
> Fixes issue where certain combinations of media would break the story show page

- app/assets/javascripts/map/cartocss/polygon_polygonSymbolizer.xml
- app/assets/javascripts/map/templates/legend/raisg_land_rights.handlebars
this need to be deployed to master also when Mikaela say us that the made the change on their side!
> Change legends definition

- app/assets/javascripts/static/ApplicationsModalView.js
- app/assets/javascripts/static/helpers/applicationsHelper.js
- app/assets/javascripts/static/templates/applications.handlebars
> Added app to Explore page

- app/assets/javascripts/connect/views/SubscriptionListView.js
- app/assets/javascripts/static/SearchView.js
- When a user deletes an entire page automatically the paginator will render the previous page if it exists.
- Paginator svg added to search and subscriptions paginators
> My gfw bug

- app/mailers/mobile_download.rb
- app/mailers/your_mailer.rb
- config/application.rb
Same as #2204 but for production
> Mail updates for production

- app/assets/stylesheets/layouts/_landing.scss
Added new carousel photo for peat blog.
> Added Peat Photo

- app/views/landing/index.html.erb
Added text and link for peat slide.
> Added peat slide

- app/assets/javascripts/map/views/layers/RaisgLayer.js
- app/assets/javascripts/map/views/layers/RaisgMiningLayer.js
> raisg new url

- app/assets/javascripts/abstract/timeline/TimelineBtnClass.js
- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/cartocss/viirs.cartocss
- app/assets/javascripts/map/helpers/FiresDatesHelper.js
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/services/AnalysisService.js
- app/assets/javascripts/map/services/LayerSpecService.js
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/FiresLayer.js
- app/assets/javascripts/map/views/layers/ViirsLayer.js
- app/assets/javascripts/map/views/timeline/FiresTimeline.js
- jstest/spec/AnalysisPresenter_spec.js
@aagm the layer doesn't seem to be working now (or on staging), can you look in to it?
@mbarrenechea once alicia has got the layer working, can you test to make sure all is OK on the front-end and then deploy to production once Mikaela gives the go ahead? see here https://basecamp.com/3063126/projects/10726176/todos/231371569#comment_417848709
> VIIRS for production

- app/assets/javascripts/map/cartocss/Places2Watch.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/places2watch.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/Places2WatchLayer.js
chequealo y para staging please!
> places to watch proof of concept

- app/assets/javascripts/map/views/layers/ViirsLayer.js
Separate hours and minutes on acquisition time:
> Use a semicolon separator for hours and minutes

- app/assets/javascripts/map/cartocss/Guyra.cartocss
- app/assets/javascripts/map/views/layers/GuyraLayer.js
this should also need to go to master
> solved issue with dates in guyra layer

- app/assets/javascripts/map/views/layers/PantropicalLayer.js
- app/assets/stylesheets/modules/map/_module-legend.scss
> biomass change colouring

- app/assets/javascripts/map/templates/timeline.handlebars
> center timeline for all layers on big resolutions

- app/assets/javascripts/map/presenters/LayersCountryPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/presenters/tabs/CountriesPresenter.js
- app/assets/javascripts/map/views/tabs/AnalysisView.js
Don't analyze param in new country dropdown didn't work. Now it's fixed
P.S: We really need to refactor the analysis module...
> Dont analyze param handler

- app/assets/stylesheets/_header1600.scss
- app/views/shared/_navbar2_landing.html.erb
We will be updating this links in the following days. But right now, we can merge this PR
> New submenu styles and links

- app/assets/javascripts/map/views/tabs/AnalysisView.js
> Fix: drawing a polygon set the dont_analyze param to true

- app/assets/javascripts/map/cartocss/Places2Watch.cartocss
- app/assets/javascripts/map/templates/legend/places2watch.handlebars
Update of the legend and the steps.
> Places to watch simplified

- app/views/shared/_navbar2_landing.html.erb
I don't need anyone to review this code
> Change menu typo

- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/views/tabs/AnalysisView.js
Analytics event for uploading shape
> Analytic event for upload files

- app/assets/stylesheets/layouts/_sitemap.scss
> Sitemap styles

- app/assets/javascripts/map/templates/analysis/analysisResults.handlebars
- app/assets/javascripts/map/templates/tabs/analysis.handlebars
- app/assets/javascripts/templates/confirmModal.handlebars
- app/assets/stylesheets/modules/_terms.scss
- app/views/countries/_header.html.erb
- app/views/countries/overview.html.erb
- app/views/countries/show.html.erb
- app/views/static/terms.html.erb
- app/views/stories/_form.html.erb
- app/views/stories/new.html.erb
It also removes the target="_blank" from the terms link
> Add back link to ToS

- app/assets/stylesheets/layouts/_landing.scss
Added carousel photo for PALM risk tool.
> Added photo for PALM tool

- app/views/landing/index.html.erb
Added link and slide text for new PALM risk tool.
> Added new slide for PALM Risk Tool

- app/views/landing/index.html.erb
Updated photo credit for PALM risk tool carousel slide.
> Updated photo credit for PALM slide

- app/assets/stylesheets/layouts/_landing.scss
Changed photo for PALM Risk Tool slide.
> Updated photo for PALM Risk Tool

- app/assets/javascripts/map/presenters/MapPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- fix to geom if the param `fix_to_geom` exists
- console.log removed
> Fix: fit to geom fixed

- app/views/small_grants_fund/index.html.erb
> SGF: link to howto faqs with a filter

- app/assets/javascripts/static-pages/views/SliderView.js
- app/assets/javascripts/static-pages/views/SmallGrantsFundView.js
- app/views/small_grants_fund/index.html.erb
- config/routes.rb
this PR contains:
- redirection to new SGF page
- little typo amendments
- autoplay enabled in lory sliders
> Redirection added. Infinite carousel

- config.ru
- config/routes.rb
Remember to add `DEVELOPERS_URL=http://vizzuality.github.io/gfw-atlas` to the .env file
> Proxy to get developers corner

- app/assets/javascripts/map/views/layers/GladLayer.js
Use new tiles from Charlie and handle the changed RGB encoding. We're also decoding the intensity here, but not yet using it when rendering the points.
> Handle new GLAD tile encoding

- app/assets/stylesheets/_header1600.scss
- app/assets/stylesheets/layouts/_sitemap.scss
- app/assets/stylesheets/modules/_shared1600.scss
- app/assets/stylesheets/modules/_terms.scss
- app/views/map/index.html.erb
- app/views/sitemap/index.html.erb
- app/views/static/terms.html.erb
- app/views/stories/index.html.erb
- sitemap back button
- Get rid of the application menu inside sitemap
> Sitemap amendments

- app/views/stories/_form.html.erb
- Change location field to a hidden value. We should get rid of it but let's wait until we refactor the stories page.
> Location set as hidden value

- app/assets/javascripts/map/services/MapLayerService.js
- app/assets/javascripts/map/templates/layersCountry.handlebars
This PR fix the wrapped layer title
> Title of wrapped layers comes from the does_wrapper object

- app/assets/stylesheets/layouts/_sitemap.scss
- app/assets/stylesheets/sitemap.scss
- app/views/sitemap/index.html.erb
- Links changed
- Back button
- Some style fixes
> Links, styles and back button

- app/assets/javascripts/map/templates/analysis/analysisResults.handlebars
- app/views/countries/_header.html.erb
- warning text
- warning always present in loss, gain and tree cover analysis
> Warning text changed

- app/assets/stylesheets/layouts/_header.scss
- app/views/countries/index.html.erb
- app/views/countries/overview.html.erb
- app/views/countries/show.html.erb
- app/views/map/index.html.erb
- app/views/shared/_navbar2_landing.html.erb
- app/views/sitemap/index.html.erb
- app/views/small_grants_fund/index.html.erb
- app/views/static/terms.html.erb
- app/views/stories/crowdsourcedstories.html.erb
- app/views/stories/index.html.erb
- app/views/stories/new.html.erb
- app/views/stories/show.html.erb
This PR will remove the 'beta' ribbon from all the logos of the GFW pages. It will also add a 'stories' ribbon to the story pages.
> Remove beta ribbon and add stories ribbon

- app/assets/javascripts/templates/sourceModal.handlebars
- app/assets/javascripts/views/SourceModalView.js
- app/assets/stylesheets/modules/_modal_new.scss
- New URLs for the "open in ArcGis" and "open in CartoDB" buttons
- We still need to ask WRI to fill the correct field for "open in CartoDB"
> Open in Cartodb/Arcgis buttons inside modal footer

- app/assets/javascripts/map/presenters/LegendPresenter.js
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/stylesheets/modules/map/_module-legend.scss
- Render forest atlas link if it exists
- Don't hide the legend if a country is set
> Legend: forest atlas button added

- app/views/small_grants_fund/index.html.erb
Fixed a small typo on the new Small Grants Fund page.
> Fixed typo in new SGF page

- app/assets/javascripts/stories/views/StoriesNewView.js
This change wasn't merged in the last deploy.
> Draggable images in submit story page

- app/helpers/stories_helper.rb
- app/views/stories/show.html.erb
this PR handles the bugs that have appeared in the story pages
> Stories: do not show the preview video image

- app/assets/javascripts/views/SourceModalView.js
They are going to use a .zip file instead of an SQL
> Remove parse from the oneclick button

- app/views/landing/index.html.erb
Added carousel slide for fire risk blog.
> Added Fire Risk Carousel

- app/assets/stylesheets/layouts/_landing.scss
Added photo for fire risk carousel slide.
> Updated photos for Fire Risk blog

- app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineDatePicker.js
- app/assets/javascripts/map/presenters/TorqueTimelinePresenter.js
- app/assets/javascripts/map/services/GladDateService.js
- app/assets/javascripts/map/views/layers/GladLayer.js
The GLAD timeline should show the most recent date as "June 30 2016" and also highlight pretty much every day in the date picker with a green dot, showing that data is available for that day.
> Retrieve GLAD occurrence dates

- app/assets/javascripts/map/helpers/guides.js
- app/assets/javascripts/map/presenters/GuidePresenter.js
- app/assets/javascripts/map/views/GuideView.js
Fix bug not showing the modal after finish
Unify the logic into the presenter
> Fix bug and move logic to presenter

- app/assets/javascripts/map/views/layers/UrthecastLayer.js
Now if you found a zone without imagery available making zoom the notification will appear.
> Add change zoom listener to check if has imagery available

- app/assets/stylesheets/static-pages/modules/_section.scss
- app/views/small_grants_fund/index.html.erb
This Pr fix the mobile styles of the Small Grants Fund page
> SGF: style fixes

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/views/layers/GladCoverageLayer.js
- app/assets/stylesheets/modules/map/_module-legend.scss
* Update styling for confirmed alerts toggle
* Update layer coerage with brazil
> Small GLAD fixes

- app/assets/javascripts/map/presenters/LayersCountryPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/templates/tabs.handlebars
- app/assets/javascripts/map/views/TabsView.js
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- Remove layers from country if I change it by analyzing it.
- Allow wdpaid subscriptions
- Little refactor of subscription view
> Analysis: many bugs solved

- app/assets/javascripts/stories/collections/StoriesCollection.js
- app/assets/javascripts/stories/templates/new_story.handlebars
- app/assets/javascripts/stories/utilities/story.js
- app/assets/javascripts/stories/views/StoriesNewView.js
- app/assets/stylesheets/modules/_form.scss
- config/requirejs.yml
- Remove an image from the media collection once you remove it
- Validate js added to validate forms, instead of doing it manually
Remember to `bower install`
> Stories: remove image from media collection if the user removes it

- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/views/tabs/SubscribeView.js
When you were not logged, the subscription modal didn't appear. Now it's fixed because I render the subscription modal even if the fetch of the user model fails.
> Map: subscription render bug solved

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/javascripts/stories/templates/new_story.handlebars
- app/assets/javascripts/views/SourceModalView.js
- app/views/countries/show.html.erb
- app/views/static/about.html.erb
Add the correct class to all mailto links along the app to open the contact us modal.
> Add the correct class to all mailto links

- app/assets/javascripts/map/views/layers/GladLayer.js
- The default dates of Glad don't override the dates if they are in the URL
> Glad: if there is a date do not override it with the default ones

- app/assets/javascripts/map/helpers/guides.js
- app/assets/javascripts/map/helpers/guidetexts.js
- app/assets/javascripts/map/presenters/GuidePresenter.js
- app/assets/javascripts/map/views/GuideView.js
- app/assets/stylesheets/modules/_guide.scss
- General tour shortened
- Bug fixed: no chance of negative height
> Map: general tour shortened

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/javascripts/map/templates/layersCountry.handlebars
- app/assets/javascripts/map/templates/tabs/countries.handlebars
- app/assets/javascripts/map/templates/tabs/countriesMobile.handlebars
- app/assets/javascripts/stories/templates/new_story.handlebars
- app/assets/javascripts/views/SourceModalView.js
- app/assets/stylesheets/static-pages/modules/_section.scss
- app/views/countries/show.html.erb
- app/views/small_grants_fund/index.html.erb
- app/views/static/about.html.erb
This PR is for deploying:
- The contact us links. 
- Little style bug in SGF page.
> Contact us links

- app/assets/javascripts/abstract/timeline/GladTimelineDatePicker.js
- Fixes GLAD timeline timezone issues
> Fix: Glad - Timeline timezone issues

- app/assets/javascripts/connect/routers/UserRouter.js
- app/assets/stylesheets/connect.scss
- app/assets/stylesheets/modules/static/_spinner.scss
- app/views/connect/index.html.erb
- Re-render the view whenever the route changes.
- Same spinner for all the app
> MYGFW subscriptions amendments

- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
Subscribe to countries by clicking on the subscribe button above country layer dropdown.
> Map: subscribe to countries by clicking on the subscribe button

- app/assets/javascripts/map/helpers/guides.js
- app/assets/javascripts/map/presenters/GuidePresenter.js
- app/assets/javascripts/map/presenters/analysis/AnalysisDrawPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/views/GuideView.js
This will prevent the issue of storing the geojson in two databases
> Map: Use a geojson instead a geostore for the Glad walkthrough

- app/assets/javascripts/map/presenters/analysis/AnalysisDrawPresenter.js
- app/assets/javascripts/map/services/ShapefileNewService.js
- app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
- app/views/shared/_notifications.html.erb
This PR will show an error notification when a user tries to upload an invalid file
> Notifications added to upload files workflow

- app/views/countries/show.html.erb
This PR solves a bad merge that we didi with the country pages. I just copied all the code from develop and pasted it to master.
> HOTFIX: Country page well merged (we need to deploy it to PRO as soon as possible)

- app/views/landing/index.html.erb
Added text, url link and image credit for new GLAD Brazil slide.
> Added slide for GLAD Brazil

- app/assets/stylesheets/layouts/_landing.scss
Added a photo for the GLAD Brazil carousel slide.
> Added photo for GLAD Brazil slide

- app/assets/javascripts/map.js
- app/assets/javascripts/map/services/CountryService.js
- app/assets/javascripts/map/views/LayersCountryView.js
- app/assets/stylesheets/modules/map/_analysis-draw.scss
- app/assets/stylesheets/modules/map/_tab-analysis.scss
This PR adds the following:
- Style amendments for each change of the language
- Cache again the CountryService. We are now storing only 167 countries
> Map: amendments related to lang change

- app/assets/stylesheets/layouts/_landing.scss
Added the processed photos for the first 2 carousel slides. Thanks!
> Added smaller photos for carousel

- app/assets/javascripts/templates/sourceModal.handlebars
- app/assets/javascripts/views/SourceModalView.js
This Pr makes sure that cartodb one click won't appear again.
> Map: check if the source download is available

- app/views/landing/index.html.erb
- app/views/sitemap/index.html.erb
This PR add to master branch the Water changes that we did long time ago
> Water deploy amendments

- app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineSlider.js
- app/assets/javascripts/map/services/TerraiDateService.js
- app/assets/javascripts/map/views/layers/GladLayer.js
- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
- app/assets/javascripts/map/views/timeline/GladTimeline.js
- app/assets/javascripts/map/views/timeline/TerraiTimeline.js
- app/assets/stylesheets/modules/map/_timeline-torque.scss
- app/assets/stylesheets/modules/map/_timeline.scss
- Added the Terra-i canvas layer with a timeline.
- The calendar shows the latest dates with data.
- Small refactor to use the same system as GLAD for this and future similar cases.
- A few fixes to the general timeline's functionality.
> Feat - Terra-i Canvas Layer with timeline

- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
Fixes the data max zoom to 10.
> Fix: Terra-i - Max level set to 10

- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
Recent alerts for the Terra-i layer are now highlighted:
> Feat: Terra-i - Recent alerts

- app/views/landing/index.html.erb
Added a new carousel slide for GFW Water.
> Added slide for GFW Water

- app/assets/stylesheets/layouts/_landing.scss
Added link to photo for the new GFW Water carousel slide.
> Added photo for GFW Water slide

- app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
- app/assets/stylesheets/modules/map/_timeline-torque-date-picker.scss
- app/assets/stylesheets/modules/map/_timeline.scss
- Fixes the calendar's position
- Slider position is now working for all screen sizes
- Fixes the canvas rendering for recent alerts
> Fix: Terra-i - Calendar position, canvas rendering for recent alerts

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/javascripts/connect/views/UserFormView.js
Let users select the global language of confirmation emails related to everything but subscriptions.
> Profile: language selector

- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/static/ContributeDataView.js
- app/assets/javascripts/stories/views/StoriesNewView.js
- app/assets/mails/contribute-data-confirmation/contribute-data-confirmation-en.html
- app/assets/mails/contribute-data/contribute-data-en.html
- app/assets/mails/contribute-data/contribute-data.html
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/_section-new.scss
- app/controllers/data_controller.rb
- app/uploaders/data_uploader.rb
- app/views/shared/_notifications.html.erb
- app/views/static/contribute.html.erb
- config/routes.rb
This PR allows users to upload files
> Contribute data: Upload files

- app/assets/javascripts/map/presenters/layers/FormaLayerPresenter.js
- app/assets/javascripts/map/views/layers/FormaLayer.js
- Added the first version of the FORMA canvas layer
> Feat: FORMA Canvas Layer

- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/presenters/layers/Forma2016LayerPresenter.js
- app/assets/javascripts/map/presenters/layers/FormaLayerPresenter.js
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/views/layers/Forma2016Layer.js
- app/assets/javascripts/map/views/layers/FormaLayer.js
Note: This is a test layer and should NOT be deployed to master.
> Feat: FORMA 250 (2016) layer

- app/assets/javascripts/abstract/timeline/GladTimelineDatePicker.js
- app/assets/javascripts/map/services/GladDateService.js
- app/assets/javascripts/map/views/layers/GladLayer.js
- This fixes the issue with a day off on Production in GLAD's calendar selector.
- It involves an API deploy as well.
> Feat: GLAD - Timeline dates

- app/assets/javascripts/static/ContributeDataView.js
- app/assets/mails/contribute-data-confirmation/contribute-data-confirmation-en.html
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/static/_spinner.scss
- app/uploaders/data_uploader.rb
- app/views/shared/_notifications.html.erb
- app/views/static/contribute.html.erb
- Spinner added when a user uploads a file
- Notifications handled
> Upload behaviour

- app/assets/javascripts/connect/templates/subscriptionListItem.handlebars
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
Fixed some languages codes that were missing their country code
> Feat: Language selectors - Added missing lang code

- app/assets/mails/data-contribution-confirmation/data-contribution-confirmation-es_MX.html
- app/assets/mails/data-contribution-confirmation/data-contribution-confirmation-fr.html
- app/assets/mails/data-contribution-confirmation/data-contribution-confirmation-id.html
- app/assets/mails/data-contribution-confirmation/data-contribution-confirmation-pt_BR.html
- app/assets/mails/data-contribution-confirmation/data-contribution-confirmation-zh.html
- app/assets/mails/subscriptions-confirmation/subscriptions-confirmation-en.html
- app/assets/mails/subscriptions-confirmation/subscriptions-confirmation-es_MX.html
- app/assets/mails/subscriptions-confirmation/subscriptions-confirmation-fr.html
- app/assets/mails/subscriptions-confirmation/subscriptions-confirmation-zh.html
Added new translations templates and some updates.
> Feat: Mails - New templates and updates

- app/assets/javascripts/static/ContributeDataView.js
- app/assets/javascripts/static/GalleryView.js
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/static.scss
- app/views/static/contribute.html.erb
- Mandatory fields added (data_permission, data_updating)
- Field added (other_name)
- New behavior for uploading files (We allow users to only share a link)
> Contribute data

- app/assets/stylesheets/modules/map/_timeline-torque-date-picker.scss
- app/assets/stylesheets/modules/map/_timeline-torque.scss
- app/assets/stylesheets/modules/map/_timeline.scss
Fixes several timelines CSS issues on mobile
> Fix: Timelines - Several issues on mobile

- app/assets/javascripts/connect/views/UserFormModalView.js
- app/assets/javascripts/connect/views/UserFormView.js
- app/assets/javascripts/helpers/languagesHelper.js
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/javascripts/models/UserModel.js
- Added new languages helper to manage the key languages of the platform (pending to update a few static selectors)
- New get language method under the user model, to get the language from its profile or from the browser if there no language selected.
> Feat: Global languages helper and subscription select list update

- app/assets/mails/new-story/new-story-en.html
- app/assets/mails/new-story/new-story-es_MX.html
- app/assets/mails/new-story/new-story-fr.html
- app/assets/mails/new-story/new-story-id.html
- app/assets/mails/new-story/new-story-pt_BR.html
- app/assets/mails/new-story/new-story-zh.html
Updated the feedback link in some templates
> Feat: Mails - Updated feedback link

- app/assets/javascripts/abstract/layer/CanvasJSONLayerClass.js
- app/assets/javascripts/abstract/layer/CanvasLayerClass.js
- app/assets/javascripts/abstract/layer/CartoDBLayerClass.js
- app/assets/javascripts/abstract/layer/ImageLayerClass.js
- app/assets/javascripts/abstract/layer/ImageMaptypeLayerClass.js
- app/assets/javascripts/abstract/layer/MarkersLayerClass.js
- app/assets/javascripts/abstract/layer/OverlayLayerClass.js
- app/assets/javascripts/abstract/layer/TorqueLayerClass.js
- app/assets/javascripts/abstract/layer/WMSLayerClass.js
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDataSelection.handlebars
- app/assets/javascripts/connect/views/MapMiniSelectedView.js
- app/assets/javascripts/connect/views/MapMiniView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/stylesheets/global/_animations.scss
- app/assets/stylesheets/modules/_section-new.scss
This PR adds:
- Clear selection
- Info selection
- Loader
> New subscription

- app/views/shared/_google_carto.html.erb
- Google Maps API version changed to the latest stable version 3.21
> Feature: Map - Google maps API changed to the latest stable version

- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- Specified the format we were passing to moment to avoid a deprecated warning.
> Fix: High resolution image - Removed moment warning

- app/assets/mails/fires-notification/fires-notification-id.html
- app/assets/mails/fires-notification/fires-notification-zh.html
Fixed some typos for ID and ZH templates for the Fire Alerts
> Fix: Mails - Fire alerts: Links typos

- app/assets/javascripts/connect/templates/countrySelection.handlebars
- app/assets/javascripts/connect/templates/layerSelection.handlebars
- app/assets/javascripts/connect/templates/regionSelection.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/CountrySelectionView.js
- app/assets/javascripts/connect/views/LayerSelectionView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/_section-new.scss
- app/assets/stylesheets/modules/_select.scss
This PR adds:
- Field sizes 
- Country layers (we should filter the array of countries to have only the ones that have layers)
> Subscription: country layers

- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/templates/tabs-mobile.handlebars
- app/assets/javascripts/map/templates/tabs.handlebars
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/javascripts/static/ApplicationsModalView.js
- app/assets/javascripts/views/ConfirmModalView.js
- app/assets/javascripts/views/ModalView.js
- app/assets/javascripts/views/SourceModalView.js
- app/assets/stylesheets/map.scss
- app/assets/stylesheets/modules/_modal_new.scss
- app/assets/stylesheets/modules/map/_subscription-modal.scss
- app/views/connect/index.html.erb
This PR adds:
- Migration of the old subscription modal to the new modalView.
> Subscription modal enabled for mobile devices

- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
Results numbers below 10 will not fix unless they have decimals.
> Map: fires analysis results 

- app/assets/javascripts/map/views/layers/CustomInfowindow.js
- app/assets/javascripts/map/views/layers/UrthecastLayer.js
Show Urthecast tile info on each click
> Map: urthecast infowindow

- app/assets/javascripts/abstract/layer/CanvasJSONLayerClass.js
- app/assets/javascripts/abstract/timeline/TimelineMonthlyPicker.js
- app/assets/javascripts/map/presenters/TorqueTimelinePresenter.js
- app/assets/javascripts/map/views/timeline/TerraiTimeline.js
- app/assets/javascripts/templates/monthlyPickerTorque.handlebars
- app/assets/stylesheets/map.scss
- app/assets/stylesheets/modules/map/_timeline-torque-monthly-picker.scss
- Fixed missing dependency in the Canvas JSON Class.
- Added new monthly timeline for Terra-i:
g
Pending: Mobile template for the timeline.
> Feat: Terra-i monthly torque selector

- app/controllers/static_controller.rb
allowing for files with the same name.
> Add secure random to generate unique paths for files. 

- app/assets/mails/fires-notification/fires-notification-en.html
- app/assets/mails/fires-notification/fires-notification-es_MX.html
- app/assets/mails/fires-notification/fires-notification-fr.html
- app/assets/mails/fires-notification/fires-notification-id.html
- app/assets/mails/fires-notification/fires-notification-pt_BR.html
- app/assets/mails/fires-notification/fires-notification-zh.html
- app/assets/mails/forest-change-notification/forest-change-notification-en.html
- app/assets/mails/forest-change-notification/forest-change-notification-es_MX.html
- app/assets/mails/forest-change-notification/forest-change-notification-fr.html
- app/assets/mails/forest-change-notification/forest-change-notification-id.html
- app/assets/mails/forest-change-notification/forest-change-notification-pt_BR.html
- app/assets/mails/forest-change-notification/forest-change-notification-zh.html
This PR adds:
- `alert_date_begin` and `alert_date_end` to mails
> Mails: translate date of alerts

- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
- app/assets/javascripts/map/views/layers/CustomInfowindow.js
- app/assets/javascripts/map/views/layers/UrthecastLayer.js
- app/assets/stylesheets/layouts/_header.scss
- app/views/small_grants_fund/index.html.erb
- config/routes.rb
This PR adds to production a bunch of little fixes along the app
> Little fixes

- app/assets/javascripts/abstract/timeline/TimelineMonthlyPicker.js
- app/assets/javascripts/map/presenters/TorqueTimelinePresenter.js
- app/assets/javascripts/templates/monthlyPickerTorque.handlebars
- app/assets/stylesheets/modules/map/_timeline-torque-monthly-picker.scss
- New month timeline selectors
> Terra i timeline

- app/assets/javascripts/connect/views/SubscriptionNewView.js
- Fixed use of var instead of let to avoid cross-browser issues.
> Fix: My subscriptions - iOS 9 bug use of let instead of var

- app/assets/javascripts/abstract/timeline/TimelineMonthlyPicker.js
- Temp: Re-rendering for mobile
> Fix: Terra-i - Selectors limits

- app/views/shared/_google_carto.html.erb
> Feat: Map - Google Maps Api Version 3.22

- app/assets/stylesheets/modules/map/_timeline-month.scss
- app/assets/stylesheets/modules/map/_timeline-torque.scss
This Pr contains some style amendments for the mobile timelines
> Timeline: mobile style amendments

- app/assets/javascripts/map/views/layers/GladLayer.js
> staging url changed for glad

- app/assets/stylesheets/modules/map/_timeline-torque.scss
Add min-width to torque-timeline legend
> Add min-width to torque-timeline legend

- app/assets/javascripts/helpers/languagesHelper.js
Remove the parenthesis details in the language selector.
> Update languages literals in subscription selector

- app/assets/stylesheets/modules/map/_timeline.scss
- Removed unnecessary min width for mobile resolutions.
> Fix: Timeline - removed unnecessary min width

- app/assets/stylesheets/layouts/_landing.scss
Added image for Map Builder carousel slide.
> Added Image for Map Builder

- app/views/shared/_sources_map.html.erb
- Updated text for the allowed datasets formats.
> Feat: Map - Uplodad datasets allowed formats

- app/views/landing/index.html.erb
Added a carousel slide for Map Builder.
> Added Map Builder Carousel Slide

- app/views/small_grants_fund/index.html.erb
- Fix broken to the blog (Announcing the 2016 Recipients of the Small Grants Fund)
> Fix: Small Grant Funds - Broken blog link

- app/views/landing/index.html.erb
> Fix: Landing - Updated blog link

- app/assets/javascripts/stories/templates/story.handlebars
- app/assets/stylesheets/layouts/_landing.scss
- app/views/landing/index.html.erb
- app/views/shared/_sources_map.html.erb
- app/views/small_grants_fund/index.html.erb
- config/routes.rb
- Landing slider updates
- Stories links fixed
- Grant funds broken link
- Upload of datasets: allowed formats text change
> Landing slider updates and stories link

- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
Contribute data link inside the subscription confirmation window in the map
> Feat: Map - Contribute data link in subscription confirmation popup

- app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
Hide a drawn geojson completely if all forest change layers have been turned off
> Fix: Map - Hide geojson when all forest change layers have been turned off

- app/assets/javascripts/map/views/controls/SearchboxView.js
Added option to remove marker on hover:
> Feat: Map Search - Marker with remove button

- app/assets/javascripts/connect.js
- app/assets/javascripts/connect/models/Subscription.js
- app/assets/javascripts/connect/router.js
- app/assets/javascripts/connect/templates/layerSelection.handlebars
- app/assets/javascripts/connect/templates/regionSelection.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/CountrySelectionView.js
- app/assets/javascripts/connect/views/LayerSelectionView.js
- app/assets/javascripts/connect/views/MapMiniDrawingView.js
- app/assets/javascripts/connect/views/MapMiniView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/stylesheets/modules/_form.scss
- app/views/connect/index.html.erb
- app/views/shared/_notifications.html.erb
- bower.json
- config/requirejs.yml
This PR adds:
- New router. We save `aoi` and `datasets` in the url 
- ´Datasets helper´ created to manage all thing related to forest change layers
- Bugs/Fixes/Typos
Remember to `bower install`and restart the server because I've added URI.js
> Subscription new

- app/assets/javascripts/countries/views/CountryShowView.js
- app/views/countries/show.html.erb
- Unit change for the y axis of the "Burned forest" graph.
- Unit change for the reforestation text.
> Fix: Country page - Units change

- app/assets/javascripts/map/cartocss/Places2Watch.cartocss
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/templates/legend/places2watch.handlebars
- app/assets/javascripts/map/views/layers/Places2WatchLayer.js
This is a second iteration of this concept there will be a couple more
> added new changes to ptw layer

- app/assets/javascripts/static/ContactUsView.js
Related with https://github.com/Vizzuality/gfw/pull/2627 to remove ES6 features
> Fix: remove ES6 features

- app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
Fixes an issue with a geojson bounds.
Next is to migrate everything to use the geostore bbox.
> Fix: Bounds issue for geojson

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/stylesheets/modules/_form.scss
Show which fields are required to the user
> Feat: Profile - Highlight required fields

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/connect/_user-form.scss
Changed how we display the required fields
> Fix: My gfw - Required fields

- app/assets/javascripts/abstract/layer/CartoDBLayerClass.js
- app/assets/javascripts/helpers/gaEventsHelper.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/views/tabs/AnalysisNewView.js
Adds google analytics events to subscriptions actions
> Feat: Google Analytics - Track subscriptions events

- app/assets/javascripts/map/cartocss/style.cartocss
this must be at production also
> deleted repeated style

- app/assets/javascripts/map/cartocss/style.cartocss
> Layer: Mexico - Payments for Ecosystem Services

- app/assets/stylesheets/layouts/_landing.scss
- app/views/landing/index.html.erb
- Added new carousel slide for user data form
- Added user data form image for carousel
> Release: Home slider changes

- app/assets/javascripts/connect/templates/countrySelection.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/views/LayerSelectionView.js
- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/stylesheets/modules/_form.scss
- Change of the datasets order.
- Change of texts.
> Feature: Subscriptions - Datasets order

- app/assets/javascripts/static/ContactUsView.js
- app/views/static/about.html.erb
- Send the contact-us form to the new API
> Send contact us form to new api

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/javascripts/connect/views/UserFormView.js
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/connect/_user-form.scss
- app/views/shared/_notifications.html.erb
Redirects the user when it has an incomplete profile
> Release: User profile redirection

- app/assets/javascripts/map/cartocss/canPA.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/views/layers/CanProtectedAreasLayer.js
> added can_Pa layer

- app/assets/javascripts/connect/templates/login.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/views/LoginView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/javascripts/models/UserModel.js
Update links for the new login system
> Feat: Users - Login links update

- app/assets/javascripts/connect/templates/login.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/views/LoginView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/views/tabs/SubscribeView.js
Remove callbackUrl parameter, now the API will use the referer param.
> Feat: Login - Remove callbackUrl param

- app/assets/javascripts/connect/router.js
- app/assets/javascripts/connect/views/MapMiniDrawingView.js
- app/assets/javascripts/connect/views/MapMiniUploadView.js
- app/assets/javascripts/connect/views/SubscriptionListView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
Show the upload data button in the subscriptions confirmation box if the user uploaded a dataset only.
> Feature: Subscriptions app - Upload data button

- app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
- app/views/shared/_sources_map.html.erb
- Solves issue with KMZ files and their fit to bound.
- Update of the shapefiles limits and support.
> Release: KMZ Files Bounds and Shape upload text update

- app/assets/javascripts/map/templates/analysis/analysis-download.handlebars
Add download support for GLAD Alerts:
> Feat: Glad - Download links

- app/assets/javascripts/map/presenters/analysis/AnalysisDownloadPresenter.js
Parsing of the download url to include the API URL.
> Feat: Map - Download links parsing

- app/assets/mails/forest-change-notification/forest-change-notification-en.html
- Added download links for the GLAD alerts mails.
> Feat: Mails - Forest change - GLAD alerts download link

- app/assets/javascripts/map/presenters/analysis/AnalysisCountryPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-country.handlebars
- app/assets/javascripts/map/views/analysis/AnalysisCountryView.js
Temp: Disable regions analysis for GLAD and Terra-i
> Feat: Map - Disable region analysis for terra-i and GLAD (temp)

- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
- app/assets/javascripts/map/views/analysis/AnalysisCountryView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
Disable regions in analysis result for GLAD and Terra-i (temp)
> Feat: Analysis result - Disable regions for GLAD and terra-i

- app/assets/javascripts/connect/router.js
- app/assets/javascripts/connect/templates/countrySelection.handlebars
- app/assets/javascripts/connect/templates/layerSelection.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/views/DatasetsListView.js
- app/assets/javascripts/connect/views/LayerSelectionView.js
- app/assets/javascripts/connect/views/MapMiniSelectedView.js
- app/assets/javascripts/connect/views/MapMiniView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/javascripts/map/presenters/analysis/AnalysisDrawPresenter.js
Added more support for URL params, still some work left to do.
> Feat: Subscriptions app - Support for more params in the URL

- app/assets/javascripts/map/presenters/analysis/AnalysisCountryPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-country.handlebars
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
- app/assets/javascripts/map/views/analysis/AnalysisCountryView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
Disables subnational analysis for GLAD and Terra-i Alerts
> Release: Disable subnational analysis

- app/assets/javascripts/connect/templates/listItemDatasetsConfirm.handlebars
- app/assets/javascripts/connect/views/DatasetsListView.js
- app/assets/javascripts/connect/views/ListItemDatasetsConfirmView.js
- app/assets/stylesheets/modules/connect/_subscriptions.scss
Added the Coverage service in the subscriptions list, to show the available datasets depending on the AOI of the subscription.
> Feat: Subscriptions list - Add coverage service

- app/assets/javascripts/map/presenters/LayersCountryPresenter.js
- app/assets/javascripts/map/templates/layersCountry.handlebars
- app/assets/javascripts/map/views/LayersCountryView.js
- app/views/connect/index.html.erb
- Map: Under countries layers, the alerts icon now redirects to the app with the country selected.
- My GFW menu
> Feat: Subscriptions - More links added throughout the app

- app/assets/javascripts/connect/views/SubscriptionNewView.js
Show contribute data button when the user uploads a shape
> Feat: Subscriptions - Show contribute data button for user uploads

- app/assets/javascripts/abstract/layer/CartoDBLayerClass.js
- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/templates/tabs/subscribeDatasets.handlebars
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/stylesheets/modules/_modal_new.scss
- app/assets/stylesheets/modules/common/_subscription-modal.scss
- app/assets/stylesheets/modules/connect/_subscriptions.scss
- app/assets/stylesheets/modules/map/_module-legend.scss
- Added coverage service in the map for subscriptions: this allows users to subscribe to more than one forest change layer at a time, depending on the AOI it will show the available layers.
- Now users can subscribe to an AOI like 'Protected areas' without having any forest change layer turned on:
> Feat: Map - Added coverage service for subscriptions

- app/views/layouts/landing.html.erb
- app/views/shared/_navbar2_landing.html.erb
- Added Optimizely for A/B testing.
- Added a new link under "Get Involve" for the new subscriptions app.
> Feat: Subscriptions A/B Menu link

- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- Added a subscriptions helper to get the list of available layers that allow subscriptions.
- Updated legend to use the same helper to show the link to the subscriptions app.
> Feat: Subscriptions helper and legend links

- app/assets/javascripts/connect/views/DatasetsListView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
Fixes issue with a country selection not updating the available datasets
> Fix: Subscriptions app - Country selection issue

- app/assets/javascripts/connect/views/SubscriptionListView.js
Fixes the redirect issue when unsubscribing from an email alert.
> Feat: Unsubscribe redirect

- app/assets/javascripts/abstract/layer/CartoDBLayerClass.js
- app/assets/javascripts/connect/templates/listItemDatasetsConfirm.handlebars
- app/assets/javascripts/connect/views/DatasetsListView.js
- app/assets/javascripts/connect/views/ListItemDatasetsConfirmView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/javascripts/map/presenters/LayersCountryPresenter.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/templates/layersCountry.handlebars
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/templates/tabs/subscribeDatasets.handlebars
- app/assets/javascripts/map/views/LayersCountryView.js
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/stylesheets/modules/_modal_new.scss
- app/assets/stylesheets/modules/common/_subscription-modal.scss
- app/assets/stylesheets/modules/connect/_subscriptions.scss
- app/assets/stylesheets/modules/map/_module-legend.scss
- app/views/connect/index.html.erb
- app/views/layouts/landing.html.erb
- app/views/shared/_navbar2_landing.html.erb
- Feat: Subscriptions list - Add coverage service
- Feat: Subscriptions - Link in my gfw menu
- Feat: Map - Country layers - Link to subscription
- Feat: Subscriptions - Show contribute data button for user uploads
- Feat: Map - Added coverage service for subscriptions
- Feat: Added Optimizely for A/B testing
- Feat: Menu - Added link for the subscriptions app
- Feat: Analysis - Subscriptions helper
- Feat: Legend - Subscription links
- Fix: Remove console log
- Fix: Subscriptions app - Country selection issue
- Remove unused template
> Release: Map coverage service & subscriptions app improvements

- app/assets/javascripts/connect/views/MapMiniView.js
Resolves issue with previously drawn geojson shapes not getting removed
> Fix: Subscriptions app - Issue with previously drawn geojson shapes

- app/assets/javascripts/map/templates/legend/plantations_by_species.handlebars
- app/assets/javascripts/map/templates/legend/plantations_by_type.handlebars
Fixes the colors for the legend of the layer 'Tree Plantations'
> Fix: Legend - Tree plantation colors

- app/views/shared/_footer_landing.erb
- app/views/shared/_navbar2_landing.html.erb
> Fix: Newsletter link

- app/assets/javascripts/map/templates/legend/plantations_by_species.handlebars
- app/assets/javascripts/map/templates/legend/plantations_by_type.handlebars
- app/views/shared/_footer_landing.erb
- app/views/shared/_navbar2_landing.html.erb
Fix: Legend - Tree plantation colors
Fix: Newsletter link
> Release: Legend for Tree plantations & Newsletter link fix

- app/assets/javascripts/connect/views/LayerSelectionView.js
Added search functionality for the country selector.
> Feat: Subscriptions app - Search functionality for countries selector

- app/assets/javascripts/connect/router.js
- app/assets/javascripts/connect/views/DatasetsListView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/map/templates/legend/legend.handlebars
- Legend link updated for the subscriptions app.
- Datasets selection validation.
> Feat: Subscriptions - Legend link update and datasets validation

- app/assets/javascripts/abstract/layer/OverlayLayerClass.js
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/map/presenters/LegendPresenter.js
- app/assets/javascripts/map/views/LegendView.js
- app/assets/stylesheets/connect.scss
- app/assets/stylesheets/modules/connect/_subscription.scss
- app/assets/stylesheets/modules/map/_module-legend.scss
Added a legend to show the layers information:
> Feat: Subscriptions app - Legend

- app/assets/javascripts/map/cartocss/mangrove_2.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/presenters/LegendPresenter.js
- app/assets/javascripts/map/presenters/layers/Mangrove2LayerPresenter.js
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/mangrove_2.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/Mangrove2Layer.js
- app/assets/stylesheets/modules/map/_onoffswitch.scss
> Feat: Mangrove with filters

- app/assets/javascripts/static/ContactUsView.js
- app/assets/javascripts/static/templates/contactUsNewsletter.handlebars
- app/assets/stylesheets/modules/static/_newsletter.scss
- app/assets/stylesheets/static.scss
- app/views/static/about.html.erb
Show the newsletter form when clicking on the button that shows up with the confirmation.
> Feat: Contact us - Newsletter

- app/assets/javascripts/map/cartocss/mangrove_2.cartocss
- app/assets/javascripts/map/templates/legend/mangrove_2.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/stylesheets/modules/map/_module-legend.scss
- Text updates
- Colors for the selectors
- Removed circle icons
> Feat: Mangrove - Styles for selectors

- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
Temporarily disable GLAD analysis download
> Fix: GLAD - Disable analysis download

- app/assets/javascripts/abstract/layer/OverlayLayerClass.js
- app/assets/javascripts/connect/router.js
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/DatasetsListView.js
- app/assets/javascripts/connect/views/LayerSelectionView.js
- app/assets/javascripts/connect/views/MapMiniView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/map/presenters/LegendPresenter.js
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/stylesheets/connect.scss
- app/assets/stylesheets/modules/connect/_subscription.scss
- app/assets/stylesheets/modules/map/_module-legend.scss
- Fix issue with previously drawn geojsons not getting removed
- Added search functionality for countries selector
- Updated link to the subscriptions app from the map's legend
- Added legend in the map:
> Release: Subscription app features

- app/assets/javascripts/connect/templates/storiesListItem.handlebars
- app/assets/javascripts/stories/models/StoryModel.js
- app/assets/javascripts/stories/routers/StoriesRouter.js
- app/assets/javascripts/stories/templates/storiesNew.handlebars
- app/assets/javascripts/stories/views/StoriesNewView.js
Added support for editing a story
> Feat: Stories - Edit functionality

- app/assets/javascripts/connect/models/Subscription.js
- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/mails/story-alerts-notification/stories-alerts-en.html
Support to allow subscriptions to stories
> Feat: Stories to pubsub

- app/assets/javascripts/helpers/languagesHelper.js
- app/assets/javascripts/static/ContactUsView.js
Now the contact form uses the selected language from transifex.
> Feat: Contact us - Language

- app/assets/javascripts/connect/templates/userForm.handlebars
- app/assets/javascripts/connect/views/UserFormView.js
Fixes the selection of the user's current language, using the languagesHelper.
> Fix: User Profile - Selected language

- app/assets/javascripts/helpers/datasetsHelper.js
Added the metadata information for the User stories subscription
> Feat: Subscriptions - Stories metadata

- app/assets/javascripts/stories/templates/storiesNew.handlebars
Move the email field from the hidden section
> Feat: Stories - Form tweaks

- app/assets/javascripts/stories/views/StoriesNewView.js
Disables the enter key to prevent form submitting
> Feat: Stories - Disable intro key to prevent form submitting

- app/assets/javascripts/stories/routers/StoriesRouter.js
- app/assets/javascripts/stories/templates/storiesNew.handlebars
- app/assets/javascripts/stories/views/StoriesNewView.js
- app/assets/stylesheets/modules/_section-new.scss
Allows the user to preview the section without being logged in:
> Feat: Stories - New story preview without login

- app/assets/javascripts/stories/routers/StoriesRouter.js
Method name fix, it was breaking the compile process.
> Fix: Stories - Method name

- app/assets/javascripts/connect/models/Subscription.js
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/javascripts/map/views/tabs/SubscribeView.js
- app/assets/stylesheets/map.scss
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/common/_tabs.scss
Added webhook support for subscriptions:
- From the map:
- From the subscriptions app:
> Feat: Webhook for subscriptions

- app/assets/javascripts/stories/routers/StoriesRouter.js
Fixes editing a story with login
> Fix: Stories - Editing with login

- app/assets/javascripts/connect/templates/storiesList.handlebars
Added description and a new link to create new stories.
> Feat: My GFW - Stories - Create new story link

- app/assets/javascripts/abstract/layer/AnimatedCanvasLayerClass.js
- app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
Fixes the player functionality for the timeline, reported from this issue #2612.
> Release: Torque player fix

- app/assets/stylesheets/modules/_modal_new.scss
- app/views/shared/_sources_map.html.erb
- Increased width size of the global modal to fit more information
- Added metatada for UrtheCast Sentinel 2 sensor:
> Feature: UrtheCast metadata for Sentinel 2 sensor

- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/presenters/LegendPresenter.js
- app/assets/javascripts/map/presenters/layers/Mangrove2LayerPresenter.js
- app/assets/javascripts/map/services/MangroveDateService.js
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/mangrove_2.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/Mangrove2Layer.js
- app/assets/javascripts/map/views/timeline/MangroveTimeline.js
> Feat: Layer - Mangrove timeline

- app/views/shared/_sources_map.html.erb
Added missing metadata for Sentinel 2
> Feat: UrtheCast - Sentinel-2A Metadata

- app/assets/javascripts/map/cartocss/Lbr_community.cartocss
- app/assets/javascripts/map/cartocss/lbr_forest.cartocss
- app/assets/javascripts/map/cartocss/lbr_mining.cartocss
- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/templates/legend/lbr_community.handlebars
- app/assets/javascripts/map/templates/legend/lbr_forest.handlebars
- app/assets/javascripts/map/templates/legend/lbr_mining.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/LbrDevExL.js
- app/assets/javascripts/map/views/layers/LbrLoggingLayer.js
- app/assets/javascripts/map/views/layers/LbrMinDevAg.js
- app/assets/javascripts/map/views/layers/LbrMinExL.js
- app/assets/javascripts/map/views/layers/LbrOilPalmLayer.js
- app/assets/javascripts/map/views/layers/LbrPrivUseP.js
- app/assets/javascripts/map/views/layers/LbrResourceRightsLayer.js
> Release: Liberia layers

- app/assets/javascripts/map/templates/legend/mangrove_2.handlebars
> Fix: Mangrove Change - Legend

- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
From BC: https://basecamp.com/3063126/projects/10727890/todos/289486887
> Don't show the form at all if user not logged in

- app/assets/javascripts/map/views/layers/UrthecastLayer.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- app/assets/stylesheets/modules/_modal_new.scss
- app/views/shared/_sources_map.html.erb
- Added new sensor Sentinel 2 for UrtheCast imagery.
- Added metadata for this sensor.
> Release: UrtheCast - New Sentinel 2 sensor

- app/assets/javascripts/stories/models/StoryModel.js
> Fix: Stories List - Link to story

- Gemfile.lock
- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/views/layers/CanLoggingLayer.js
- app/assets/javascripts/map/views/layers/PakUserMangrovesLayer.js
There was aggregated a layer: PakUserMangrovesLayer 
And was updated CanLoggingLayer.
Note that Pakistan Mangroves is a very tiny layer. If you want to see it to review it, zoom in on the coastal area of Pakistan.
> Layer updated (Canada forest tenures) and new layer (User data - Pakistan mangroves) 

- app/assets/javascripts/map/services/MapLayerService.js
- app/assets/javascripts/map/templates/layersCountry.handlebars
- app/assets/javascripts/map/views/LayersCountryView.js
- app/assets/stylesheets/modules/map/_layer-nav.scss
- app/assets/stylesheets/modules/map/_module-tabs.scss
> Feat: Layer nav - User tab

- app/assets/javascripts/map/cartocss/BolUserFireFreq.cartocss
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/templates/legend/bol_user_fire_frequency.handlebars
- app/assets/javascripts/map/views/layers/CanLoggingLayer.js
- app/assets/javascripts/map/views/layers/EcuUserProtectedAreasLayer.js
- app/assets/javascripts/map/views/layers/SenUserProtectedAreasLayer.js
There were fixed some observations (handlerbars, legends, ...) about the new layers of Bolivia, Ecuador and Senegal.
> Were fixed the observations about the new layers

- app/assets/javascripts/static/ContributeDataView.js
> Feat: Contribution data - new endpoint

- app/assets/javascripts/helpers/languagesHelper.js
- app/assets/javascripts/static.js
- app/assets/javascripts/static/ContactUsView.js
- app/assets/javascripts/static/ContributeDataView.js
- app/assets/javascripts/static/templates/contactUsNewsletter.handlebars
- app/assets/stylesheets/modules/_steps.scss
- app/assets/stylesheets/modules/static/_newsletter.scss
- app/assets/stylesheets/static.scss
- app/views/shared/_navbar2_landing.html.erb
- app/views/sitemap/index.html.erb
- app/views/static/about.html.erb
- Added contact form in the about page:
- Changed contribute data endpoint
> Release: Contact us form

- app/assets/javascripts/connect/templates/subscriptionDatasetsList.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/LayerSelectionView.js
My last commit it's because this small change was going to make conflict with the changes of this branch, so I merged the changes so we could check them better.
> Remove asterisks in all labels from the subscription form

- app/assets/javascripts/map/presenters/LegendPresenter.js
- app/assets/javascripts/map/views/layers/Forma2016Layer.js
Update tile and decoding function.
> Feat: Forma 2016 - Tile update

- app/assets/javascripts/map/templates/tabs/countriesMobile.handlebars
- app/assets/javascripts/map/views/tabs/CountriesView.js
- app/assets/stylesheets/modules/map/_module-tabs.scss
Added feature for mobile devices
> Feat: User data - mobile tabs

- app/assets/javascripts/map/cartocss/Places2Watch.cartocss
- app/assets/javascripts/map/views/layers/Places2WatchLayer.js
Data update for 'Places to watch' layer
> Feat: Map - Places to watch - Data update

- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/map/templates/tabs/subscribe.handlebars
- app/assets/stylesheets/modules/_form.scss
- app/assets/stylesheets/modules/_modal_new.scss
- app/assets/stylesheets/modules/common/_tabs.scss
- app/views/shared/_sources_map.html.erb
Metadata and preview for subscriptiosn webhooks
> Feat: Webhook - Metadata and preview

- app/views/shared/_sources_map.html.erb
Change text to "This layer displays the geographic coverage of GLAD alerts"
> Update: text for glad coverage modal

- README.md
Fix ImageMagick version to avoid conflicts with `rmagick`
> Update readme to fix the version of imagemagick

- app/assets/javascripts/map/presenters/analysis/AnalysisDrawPresenter.js
- app/assets/javascripts/map/services/ShapefileNewService.js
- app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
- app/assets/javascripts/presenters/NotificationsPresenter.js
- app/assets/javascripts/views/NotificationsView.js
- app/views/shared/_notifications.html.erb
- app/views/shared/_sources_map.html.erb
Additional notifications for failed uploads to ogr microservice:
- If layer contains more than 1000 features prevent turf reduction and exit
- If file is corrupt
- If file file contains multiple layers (not supported by OGR) exit.
> Feature: fixes for upload shape

- app/assets/javascripts/connect/templates/subscriptionDatasetsList.handlebars
- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
- app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
- app/assets/javascripts/connect/views/LayerSelectionView.js
- app/assets/stylesheets/layouts/_landing.scss
- app/views/landing/index.html.erb
- Home: New image and text to promote GLAD.
- Subscriptions:
- Don't show the form at all if user not logged in
- Improve subscriptions 'How it works' text
- Remove asterisks in all labels from the subscription form
- Labels changes
> Release: Home images and subscriptions tweaks

- app/assets/javascripts/map/templates/analysis/analysis-draw.handlebars
- app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
- app/assets/stylesheets/modules/map/_analysis-draw.scss
Added loader when uploading shapes.
> Feat: Upload data - Loader

- app/views/small_grants_fund/index.html.erb
As requested on this Basecamp Thread: https://basecamp.com/3063126/projects/10728552/todos/297212702#comment_505776771
Goal is to deploy to production alongside changes to the How To Portal (https://github.com/Vizzuality/gfw-howto/pull/41) , today in DC's early afternoon.
> Makes updates requested by Jessica for the small grants fund 2017

- app/views/small_grants_fund/index.html.erb
Updates for Small grants fund 2017
> Release: Small grants fund 2017

- app/assets/stylesheets/layouts/_landing.scss
- app/views/landing/index.html.erb
> Release: Small Grants Fund

- app/assets/javascripts/static-pages/views/SmallGrantsFundView.js
> Fix: Small Grants - Disable slider

- app/assets/javascripts/static-pages/views/SmallGrantsFundView.js
> Release: Small Grants - Disable slider

- app/assets/javascripts/abstract/timeline/TimelineYearClass.js
- app/assets/javascripts/map/views/layers/LossLayer.js
Don't merge until this 2 issues are solved:
> update hansen loss layer to 2015 data

- app/assets/javascripts/map/cartocss/Places2Watch.cartocss
- app/assets/javascripts/map/views/layers/Places2WatchLayer.js
Added Places to Watch styles. Info window in process.
> Feat: PTW - Layer styles

- app/views/shared/_sources_map.html.erb
Update text for glad coverage modal
> Release: Update text for glad coverage modal

- app/assets/javascripts/map/views/layers/Forma2016Layer.js
> Forma: Added 3month tiles

- app/assets/javascripts/map/views/layers/Forma2016Layer.js
> Fix: FORMA tile url

- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
Enable glad downloads on production
> Release: Enable Glad downloads

- app/assets/javascripts/map/presenters/analysis/AnalysisDownloadPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-download.handlebars
Enable download of points for GLAD
> Release: Download links for GLAD

- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
> Map - Subscription - Fix error callback

- app/assets/javascripts/abstract/timeline/TimelineBtnClass.js
- app/assets/javascripts/abstract/timeline/TimelineMonthClass.js
- app/assets/javascripts/abstract/timeline/TimelineYearClass.js
- app/assets/javascripts/map/presenters/ExperimentsPresenter.js
- app/assets/javascripts/map/presenters/TabsPresenter.js
- app/assets/javascripts/map/views/LayersNavView.js
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/MapView.js
- app/assets/javascripts/map/views/TabsView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsView.js
- app/assets/javascripts/map/views/controls/SearchboxView.js
- app/assets/javascripts/map/views/tabs/AnalysisNewView.js
- app/assets/javascripts/map/views/tabs/AnalysisView.js
- app/assets/javascripts/map/views/tabs/CountriesView.js
Added missing import for the `enquire` library
> Fix: Missing import for the equire library

- app/assets/javascripts/abstract/timeline/TimelineBtnClass.js
- app/assets/javascripts/abstract/timeline/TimelineMonthClass.js
- app/assets/javascripts/abstract/timeline/TimelineYearClass.js
- app/assets/javascripts/map/presenters/ExperimentsPresenter.js
- app/assets/javascripts/map/presenters/TabsPresenter.js
- app/assets/javascripts/map/presenters/tabs/SubscribePresenter.js
- app/assets/javascripts/map/views/LayersNavView.js
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/MapView.js
- app/assets/javascripts/map/views/TabsView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsView.js
- app/assets/javascripts/map/views/controls/SearchboxView.js
- app/assets/javascripts/map/views/tabs/AnalysisNewView.js
- app/assets/javascripts/map/views/tabs/AnalysisView.js
- app/assets/javascripts/map/views/tabs/CountriesView.js
- Fix the `enquire` library imports
- Fix wrong use of the error callback
> Release: Fix enquire imports and wrong callback use

- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
I made two minor edits to the text about UrtheCast in the high-res imagery tab.
> Small text edits to UrtheCast message

- app/assets/javascripts/map/views/layers/LossLayer.js
> Update Loss layer tiles

- app/assets/javascripts/countries/models/CountryShowModel.js
- app/assets/javascripts/countries/views/CountryHeaderView.js
- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/javascripts/services/CountryService.js
> Feat: Countries page upgrade

- app/views/countries/_header.html.erb
- app/views/embed/_country.html.erb
> Countries: Update last date update label

- app/assets/javascripts/countries/views/CountryHeaderView.js
> Fix: Cover gain value

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/UMDCoverLayer.js
- app/assets/stylesheets/modules/map/_module-legend.scss
- app/views/shared/_sources_map.html.erb
Added the temp 2015 coverage layer
> Feat: UMD 2015 Coverage

- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/LossLayer.js
- app/assets/stylesheets/modules/map/_module-legend.scss
- Updates the Loss layer tiles with 2015 data
- Legend tweak for the coverage layer
> Feat: 2015 loss tile update and legend for coverage

- .gitignore
- app/assets/mails/forest-change-notification/forest-change-notification-en.html
- app/assets/mails/forest-change-notification/forest-change-notification-es_MX.html
- app/assets/mails/forest-change-notification/forest-change-notification-fr.html
- app/assets/mails/forest-change-notification/forest-change-notification-id.html
- app/assets/mails/forest-change-notification/forest-change-notification-pt_BR.html
- app/assets/mails/forest-change-notification/forest-change-notification-zh.html
Include last 10 alerts in forest change templates.
> Add forest change last 10 alerts

- app/views/countries/_header.html.erb
- app/views/countries/overview.html.erb
Updates the current excel with the 2015 data
> Feat: Countries - Update excel file with loss data

- app/views/countries/_header.html.erb
- app/views/countries/overview.html.erb
Updates the excel file with the 2015 data
> Release: Countries - Update excel file with loss data

- app/assets/javascripts/map/templates/maptype.handlebars
- app/assets/javascripts/map/templates/tabs/basemaps.handlebars
- app/assets/javascripts/map/views/MapView.js
- app/assets/javascripts/map/views/maptypes/landsatMaptype.js
> Feat: Landsat 2015

- app/assets/javascripts/landing/views/UseExamplesView.js
- app/assets/stylesheets/components/home/_c-home-use-examples.scss
- app/controllers/landing_controller.rb
- app/views/landing/_use_examples.html.erb
> Feat: Home - Added credits to pictures

- app/assets/javascripts/countries/views/CountryOverviewView.js
Don't request the data for the year 2015 in the country overview page.
> Don't request data from overview in  2015 year

- app/assets/javascripts/countries/views/CountryOverviewView.js
Removed 2015 data from the countries rankings
> Release: Removed 2015 data from countries rankings

- app/views/shared/navigate/_default_navigate.html.erb
Fixes the link for 'Provide Feedback' in the menu
> Fix: Menu - Feedback link

- app/assets/javascripts/connect/views/StoriesListItemView.js
- app/assets/javascripts/connect/views/StoriesListView.js
- app/assets/javascripts/connect/views/SubscriptionListItemView.js
- app/assets/javascripts/connect/views/SubscriptionListView.js
- app/assets/javascripts/connect/views/SubscriptionNewView.js
- app/assets/javascripts/connect/views/UserFormView.js
- app/assets/javascripts/models/UserModel.js
- app/views/shared/_notifications.html.erb
- app/views/shared/navigate/_default_navigate.html.erb
- Now every request that requires a logged user will check the session before making any requests.
- It also fixes the feedback menu in the home page
> Release: My GFW - Check auth

- app/assets/javascripts/abstract/timeline/TorqueTimelineSlider.js
- app/assets/javascripts/map/presenters/layers/FormaMonth3LayerPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/services/AnalysisNewService.js
- app/assets/javascripts/map/services/FormaDateService.js
- app/assets/javascripts/map/services/FormaService.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
- app/assets/javascripts/map/views/layers/Forma250CoverLayer.js
- app/assets/javascripts/map/views/layers/FormaMonth3Layer.js
- app/assets/javascripts/map/views/timeline/FormaTimeline.js
- Added dynamic tiles
- Added timeline like GLAD
- Added first part of the analysis (test wip)
> Feat: FORMA

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/views/layers/CanMiningLayer.js
This PR addresses the Basecamp assigned issue to Update Canada mineral tenures data.
> Feat: Update Canadian mining layer

- app/assets/javascripts/connect/templates/subscriptionList.handlebars
changed text at top of my subscriptions page
> intro to my subscriptions page

- app/assets/javascripts/connect/templates/subscriptionNew.handlebars
Change "forest loss alerts" to "deforestation alerts"
> change language to "deforestation alerts"

- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/services/AnalysisNewService.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
> Feat: Forma 250 analysis

- app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
- app/assets/javascripts/map/services/FormaDateService.js
- app/assets/javascripts/map/views/layers/FormaMonth3Layer.js
- app/assets/stylesheets/modules/map/_timeline-torque.scss
- Correct FORMA available dates
- Timezone issues
- Layout issue
> Fix: Forma 250 timeline

- app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
- app/assets/javascripts/map/cartocss/FormaActivity.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/services/LayerSpecService.js
- app/assets/javascripts/map/services/MapLayerService.js
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/forma_month.handlebars
- app/assets/javascripts/map/views/LayersNavView.js
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/FormaActivityLayer.js
- app/assets/stylesheets/modules/map/_layer-nav.scss
- Support for sublayers
- New FORMA activity alerts layer
- Fixed timeline and dates
- Fixed issue with the high res imagery
> Feat: FORMA - Activity alerts layer

- app/assets/javascripts/map/templates/layersNav.handlebars
Update the layer's name in the navigation bar
> Feat: Forma - Update name

- app/assets/javascripts/map/views/LayersNavView.js
Fixes an issue with the sublayers functionality and the filters
> Fix: Sublayer toggle

- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/layers/SentinelLayer.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
First implementation of the info window and some endpoint changes
> Feat: Sentinel improvements

- app/assets/javascripts/map/services/FormaDateService.js
- app/assets/javascripts/map/services/FormaService.js
Added endpoint to get the actual dates with data
> Feat: FORMA - Dates endpoint

- app/views/shared/_sources_map.html.erb
Added new metadata information
> Feat: Senitnel hub - metadata

- app/assets/javascripts/connect/models/Subscription.js
- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/mails/story-alerts-notification/stories-alerts-en.html
- app/assets/mails/story-alerts-notification/stories-alerts-es.html
- app/assets/mails/story-alerts-notification/stories-alerts-fr.html
- app/assets/mails/story-alerts-notification/stories-alerts-id.html
- app/assets/mails/story-alerts-notification/stories-alerts-pt.html
- app/assets/mails/story-alerts-notification/stories-alerts-zh.html
Enables users to subscribe to stories.
> Release: Stories in Subscriptions

- app/assets/javascripts/map/templates/tabs.handlebars
- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- app/views/shared/_sources_map.html.erb
- Meta data information changes
- Change "hi-res imagery" to "recent satellite imagery"  and show current zoom
- Fix typo in the renders selector
> Feat: Sentinel hubs changes

- app/assets/javascripts/map/views/tabs/HighresolutionView.js
> Feat: Sentinel hub - min date

- app/assets/javascripts/map/services/FormaService.js
> Feat: FORMA - Update tile endpoint

- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/javascripts/map/helpers/timelineDatesHelper.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/views/timeline/FiresTimeline.js
- app/assets/javascripts/map/views/timeline/FormaActivityTimeline.js
- app/assets/javascripts/map/views/timeline/MangroveTimeline.js
Added new analysis enpoint for the layer `FORMA active clearing alerts`
> Feat: Forma activity analysis

- app/assets/stylesheets/components/home/_c-home-cover.scss
- app/views/landing/_cover.html.erb
> change close video button

- app/assets/javascripts/map/presenters/TerraILayerPresenter.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
- app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
> Fix: Layers - GLAD, Terra I, FORMA

- app/assets/mails/forest-change-notification/forest-change-notification-en.html
- app/assets/mails/forest-change-notification/forest-change-notification-es_MX.html
- app/assets/mails/forest-change-notification/forest-change-notification-fr.html
- app/assets/mails/forest-change-notification/forest-change-notification-id.html
- app/assets/mails/forest-change-notification/forest-change-notification-pt_BR.html
- app/assets/mails/forest-change-notification/forest-change-notification-zh.html
- Change all languages templates.
- Update emails templates on **_SparkPost_**
> Change content on email templates

- app/assets/javascripts/map/cartocss/FormaActivity.cartocss
- app/assets/javascripts/map/views/layers/FormaActivityLayer.js
- New Styles on **FORMA Active clearing alerts.**
- Enabled info window.
> Add new styles on forma-active-layer

- app/assets/javascripts/connect/templates/regionSelection.handlebars
- app/assets/javascripts/countries/templates/countryHeader.handlebars
- app/assets/javascripts/countries/views/CountryHeaderView.js
- Include functions to show regions on header.
> Add regions on selector

- app/assets/javascripts/map/presenters/GladLayerPresenter.js
- app/assets/javascripts/map/presenters/TerraiCanvasLayerPresenter.js
- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
- app/assets/stylesheets/global/_texts.scss
- app/assets/stylesheets/map.scss
- app/views/shared/_notifications.html.erb
Added GLAD updates notification:
> Release: GLAD updates notification

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/views/layers/HaitiWatershedLayer.js
New user data for Haiti watershed areas
> Release: User data for Haiti watershed areas

- app/assets/javascripts/map/cartocss/Places2Watch.cartocss
- Change zoom styles for place to watch layer icons
> Change styles for place to watch layer

- app/assets/javascripts/map/views/layers/LossLayer.js
Tree cover loss layer endpoint update with all 2015 data
> Feat: Update Tree cover loss layer endpoint with all 2015 data

- app/assets/javascripts/helpers/datasetsHelper.js
- app/assets/stylesheets/components/home/_c-home-cover.scss
- app/views/landing/_cover.html.erb
> Improve Home page video button styles

- app/assets/stylesheets/components/home/_c-home-cover.scss
- app/views/landing/_cover.html.erb
Added button to stop loading the video for users who pre-paid data packages.
> Release: Home page - Video stop button

- app/assets/javascripts/connect.js
- app/assets/javascripts/helpers/datasetsHelper.js
Updated the Datasets helper to include the analysis IDs
> Feat: Datasets helper - added if for analysis

- app/assets/javascripts/map/views/layers/SentinelLayer.js
Added missing parameter to show the most recent images `&PRIORITY=mostRecent`
> Feat: Sentinel - fix dates

- app/views/shared/_sources_map.html.erb
Updated the metadata for this layer
> Feat: Sentinel - updated meta data

- app/assets/stylesheets/components/home/_c-home-cover.scss
Fixes a cross browser issue with Safari
> Release: Home - Cross browser issue

- app/assets/javascripts/map/services/GladDateService.js
- app/assets/javascripts/map/services/TerraiDateService.js
Get dates with available data for GLAD and Terra-i from the API.
> Feat: GLAD / Terra-i - Dates from elastic

- app/assets/javascripts/common/views/GroupedGraphView.js
- app/assets/javascripts/countries/templates/widgets/annualTreeCoverLoss.handlebars
- app/assets/javascripts/countries/views/CountryHeaderView_old.js
- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- app/assets/stylesheets/modules/countries/_show.scss
- app/assets/stylesheets/modules/countries/widgets/_annual-tree-cover-loss.scss
- Add min and max date.
- Add all dates on the selector.
> Add features to Tree cover loss widget.

- app/assets/javascripts/map/helpers/guidetexts.js
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/presenters/tabs/HighresolutionPresenter.js
- app/assets/javascripts/map/templates/legend/sentinel.handlebars
- app/assets/javascripts/map/templates/tabs.handlebars
- app/assets/javascripts/map/templates/tabs/highresolution.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/SentinelLayer.js
- app/assets/javascripts/map/views/tabs/HighresolutionView.js
- app/assets/stylesheets/modules/map/_tab-highresolution.scss
- app/views/shared/_js_config.html.erb
- app/views/shared/_map.html.erb
- app/views/shared/_notifications.html.erb
- app/views/shared/_sources_map.html.erb
New high res imagery by Sentinel Hub:
> Release: Sentinel hub imagery

- app/assets/javascripts/map/cartocss/FormaActivity.cartocss
> Change styles on forma active layer.

- app/assets/javascripts/countries/templates/widgets/treeCoverLossAlerts.handlebars
- app/assets/javascripts/countries/templates/widgets/treeCoverLossAlertsCard.handlebars
- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/javascripts/countries/views/widgets/TreeCoverLossAlertsView.js
- app/assets/javascripts/services/CountryService.js
- app/assets/stylesheets/modules/countries/_show.scss
- Active check data source filter.
> Include new features to tree cover loss alerts widget.

- app/assets/javascripts/map/cartocss/FormaActivity.cartocss
- Change zoom level styles.
- Change com-op properties.
- Change color legends.
> Forma Active layer on map.

- app/assets/javascripts/map/services/GladDateService.js
Changed the dataset id to the staging one for testing.
> Temp: GLAD dataset staging dataset for the timeline

- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/services/GladDateService.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
The new microservices will use the old endpoints so we are changing them back.
> Restore old GLAD / Terra-i analysis endpoints

- app/assets/mails/fires-notification/fires-notification-es_MX.html
- app/assets/mails/fires-notification/fires-notification-fr.html
- app/assets/mails/fires-notification/fires-notification-id.html
- app/assets/mails/fires-notification/fires-notification-zh.html
- app/assets/mails/forest-change-notification/forest-change-notification-en.html
- app/assets/mails/forest-change-notification/forest-change-notification-es_MX.html
- app/assets/mails/forest-change-notification/forest-change-notification-fr.html
- app/assets/mails/forest-change-notification/forest-change-notification-id.html
- app/assets/mails/forest-change-notification/forest-change-notification-pt_BR.html
- app/assets/mails/forest-change-notification/forest-change-notification-zh.html
Updates for the notifications templates
> Release: Notifications emails updates

- app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
- app/assets/javascripts/map/presenters/TerraILayerPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/services/GladDateService.js
- app/assets/javascripts/map/services/TerraiDateService.js
- app/assets/javascripts/map/templates/analysis/analysis-country.handlebars
- app/assets/javascripts/map/views/analysis/AnalysisCountryView.js
- app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
- app/assets/javascripts/map/views/layers/TerraiCanvasLayer.js
Changed GLAD and Terra-i date services to use elastic search to pull the years with data available
> Release: GLAD / Terra-i - Timeline dates from elastic

- app/assets/javascripts/map/services/GladDateService.js
> Fix glad datepicker layer

- app/assets/javascripts/countries/templates/countryHeader.handlebars
- app/assets/javascripts/countries/templates/widgets/annualTreeCoverLoss.handlebars
- app/assets/javascripts/countries/views/CountryHeaderView.js
- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- app/assets/javascripts/countries/views/widgets/MapCountry.js
- app/assets/javascripts/countries/views/widgets/TreeCoverLossAlertsView.js
- app/assets/javascripts/countries/views/widgets/TreeCoverView.js
- app/assets/javascripts/services/CountryService.js
- app/assets/stylesheets/modules/countries/widgets/_annual-tree-cover-loss.scss
- Select first option change to "Whole Country" when the user changes the region. And when choose "Whole country" then change to "Select a jurisdiction".
- Fix errors when selecting another region, now the different layers appear.
- Improve map functions.
- Now the map update with animations and not re-create another new map for different region or country.
> Improve and fix countries page map and other features.

- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- Change values when the region is different.
> Improve annual tree cover loss widget.

- app/assets/javascripts/countries/helpers/AreasCountries.js
- app/assets/javascripts/countries/templates/widgets/annualTreeCoverLoss.handlebars
- app/assets/javascripts/countries/templates/widgets/treeCoverLoss.handlebars
- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- app/assets/javascripts/countries/views/widgets/TreeCoverLossView.js
- app/assets/stylesheets/modules/countries/widgets/_annual-tree-cover-loss.scss
> Improve areas countries functions and include on widgets
