app/controllers/application_controller.rb
app/views/shared/_js_footer.html.erb
lib/user_agent_validator.rb
spec/controllers/application_controller_spec.rb

The sharing snippets for FB and G+ were not getting passed the supported browser check (the bot check in the user agent gem is just a regex match for "bot" :dizzy_face:) and the terms check, so I extracted that out and added some special cases for Facebook and g+. It's easy to add in more exemptions if we need to, for whatever reason. 
This seems like a big change, but I've just moved the user agent validation out in to a separate class as it's a separate responsibility from the app controller, and to make it testable.

Fix sharing snippets

---

app/assets/javascripts/map/templates/mapcontrols.handlebars
app/assets/javascripts/map/views/MapControlsView.js
app/assets/javascripts/views/ShareView.js
app/views/countries/_header.html.erb

Default to using /embed/<rest of URL> as that's what all the embeds use anyway.

Fix embed URLs

---

app/views/shared/_sources_map.html.erb

there is only one link left miguel, the one on the image (quicc one)

hotfixed: change url quicc to data portal link

---

app/views/shared/_sources_map.html.erb

the Peru layer is not part of the global managed forests layer

removed Peru from list of managed forests

---

app/views/static/howto.html.erb

On FAQ "What Kinds of Data Are Available on GFW?" page.

Changed link for Data Playbook to Amazon S3.

---

app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
app/assets/javascripts/map/presenters/tabs/SubscriptionPresenter.js
app/assets/javascripts/map/services/AnalysisService.js

This PR updates `prodes-alerts` endpoints to hit `prodes-loss`.
API changes are deployed to staging:
http://staging.gfw-apis.appspot.com/forest-change/prodes-loss

Update prodes endpoints for API

---

app/assets/javascripts/abstract/layer/OverlayLayerClass.js
app/assets/javascripts/abstract/layer/TorqueLayerClass.js
app/assets/javascripts/abstract/timeline/TorqueTimelineClass.js
app/assets/javascripts/abstract/timeline/TorqueTimelineSlider.js
app/assets/javascripts/map/cartocss/default_torque_style.cartocss
app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/presenters/TorqueLayerPresenter.js
app/assets/javascripts/map/presenters/TorqueTimelinePresenter.js
app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/views/layers/LandsatAlertsTorqueLayer.js
app/assets/javascripts/map/views/timeline/LandsatAlertsTorqueTimeline.js
app/assets/javascripts/templates/timelineTorque-controls.handlebars
app/assets/javascripts/templates/timelineTorque.handlebars
app/assets/stylesheets/map.scss
app/assets/stylesheets/modules/map/_timeline-torque.scss
app/views/layouts/map.html.erb

This PR introduces a Torque layer (with a matching Timeline). The timeline only roughly fits the design, this PR is mostly just to get the Torque layer reviewed early on. Since this is potentially going to replace other animated layers, it'd be nice if you could give the Torque timeline classes a thorough code review.
I've added a new layer to the spec for testing, which you can try out locally here: http://localhost:5000/map/3/0.54/20.80/ALL/grayscale/gfw_landsat_torque_alerts You'll have to reset your localStorage first, of course. The date shows as 1970 as the test table doesn't have real dates right now :(
Next up, date pickers!

Torque layer

---

app/views/shared/_sources.html.erb

Link is broken since this data is not currently on the ODP (because the 2014 data download is not ready). Linking instead to the Google Earth Engine

Update link in loss info window

---

app/assets/javascripts/map/cartocss/Forma250Layer.cartocss
app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/presenters/MapPresenter.js
app/assets/javascripts/map/services/MapLayerService.js
app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/views/layers/Forma250Layer.js
app/assets/javascripts/map/views/timeline/Forma250Timeline.js

Adds a layer to test out the forma 250 data (for Peru). Mostly a standard layer addition, but also introduces a method to fit the map to the geometry bounds in the layerspec when selecting the layer from the menu.
@apercas This adds a new column to the layerspec: `fit_to_geom` that the MapPresenter uses to decide whether or not to try and fit to the geometry bounds. Does the staging server use `layerspec_nuclear_hazard`?
Test it out: http://localhost:5000/map/10/-5.75/-77.20/ALL/grayscale/forma_250?begin=2015-03-22&end=2015-11-16

Adds FORMA 250 torque layer

---

app/views/static/howto.html.erb

Removed Fires and Commodities buttons from "ANALYZE A USER-DEFINED AREA" and "ANALYZE A COUNTRY OR SUBNATIONAL JURISDICTION".

Removed Fires and Commodities from How To

---

app/views/static/getinvolved.html.erb

The date was wrong in an FAQ - should be December 31, 2016

Change year in FAQ from 2015 to 2016

---

app/views/shared/_notifications.html.erb

Fixed typo in error message text when user enters non-standard coordinates.

Updated text for non-standard coordinates

---

app/views/static/about.html.erb

Changed "World Resorces Institute" to correct spelling.

Fixed typo in spelling of WRI

---

app/assets/javascripts/abstract/timeline/TorqueTimelineDatePicker.js

* Prevents timezone adjusting code from constantly increasing the
selected time until it overruns to the following day
* Account for daylight savings

Fixes timezone issues

---

app/assets/javascripts/map/services/CartoDbLayerDateService.js
app/assets/javascripts/map/services/TorqueDateService.js

It seems that some of the issues related to GLAD dates were due to the cache. In particular, the dates would be cached for 24 hours, which meant that you might not necessarily see new data, depending on when you last viewed the layer.

Cache until the end of the day, rather than 24 hours later

---

app/assets/javascripts/map/views/layers/CustomInfowindow.js

If you close the infowindow by clicking the "X" icon, mousewheel map option will be enabled again

Map: fixing mousewheel behaviour in custom infowindows

---

app/assets/javascripts/connect/views/SubscriptionListView.js
app/views/shared/_notifications.html.erb

A little bit of code to redirect back to the API from subscription migrations. This allows us to use the existing log-in UI for users who have not visited before (which is likely for migrations).

Subscription migration support

---

app/controllers/countries_controller.rb
app/views/countries/show.html.erb

We need to add the column in the sql in the GFW API and deploy the API to pro. The name of the column is 'policy_links'. Hey Adam, could you do it?
https://github.com/Vizzuality/gfw-api/blob/master/gfw/countries/countries.py#L50

Country: policy links enabled

---

app/mailers/mobile_download.rb
app/mailers/your_mailer.rb
config/application.rb

Mandrill is merging in to the MailChimp plan, which makes things a little more complicated regarding payment, so we're switching to SparkPost.

Move away from Mandrill

---

app/assets/javascripts/map/models/UserModel.js
app/assets/javascripts/map/views/tabs/SubscribeView.js
jstest/spec/SubscribeView_spec.js
jstest/spec/UserModel_spec.js

If a user does not already have an email on their profile, use the email input in to a subscription instead.

Save subscription email to user's profile

---

app/assets/javascripts/map/views/tabs/CountriesView.js

Sharing link didn't save activated data layers correctly.
The "share" link for the map when GLAD Alerts and Indonesia forest moratorium data was turned on opened tree plantations and forgot the dates selected for GLAD Alerts. Now, it doesn't do that

Map: country layers do not select automatically any layer

---

app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
app/assets/javascripts/map/services/PlaceService.js
app/assets/javascripts/map/views/tabs/SubscribeView.js

* always store geostore IDs, if they are available, so they can be processed by the API
* adds a fit_to_geom URL parameter, so links in emails will always fit the map bounds to the alert geometry

A couple of fixes for subscription alerts

---

app/assets/javascripts/abstract/timeline/TimelineBtnClass.js
app/assets/javascripts/map/helpers/FiresDatesHelper.js
app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
app/assets/javascripts/map/views/layers/FiresLayer.js
app/assets/javascripts/map/views/layers/ViirsLayer.js
app/assets/javascripts/map/views/timeline/FiresTimeline.js
jstest/spec/AnalysisPresenter_spec.js
jstest/spec/AnalysisResultsPresenter_spec.js

Previously the VIIRS layer would break if you visit URLs with begin/end dates in the past...no more! I also wrote some pretty comprehensive tests for the `_buildResource` method for Analyses so that I could tear it apart and refactor it :+1: 
Example:
This doesn't work (the layer shows alerts but the analysis says 0):
http://staging.globalforestwatch.org/map/9/8.90/-11.39/ALL/grayscale/viirs_fires_alerts?tab=analysis-tab&fit_to_geom=true&geojson=%257B%2522type%2522%253A%2522Polygon%2522%252C%2522coordinates%2522%253A%255B%255B%255B-12.1619%252C9.1618%255D%252C%255B-11.1292%252C9.6224%255D%252C%255B-10.8929%252C9.4328%255D%252C%255B-10.7831%252C9.0587%255D%252C%255B-10.6128%252C8.6625%255D%252C%255B-10.7831%252C8.255%255D%252C%255B-11.3818%252C8.1734%255D%252C%255B-11.662%252C8.6733%255D%25 …

Fix VIIRS layer for subscriptions

---

app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js

Hey @adammulligan, there is an issue related to this url: [glad](http://www.globalforestwatch.org/glad)
What I've found is that the 'Place/go' event happens after the 'TorqueLayer' has set the dates. So, it tries to get the dates from the url but at this moment they are equal to null. My solution is to check if the status.date exists before changing it. I really don't like it and it may cause some issues with other layers.
Let me know if you find a better solution

Map: check if date is already set

---

app/views/shared/_gfw_assets.html.erb

@adammulligan @aagm @apercas @davidsingal @d4weed Please set this var in your .env file `GFW_ASSETS_URL=http://gfw-assets.s3.amazonaws.com/static/gfw-assets.nightly.js`. Since now we will always have the nightly version on local develop and staging. And the http://gfw-assets.s3.amazonaws.com/static/gfw-assets.latest.js` version should be the one set at production. 
Her we have a little documentation of how to use the gfw-assets: https://docs.google.com/a/vizzuality.com/document/d/1m_v-L7WVmDlBhd5eGhnpmHPTmaQ8c7gVvwUTaJweVv4/edit?usp=sharing

Version removed. Nightly version is the correct one for develop

---

app/views/shared/_js_footer.html.erb

We are now going to use the document.location.hostname as they recommend on the documentation for the cookieDomain param. https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#configuring_cookie_field_settings

Analytics cookie domain

---

app/assets/javascripts/helpers/interestingHelper.js
app/assets/javascripts/static/helpers/applicationsHelper.js
app/views/landing/index.html.erb
app/views/shared/_apps_menu.html.erb
app/views/shared/_home_menu.html.erb
app/views/shared/_navbar2_landing.html.erb
app/views/sitemap/index.html.erb
app/views/small_grants_fund/index.html.erb

If there are still links missing, we have a redirection to handle this.

Change SGF and DC links along the app

---

app/assets/javascripts/abstract/layer/AnimatedCanvasLayerClass.js
app/assets/javascripts/abstract/layer/CanvasLayerClass.js
app/assets/javascripts/map/views/layers/GladLayer.js

We only have tiles up to zoom 12 right now, so this changes makes any higher zoom levels use scaled up z12 imagery.

Scale GLAD layer after z12

---

app/assets/stylesheets/modules/map/_tab-highresolution.scss

The advanced settings in high resolution tab now have scroll in small screens.
Note: to be able to handle the selects this will display the native instead the choosen one because of the scroll.

Add scroll in high res settings

---

app/assets/javascripts/connect/templates/subscriptionListItem.handlebars
app/assets/javascripts/connect/views/SubscriptionListItemView.js
app/assets/javascripts/map/templates/tabs/subscribe.handlebars
app/assets/javascripts/map/views/layers/GladLayer.js
app/assets/javascripts/map/views/tabs/SubscribeView.js
app/assets/stylesheets/connect.scss
app/assets/stylesheets/modules/connect/_subscriptions.scss
app/assets/stylesheets/modules/map/_subscription-modal.scss

* Lets users pick a language for subscription emails (right now, portuguese or english, but more coming)
* Updates GLAD tile URL so we can see recent alerts highlighted

Subscription alerts language selector

---

app/assets/javascripts/stories/views/StoriesNewView.js

ZoomToStory function is only needed when you want to auto-locate. So it's probably unnecessary the listener as long as the auto-locate calls this function inside.

Bug: submit a story location

---

app/assets/javascripts/map/presenters/MapPresenter.js
app/assets/javascripts/map/presenters/analysis/AnalysisDrawPresenter.js
app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
app/assets/javascripts/map/services/PlaceService.js

Remove 'Geostore/go' from the place service.
It will only fire when a geostore is set on the URL. The one in charge to get the geojson is the AnalysisDrawPresenter, no one else needs it.

Remove geostore/go from the place service

---

app/assets/javascripts/map/templates/analysis/analysis-results.handlebars

Do not show 'analysis download button' tooltip unless downloads are disabled

Map: analysis download button

---

app/assets/javascripts/map/presenters/LayersNavPresenter.js

This PR just add two listeners to prevent breaking the style of the layersNav on each translation

Map: transifex translations does not break the layersNav

---

app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
app/assets/javascripts/map/services/GladDateService.js
app/assets/javascripts/map/services/TerraiDateService.js

Now the min date for the calendar is set from the API data.

Fix: Torque Calendar - Set min date from API (Glad, Terra-i)

---

app/controllers/countries_controller.rb

- The comment wasn't updated. 
NOTE: Use this to flush the countries cache.

Feat: Countries - Cache updated comment

---

app/assets/javascripts/static/ContributeDataView.js

This PR adds the credentials to the Backbone contribute model so the API will know which user is sending the contribution if it exists.

Contribute data: credentials

---

app/views/shared/_google_carto.html.erb

Updated the Google Maps API to version 3.26. Tested all of the basemaps and different overlays but we should test more before moving to prod.
FYI Removed the "sensor" parameter because it's deprecated and it's not needed to be sent in the url.

Feat: Google maps: version updated to 3.26

---

Gemfile
Gemfile.lock
app/assets/javascripts/static/ContributeDataView.js
app/controllers/static_controller.rb
app/views/static/contribute.html.erb
config/initializers/aws.rb

This PR applies the instructions available [here](https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails) to circumvent the Rails server (and hence Heroku) when uploading files to S3. This way the upload is made directly from the browser to S3.
* It adds the aws-sdk gem to manage this.
* It creates an initializer to setup the S3_DATA_BUCKET_NAME constant to instantiate the presigned_post that is then used by jQuery's fileupload plugin.
* It sets the signed post and adds the data fields to the form, that are then used by the jQuery plugin.
I've also added the dotenv-rails gem to the project to be used in development, because when you start the server with `rails server` the dotenv variables weren't being loaded to the ENV.
Currently there seems to be a CORS issue with …

Push files directly to s3

---

config/routes.rb

Prevent old URLs to be shown at the site search.

Old urls redirected

---

app/assets/javascripts/map/services/MapLayerService.js
app/assets/stylesheets/modules/map/_timeline.scss

- `min-width` removed (it isn't necessary)
- `fit_to_geom` param removed from MapLayerService (it isn't necessary)

Timeline: style amendments

---

app/assets/javascripts/abstract/layer/CartoDBLayerClass.js
app/assets/javascripts/connect/router.js
app/assets/javascripts/connect/templates/regionSelection.handlebars
app/assets/javascripts/connect/templates/subscriptionNew.handlebars
app/assets/javascripts/connect/templates/subscriptionNewCountry.handlebars
app/assets/javascripts/connect/templates/subscriptionNewData.handlebars
app/assets/javascripts/connect/templates/subscriptionNewDraw.handlebars
app/assets/javascripts/connect/views/CountrySelectionView.js
app/assets/javascripts/connect/views/LayerSelectionView.js
app/assets/javascripts/connect/views/MapMiniControlsView.js
app/assets/javascripts/connect/views/MapMiniDrawingView.js
app/assets/javascripts/connect/views/MapMiniSelectedView.js
app/assets/javascripts/connect/views/MapMiniUploadView.js
app/assets/javascripts/connect/views/MapMiniView.js
app/assets/javascripts/connect/views/SubscriptionNewView.js
app/assets/javascripts/core/View.js
app/assets/javascripts/views/SourceModalView.js
app/assets/stylesheets/modules/_buttons.scss
app/assets/stylesheets/modules/_section-new.scss
app/assets/stylesheets/modules/_select.scss
app/assets/stylesheets/modules/_uploads.scss
app/views/layouts/connect.html.erb
app/views/shared/_notifications.html.erb

This PR contains several fixes and improvements from the subscription page:
- Core VIEW with a subscribe, unsubscribe and remove function
- Country/region selection shown on map
- Email (auto populate from user)
- Several UX improvements
- Added the same info window for uploading as the map has
There are still some **pending**:
- Remove button to add data to map (add it to "subscription saved" window that appears after the user subscribes (see attached)). I don't want this button to compete with the subscribe button!
- Don't make people sign in (or create a profile) until after they have clicked subscribe
- At least for data sets on GFW, can we change the URL, so, for example, we could send a link to protected area managers with the protected area data set and GLAD alerts pre-selected?
- …

Subscriptions new

---

app/assets/stylesheets/layouts/_countries.scss

- Issue on Safari 8 due to missing flex prefixes

Fix: Countries - Safari 8 CSS issues

---

app/assets/javascripts/static.js
app/assets/javascripts/static/ContactUsView.js
app/assets/stylesheets/modules/_steps.scss
app/assets/stylesheets/static.scss
app/views/shared/_navbar2_landing.html.erb
app/views/sitemap/index.html.erb
app/views/static/about.html.erb

Use a new form in the about page instead the feedback form of the gfw-assets.
TODO: move the endpoint url to the new one when it is ready.

Add contact form to about page

---

app/assets/javascripts/connect/templates/userForm.handlebars
app/assets/javascripts/connect/views/UserFormView.js
app/views/shared/_notifications.html.erb

Support for a new flag for new registered users, to redirect them to their user profile to fill the required information.
The redirect is handled by the gfw-assets bar, then the app handles the rest.

Feat: User - Required profile data

---

app/assets/javascripts/connect/views/SubscriptionNewView.js
app/assets/javascripts/map/views/LegendView.js

Solves issue when removing the view, also changed the way the listener was being attached so it gets removed automatically when using `view.remove();`

Fix: Subscriptions - Legend listeners and remove

---

app/assets/javascripts/connect/views/MapMiniDrawingView.js
app/assets/javascripts/map/views/analysis/AnalysisDrawView.js
app/assets/stylesheets/layouts/_map.scss
app/assets/stylesheets/modules/connect/_subscription.scss

Add an instruction tooltip to the map when user begins drawing on subscriptions map:
- Append tooltip when user clicks 'start drawing' button
- Add listener for mousemove with tooltip tracking with cursor location
- CSS transition opacity for smooth view (no official design yet)
- When user finishes drawing or cancels drawing, remove tooltip and listener

Feature: tooltip for subscriptions draw map

---

app/assets/javascripts/countries/views/CountryOverviewView.js

The query wasn't ignoring null rows, now it does.

Fixes query to get ranking for forest gain

---

README.md
app/assets/javascripts/connect/views/LoginView.js
app/assets/javascripts/connect/views/SubscriptionNewView.js
app/assets/javascripts/map/views/tabs/SubscribeView.js
app/assets/javascripts/stories/views/StoriesNewView.js
app/views/shared/_js_config.html.erb

Different endpoint for the auth links, since it won't support the same API versioning.
New .ENV variable `GFW_API_AUTH`

Feat: Endpoint for the auth links

---

app/assets/javascripts/map/cartocss/style.cartocss
app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/templates/infowindow.handlebars
app/assets/javascripts/map/views/layers/CanOilLayer.js

This PR addresses the bascamp issue **Add Canada petroleum and natural gas to staging**
Note. The Info box slug *can_oil* is correctly connected on the *layerspec*, however, in testing no metadata was returned indicating a problem on the gfw-owned micro-service side.

Feat: Add Canadian petrolium and natural gas

---

app/assets/javascripts/map/cartocss/style.cartocss
app/assets/javascripts/map/views/layers/IdnLeuserLayer.js

We have been asked to update the boundary of the Lesure Ecosystem, via a Basecamp issue from Alyssa Barrett. Previous boundary had details removed. They sent a new shape-file, which I added to a [new table](https://wri-01.carto.com/tables/leuser_ecosystem_province_boundary/table) on WRI01 carto account. After this, a minor update to modify the table name in the JS class and css were needed. The effect of the changes are shown below:

Feat: Update Indonedia Leuser boundary

---

app/views/small_grants_fund/index.html.erb

Under How To Apply, changed text to: The Small Grants Fund application period is now closed. For questions about the Small Grants Fund, or to sign up to be notified when the application period opens, please write to gfwfund@wri.org.

closed SGF application period

---

app/assets/javascripts/map/cartocss/style.cartocss
app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/views/layers/HaitiWatershedLayer.js

Added a new layer for Haiti Watersheds (user data) in response to a [basecamp request](https://basecamp.com/3063126/projects/10726176/todos/308528958).

User data for Haiti watershed areas

---

app/assets/javascripts/map/views/layers/FormaActivityLayer.js
app/assets/javascripts/map/views/timeline/FormaActivityTimeline.js

Updated default timeframe to be 48 hours instead of 24.

Feat: FORMA Active clearing alerts - Updated timeframe

---

app/assets/javascripts/map/views/layers/SentinelLayer.js

- Fixed blank tiles by changing to PNG format and adding the query param `&TRANSPARENT=TRUE`
- Fix issue with the metadata returning information when there wasn't any tiles by adding missing parameters in the query
- Fixed duplicated click events not being removed.

Feat: Sentinel - Fixed blank tiles, click events,

---

app/assets/javascripts/map/templates/maptype.handlebars
app/assets/javascripts/map/templates/tabs/basemaps.handlebars
app/assets/javascripts/map/views/MapView.js
app/assets/javascripts/map/views/maptypes/landsatMaptype.js

* We have added tiles for Landsat 2016 (up to z-level 6) and hooked them up to the front-end
Note: the Earth Engine specifics to replicate these data are:
```javascript
var collection = ee.ImageCollection('LANDSAT/LC8_L1T').filterDate('2016-01-01T00:00','2017-01-01T00:00');
var composite = ee.Algorithms.Landsat.simpleComposite({collection: collection, percentile: 50, maxDepth:80, cloudScoreRange: 1, asFloat:true});
var hsv2 = composite.select(['B4', 'B3', 'B2']).rgbToHsv();    
var sharpened2 = ee.Image.cat([hsv2.select('hue'), hsv2.select('saturation'), composite.select('B8')]).hsvToRgb().visualize({gain:1000, gamma: [1.15, 1.4, 1.15]});
```
The tiles were exported to the GCS bucket `landsat-cache/2016/`

Landsat 2016 basemap

---

app/assets/javascripts/map/templates/layersNav.handlebars

Added metadata for Forma menu items (alerts and active clearing alerts). Connected to [BC thread](https://basecamp.com/3063126/projects/10726176/todos/303096581#events_todo_303096581).
Layerspec (nuclear_hazard) has also been updated: `source_json` entries 936 and 937.

Forma metadata

---

app/assets/javascripts/common/views/LineGraphView.js
app/assets/javascripts/countries/templates/widgets/treeCoverLossAlerts.handlebars
app/assets/javascripts/countries/views/widgets/TreeCoverLossAlertsView.js
app/assets/stylesheets/modules/countries/widgets/_tree-cover-loss-alerts.scss

- Change "MONTHLY TREE COVER LOSS ALERTS" to "MONTHLY COUNTS"
- On "Data Shown" selector, change "By month" to "Subnational"
- Fix spacing of the Hi-res and Subscribe buttons (they're good on zeplin)
- Add more months to the spark line, should show 12
**Before**
**After**

Improve tree cover loss alerts widget

---

app/assets/javascripts/connect/views/CountrySelectionView.js

The logic handling country changes and region changes was triggering model updates twice, and one render would override the other, causing the wrong centering of the region regardless of it being set or not. I separated the logic blocks so we only call the updates once. (please note that the case of region being null/undefined it's handled separately several times down the chain.)

replace double update with better logic

---

app/assets/javascripts/map/cartocss/palm_oil_mills.cartocss
app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/templates/infowindow.handlebars
app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/views/layers/PalmOilMillsLayer.js

[Basecamp issue here](https://basecamp.com/3063126/projects/10726176/todos/311103923).
New layer added *Land Use* > *Infrastructure*: *Palm Oil Mills* 
These data have been moved from the GFW commodities product.
*New table added to Carto account (oil_palm_mills)
*New row added to layerspec_nuclear_hazard: row 946

Added Palm oil mills layer

---

app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/templates/legend/idnSuitability.handlebars
app/assets/javascripts/map/views/LegendView.js
app/assets/javascripts/map/views/layers/IdnSuitabilityLayer.js

See [Basecamp issue](https://basecamp.com/3063126/projects/10726176/todos/311103503)
* I uploaded the raster data to Earth Engine, and created a webmap, exported to our GCS account for tiles from z0 to z13.
* Added the new layer to the Indonesian data section on the map

Added Indonesian Palm Oil Suitability layer to Indonesia 

---

app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/templates/legend/bra_rtrs.handlebars
app/assets/javascripts/map/templates/legend/pry_rtrs.handlebars
app/assets/javascripts/map/views/LegendView.js
app/assets/javascripts/map/views/layers/BraRTRSLayer.js
app/assets/javascripts/map/views/layers/PryRTRSLayer.js

[Moving raster data from GFW commodities](http://commodities.globalforestwatch.org/#v=map&x=-51.73&y=-13.93&l=5&lyrs=responsibleSoy) by means of Earth Engine upload to GCS bucket.
[Basecamp issue](https://basecamp.com/3063126/projects/10726176/todos/311103365)
Two identical layers added:
* One for Brazil country data
* One for Paraguay country data
* layerspec_nuclear_hazard rows 950 and 948
* Processed data added to GCS bucket gfw-data-layers/BRA_RTRS_soy

Responsible Soy layer working for Brazil

---

app/assets/javascripts/map/cartocss/style.cartocss
app/assets/javascripts/map/helpers/layersHelper.js
app/assets/javascripts/map/models/LayerSpecModel.js
app/assets/javascripts/map/views/layers/BraSoyCerradoLayer.js

Added Brazilian Soy in Cerrado to map in Brazil country data, according to [BC thread](https://basecamp.com/3063126/projects/10726176/todos/311103798).
* New [table in Carto](https://wri-01.carto.com/tables/bra_soy_vector)
* New row in layerspec nuclear hazard (row 951)

Brazilian soy data layer for map

---

app/assets/javascripts/map/views/maptypes/landsatMaptype.js

[BC thread](https://basecamp.com/3063126/projects/10726176/todos/249308923) post by Mikela on 25th July.
Changed max zoom limits on recent Landsat imagery to Z17.

Changed max zoom on Landsat 2015 and 2016 basemaps to z17

---

app/assets/javascripts/map/views/MapView.js
app/assets/javascripts/map/views/maptypes/landsatMaptype.js

Using the same method as for the 2015/2016 layers I have gone back and re-created the 2014 and 2013 landsat layers, pre-calculating the tiles between z0 and z11 (inclusive), and also added them to the micro-service so the higher z-levels are live from Earth Engine.

Added 2013 and 2014 landsat layers

---

app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/views/layers/RaisgLayer.js
app/assets/javascripts/map/views/layers/RaisgMiningLayer.js

This PR deactivates RASIG, which has become problematic after they updated their Argis WMS. We are leaving the layers in the codebase for future reference.
We have also set the display of these layers to false in the layerspecs.

Deactivating bad RASIG layers

---

app/assets/javascripts/map/presenters/LayersNavPresenter.js
app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/templates/legend/concesiones_forestales.handlebars
app/assets/javascripts/map/templates/legend/concesiones_forestalesType.handlebars
app/assets/javascripts/map/templates/legend/glad.handlebars
app/assets/javascripts/map/templates/legend/legend.handlebars
app/assets/javascripts/map/templates/legend/plantations_by_species.handlebars
app/assets/javascripts/map/templates/legend/plantations_by_type.handlebars
app/assets/javascripts/map/views/LayersNavView.js
app/assets/javascripts/map/views/LegendView.js
app/assets/stylesheets/modules/map/_module-legend.scss

Fix&Improve:
-  Leave the metadata icons enabled even if the layer is made invisible.
- Make the legend elements gray as well when the layer is set to invisible.
- Add space between Category name and number of layers.
(https://www.pivotaltracker.com/story/show/149555321)

Improve and fix styles on legend

---

app/assets/javascripts/views/SourceModalView.js

The old endpoint stopped working do to a change on IP. This an endpoint from the old API and will need to be migrated in the future, for now we created a proxy endpoint in the GFW production api.
This needs to be deployed to production today.

Use the new proxy endpoint created on the production API

---

app/assets/javascripts/map/templates/legend/glad.handlebars

- Fix problem with info-modal on places to watch on map legend.
- (https://www.pivotaltracker.com/story/show/151245998)
(No notes)
- Active glad legend.
- Click info button next to places to watch text.

Include info on places to watch legend

---

app/assets/javascripts/map/services/GladDateService.js

When viewing the GLAD layer: http://localhost:3000/map/3/15.00/27.00/ALL/grayscale/umd_as_it_happens,places_to_watch?tab=analysis-tab&begin=2015-01-16&end=2017-09-16&dont_analyze=true the time ranger selector on the timeline was picking the wrong date to start from (2016) instead of 2015. So the users couldn't select any dates inside of 2015.
This PR fixes this and suggests a merge directly to master to make it available in production. If all good this commit should then be merged to develop to ensure it persists.

Date selector for GLAD is picking the wrong start year for the datepicker

---

app/assets/javascripts/map/presenters/GladLayerPresenter.js
app/views/shared/_notifications.html.erb

Previously when users selected the GLAD layer we were showing a banner
with some information about its state. This is no longer necessary.
This commit removes it from the application completely.

Removes GLAD notification from map

---

app/assets/javascripts/map/templates/layersNav.handlebars

Changes the order of deforestation alerts with tree cover change.
This was on staging for a while, but now that GLAD is back we can move it to production as well.

Change menu order

---

app/assets/javascripts/countries/views/CountryOverviewView.js

Following from this BC thread: https://basecamp.com/3063126/projects/10726176/todos/327458495 
It seems that:
"apparently the current table structure on CARTO requires a value for every cell. Even though the data is not annual, we put in the total value for every year 2001 to 2012. So it does indeed need to be divided by 12 on both the individual country pages and on the country rankings page!"
So we need to divide that value per 12.

Divides gain by 12 on the total big figure for country rankings page

---

app/assets/javascripts/map/templates/layersNav.handlebars

It seems that in July we removed the SAD alerts from the map navigation in this commit: https://github.com/Vizzuality/gfw/commit/45a48c229071daf5ac093cbf764ac3e5aa307917
But talking with Mikaela it seems that this was not supposed to be like this. So I'm returning it to the production site now.

Returns SAD alerts to application

---

app/assets/javascripts/map/views/layers/FormaActivityLayer.js
app/assets/javascripts/map/views/timeline/FormaActivityTimeline.js

There was an issue with the filtering of the forma active clearings for the past 48 hours, related to the timing of the alerts what we were hoping to do with the "Past 48 hours". We are now replacing that with "Past 2 days" and making sure that we capture the past two days and a bit more regardless of the time you visit the site.

Fixes issue with filtering data from past 2 days

---

app/assets/javascripts/countries/views/CountryOverviewView.js

As described in [this BC post](https://basecamp.com/3063126/projects/10726176/todos/327458495) there has been a problem with the country ranking page values (e.g. we have been saying that forest increased by >1,000% over the past 10 years), the values in the ranked lists were also incorrect: This PR addresses those issues.
(Below screen shots are for 50% tree canopy)

Fixed long-term problem with country rankings page

---

app/assets/javascripts/map/models/LayerSpecModel.js

This addresses [BC bug](https://basecamp.com/3063126/projects/10728552/todos/332155798).
Ensures new sentinel image appears below other layers on the map.

Put sentinel data at the bottom of the image stack

---

app/assets/javascripts/map/services/LayerSpecService.js

Following [this](https://basecamp.com/3063126/projects/10728552/todos/331321730) basecamp thread, a fix has been implemented so that attempting to toggle on forbidden layer combinations does not remove all previous layers!
Instead, attempting to toggle an invalid combination only removes the conflicting previous layer(s).
e.g. Starting from the default layers (Forest Loss, Forest Gain, Tree Cover) and attempting to toggle on GLAD alerts removes only the Loss/Gain layers, but not Tree Cover.

Toggling forest change layers preserves Tree cover layer

---

app/assets/javascripts/map/templates/layersNav.handlebars

Quick fix to change Tree Cover subtitle to (2000/2010, Hansen/UMD/Google/USGS/NASA) as per [this](https://basecamp.com/3063126/projects/10726176/todos/287938139#comment_580061332) Basecamp thread.

Changes treecover menu subtitle

---

app/assets/stylesheets/layouts/_grid.scss
app/javascript/components/modal/modal-component.jsx

Feedback from @juancarlosalonso the modal is now a contained box which scrolls inside the overlay in stead of inside itself.
BONUS: remove unwanted grid break point on old pages.

Fix: correct modal styles

---

app/assets/stylesheets/modules/map/_module-legend.scss

You couldn't see the meta buttons on the mobile map layers menu, now you can.

make info buttons visible again

---

app/javascript/pages/country/data/categories.json
app/javascript/pages/country/data/widgets-config.json
app/javascript/pages/country/widget/widgets/widget-tree-cover/widget-tree-cover-selectors.js
app/javascript/pages/country/widget/widgets/widget-tree-cover/widget-tree-cover.js

* Added more menu options to widgets
* Assigned widgets to different tabs
*  I also changed the order of some of the widgets and the order of the tabs
* Refining by location `plantations` in the Tree cover Extent widget now results in the legend showing `Tree Plantations` as a label rather than `Tree Cover`. (Addressed PT bug #153854716 )

Bugfix on Tree cover extent plantation legend and update widget configs

---

app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js

Fixes mismatching date range between the analysis window and the timeline widget on load and when toggling between layers (see: [Basecamp Thread](https://basecamp.com/3063126/projects/10728552/todos/336207167#comment_589219492)).
Affected Analyses: 'Terra-i' and 'Forma'

Fixes incorrect date ranges in Analysis

---

app/assets/javascripts/map/cartocss/style.cartocss

Changed the colour of the Mangrove (2000) layer to match the style change of the new Mangrove layer.
* Updated Carto table too 
* Color change from #05ffaa to  #06ef9f

Mangrove (2000) layer style change

---

app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
app/assets/javascripts/map/templates/analysis/analysis-results.handlebars

Adds the ability to analyse the 2010 Tree Cover layer using the new staging api as requested [here](https://basecamp.com/3063126/projects/10726176/todos/287938139#comment_590680218).
When testing be sure to use the staging api **not production**!
e.g. ```https://staging-api.globalforestwatch.org/v1/umd-loss-gain?geostore=cea8c6...```

Adds analysis capability to Tree Cover 2010 layer

---

app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/templates/legend/glad.handlebars

This PR attempts to solve BC threads [here](https://basecamp.com/3063126/projects/10726176/todos/335091623)  and [here](https://basecamp.com/3063126/projects/10726176/todos/335169764). 
The info button has been added to the PTW layer. But we are still missing the layer being turned on by default when a user selects GLAD Alerts.

Include info button on places to watch legend

---

app/javascript/pages/country/data/widgets-config.json
app/javascript/pages/country/reducers.js
app/javascript/pages/country/widget/widget-actions.js
app/javascript/pages/country/widget/widget-component.jsx
app/javascript/pages/country/widget/widgets/widget-relative-tree-cover/widget-relative-tree-cover-actions.js
app/javascript/pages/country/widget/widgets/widget-relative-tree-cover/widget-relative-tree-cover-component.js
app/javascript/pages/country/widget/widgets/widget-relative-tree-cover/widget-relative-tree-cover-reducers.js
app/javascript/pages/country/widget/widgets/widget-relative-tree-cover/widget-relative-tree-cover-selectors.js
app/javascript/pages/country/widget/widgets/widget-relative-tree-cover/widget-relative-tree-cover-styles.scss
app/javascript/pages/country/widget/widgets/widget-relative-tree-cover/widget-relative-tree-cover.js

Added start of Relative tree cover widget by updating config file. This is the remaining piece of the tree cover widget which was split up after suggestions from Juan Carlos.
The widget should show a ranked list of relative tree cover (%), in a half-width widget.
The dynamic sentence should say. 
```<1st Sub region> had the largest relative tree cover of <X>%, compared to a regional average of <Y>%, considering tree cover extent in <year> with a canopy cover of greater than <Z>%.```

Added config for relative TC widget

---

app/controllers/landing_controller.rb

The link needed updated since the Developers Corner was updated.
Open homepage and see the correct link under the card "A Suite of Tools" after the header.

Update link on homepage

---

app/javascript/components/modal-meta/modal-meta-actions.js
app/javascript/components/modal-meta/modal-meta-styles.scss
app/javascript/components/modal-meta/modal-meta.js
app/javascript/pages/country/widget/components/widget-header/widget-header-component.js

We have a new case where when pushing meta data to the modal, for the widgets we only want to show a selection of the meta data, but for other cases we want to show everything. Instead of trying to manage each case inside the component, why not allow the parent to pass a whitelist of keys of what to show? Well now you can. If you don't pass a whitelist it just shows the full set as per the map.

Allow whitelisting of meta data in modal

---

app/javascript/pages/country/data/widgets-config.json
app/javascript/pages/country/widget/widgets/widget-intact-tree-cover/widget-intact-tree-cover-selectors.js
app/javascript/pages/country/widget/widgets/widget-primary-tree-cover/widget-primary-tree-cover-selectors.js

Changes in Intact forest and primary forest extent widgets in relation to various BC threads:
* [1](https://basecamp.com/3063126/projects/10727890/todos/340012070)
* [2](https://basecamp.com/3063126/projects/10727890/todos/340012462)
* [3](https://basecamp.com/3063126/projects/10727890/todos/340012348)
Changes include:
* Limit Primary forests to DRC and IDN
* Change dynamic sentence to show % of total tree cover for Intact and primary forests (rather than % relative to total area)
* Place logical test on Primary forests to catch a (hopefully short-term) bug in the data where the primary forest seems larger than total region forest
* Remove options from Primary forest widget, to make it show only with 2000 tree cover extent (as this is related to the original primary forest data)

updated intact and primary widgets in line with BC comments

---

app/javascript/pages/country/widget/components/widget-horizontal-bar-chart/custom-tick-component.jsx

Changes Ranked Plantations Extent widget label to 'XX% are plantations'.

Updates ranked list label

---

app/javascript/pages/country/data/widgets-config.json
app/javascript/pages/country/widget/widget-selectors.js
app/javascript/pages/country/widget/widget.js

HOT FIX: Use a colors prop if needed to use a type of loss for whitelisting in the indicators selector.

use colors when type loss key is needed

---

app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/templates/legend/glad.handlebars
app/assets/javascripts/map/views/LayersNavView.js
app/assets/javascripts/map/views/LegendView.js
app/views/shared/_js_config.html.erb

A much needed update to the process for showing layers on staging without showing them on production. A simple process:
- Sync the layers menu with master manually so that we look the same
- Add a new env variable `FEATURE_ENV` to allow handlebars templates to know if we are in staging
- Update handlebars template to only show menu items when on staging

sync master layer menu with develop

---

app/assets/javascripts/abstract/timeline/TimelineDatePicker.js

HOTFIX for glads calendar not letting user select first day of data.

Allow selection of first day in GLADS calendar

---

app/javascript/components/button/button-component.jsx
app/javascript/components/dropdown/dropdown-component.js
app/javascript/pages/country/header/header-component.js

Improves the use of tooltips in buttons and dropdowns. Now both can accept a much simpler tooltip object:
``` { text: "my excellent message" }```
However if you would like more customisation then you can pass any option from react tippy props as well:
``` { text: "my message", delay: 3000 }```
This was to reduce the importing of the Tip component throughout the project when its application was always the same.
In addition a tooltip has been added for the Dropdown component to allow the header section of the dashboard to have individual tooltips without extra code.
FINALLY, I also added a state prop which prevent tooltips from being shown in the header when a dropdown is open. This makes the user a lot happier I think.

Feature: improved tooltips for components

---

app/javascript/pages/country/widget/widgets/widget-fao-cover/widget-fao-cover-selectors.js
app/javascript/services/forest-data.js

Previously we were excluding countries which had no Primary Forest data in the fao table. That meant that the FAO extent widget used to look like this:
The Irish were sad.
Now we accept data from all countries, whether they had Primary Forests or now. We don't discriminate. Instead, we handle null data on the front end so that the widget now looks like this:
_You're welcome_, Ireland.
Please test! I will compile a list of countries without Primary forests in the fao data and stick it here shortly...
EDIT: here's the list
{'COL', 'CMR', 'EGY', 'JEY', 'GGY', 'FRA', 'MAF', 'UNK', 'KEN', 'PSE', 'MTQ', 'ABW', 'GNQ', 'SSD', 'ISR', 'AFG', 'YEM', 'TLS', 'TWN', 'DOM', 'GIB', 'BFA', 'ETH', 'CUB', 'MAC', 'MAR', 'SWZ', 'TZA', 'BEN', 'BES', 'AIA', 'BMU', 'DEU', 'LSO', 'BLM', 'HTI', 'CYM', 'UMI', …

Updates FAO extent query to include countries with no primary forest

---

app/javascript/services/forest-data.js

There was an issue in that the *'Where is Forest Loss Located?'* was reporting larger loss in adm2 regions than was found in the entire adm1 supra-region!
This was due to a small bug in the way the aggregated loss query was formed, which had now been fixed!
As always, please test!
- Check the values [here](http://www.globalforestwatch.org/country/IDN/24?widget=lossLocated#lossLocated)
- Check that they match for the total reported in each adm2 region [here](http://www.globalforestwatch.org/country/IDN/24/301?widget=treeLoss#treeLoss)
- Are they consistent (e.g.**947kha** =/= **120kha** in this case... but should be fixed in local)

Fixes getLocationsLoss query

---

app/javascript/pages/country/widget/widgets/widget-loss-ranked/widget-loss-ranked-selectors.js

Currently on production there is a calculation error between the [loss by year](http://www.globalforestwatch.org/country/BRA?widget=treeLoss#treeLoss) and the [global loss ranking](http://www.globalforestwatch.org/country/BRA?widget=lossRanked#lossRanked) widgets - meaning that the area_loss% values do not match in the dynamic sentences
This commit fixes the issue.

Fixes percentage calculation bug in Global Loss Rank

---

app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/views/layers/BiodiversityCompletenessLayer.js

Oh boy, here I go updating Biodiversity layers again!
The new layer is possibly the greatest achievement in biodiversity layer visualisation. It's got **new technology**, implementing the RW-API layer hosting.
It's already being described as *on*, for production.
It also updates the layer to paint pixels only where forest data exists, deciding the significance of biodiversity in a region in a way that can satisfy any data scientist or researcher, at least. And indeed, *at most*.
Looking ahead to May, we can hope **not** to see any more updates to biodiversity metrics several times, and in various combinations.
Please leave open and merge with staging. I will need to update the LayersNav if everyone is happy with this layer to go to prod.

Biodiversity Significance Layer 3.0

---

app/javascript/components/widget/widget-config.json
app/javascript/services/forest-data.js

* 1990's were missing from the employment widget. Added it back in.
* Changed default year from 2000 to 2010 for economic widget.
* Created a whitelist to prevent the economic widget from appearing on pages where no data exists.
* whitelist 
E.g. Check http://localhost:5000/country/BHR?category=people
Bahrain page should have no economic widget.
* 1990's - Angola should have 1990's data, where it didn't before
http://localhost:5000/country/AGO?category=people&forestryEmployment=eyJ5ZWFyIjoxOTkwfQ%3D%3D

fixing a couple of bugs on FAO people widgets

---

app/javascript/services/forest-data.js

Updates sql queries in preparation for global dashboard.

SQL Refactor for Global Pages

---

app/javascript/components/widgets/widgets/land-cover/fao-cover/actions.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/initial-state.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/services/forest-data.js

Be the best FAO widget you can be.
Appears to work correctly for Global and Country situations. However, please test that `area_ha` returns correctly as we have to parse from string --> int :(

FAO Globalisation, Tree-Cover Tab

---

app/javascript/components/widgets/widgets/climate/emissions/selectors.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
app/javascript/components/widgets/widgets/land-cover/ranked-plantations/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
app/javascript/components/widgets/widgets/people/economic-impact/selectors.js
app/javascript/components/widgets/widgets/people/forestry-employment/selectors.js

All dynamic sentences should now:
- Use 2sf w/ no prefix-symbols for %
- if % < 0.1 then it will state so
- All Ha use 3sf w/ prefixes (G, M, etc)
- All indicators to lower case

Universal Sentence Formatting

---

app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js

Removes indicators with broken units (AZE, KBA, TCL) from the only widget currently using them.
NOTE: this only affects gain and loss widgets

Removes indicators with broken units

---

app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js

Adds *'Other Tree Cover'* category to FAO Cover Widget fo instances where the extent is not categorised as Regenerated, Planted, or Primary Forest.

Fixes data issue with fao pie chart

---

app/assets/javascripts/helpers/datasetsHelper.js

Forma alerts meta data slugs were out of date on the subscriptions page.

Update forma alerts metadata slug

---

app/javascript/components/charts/horizontal-bar-chart/horizontal-bar-chart-component.js

We have a bug that when changing screen size the horizontal bar chart isnt interested. This is due to a bug in recharts responsive component. A check for 99% width has been added for force the resize.

Fix: force resize horizontal bar chart

---

app/javascript/components/charts/components/chart-tooltip/chart-tooltip-component.js
app/javascript/components/charts/components/chart-tooltip/chart-tooltip-styles.scss
app/javascript/components/charts/pie-chart/pie-chart-component.js
app/javascript/components/widgets/components/widget-pie-chart-legend/component.jsx
app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js

Pie charts on widgets were showing 'label' in some cases due to an order error in logic for selecting the key from the data.

fix pie chart tooltip when no label given

---

app/javascript/components/widgets/components/widget-header/widget-header.js
app/javascript/components/widgets/widgets/climate/emissions-deforestation/initial-state.js
app/javascript/components/widgets/widgets/climate/emissions/initial-state.js
app/javascript/components/widgets/widgets/conservation/glad-biodiversity/initial-state.js
app/javascript/components/widgets/widgets/forest-change/fao-deforest/initial-state.js
app/javascript/components/widgets/widgets/forest-change/fao-reforest/initial-state.js
app/javascript/components/widgets/widgets/forest-change/fires/initial-state.js
app/javascript/components/widgets/widgets/forest-change/glad-alerts/initial-state.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-global/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss/initial-state.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/initial-state.js
app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
app/javascript/components/widgets/widgets/land-cover/primary-forest/initial-state.js
app/javascript/components/widgets/widgets/land-cover/ranked-plantations/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
app/javascript/components/widgets/widgets/people/economic-impact/initial-state.js
app/javascript/components/widgets/widgets/people/forestry-employment/initial-state.js

For both translations and custom widget titles we needed to change them to use the same method as the dynamic sentences.

make widget titles translateable and editable

---

app/javascript/components/widgets/widgets/forest-change/fao-deforest/selectors.js
app/javascript/components/widgets/widgets/forest-change/fao-reforest/selectors.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
app/javascript/pages/dashboards/header/header-selectors.js

All widget dynamic sentences should now report loss/gain/extent areas that are less than 1ha as a 3sf value instead of using symbol notation:
> e.g. 0.135 ha *instead of* 135 mha
Please test all widgets - its difficult to find numbers in some cases! Most importantly, check that changing units (ha/%) still works as it should.

Feature - Low extent values

---

app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js

There seems to be an error in the FAO dataset (possibly rounding on their part) where the sum of all the forest types can be greater than the measured extent, resulting in this:
To avoid this, we now check that the sum of forest types **does not** exceed the extent. If it does, ignore it and set Other Tree Cover to 0ha.
If sum of forest types is less than total extent, Other tree cover is the remainder.
Also bundled in a new default setting for Tree Cover Ranking that was missed.

Removes uncorrect Other Tree Cover values

---

app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
app/javascript/data/colors.json

Standardises colour palette across all extent widgets. All extent widgets refer to colors.json
```json
{
"extent": {
...
"naturalForest": "#506917",
"intactForest": "#6b8729",
"primaryForest": "#84a637",
"plantedForest": "#a0c746",
"otherCover": "#c7e67c",
"nonForest": "#e7e5a4"
},
```
Probably a good idea to get advice from Designer before pushing.

Standardised extent pallet

---

app/javascript/components/widgets/widgets/forest-change/fao-deforest/selectors.js
app/javascript/components/widgets/widgets/forest-change/fao-reforest/selectors.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js

Reduces amount of code when deciding formatting scheme for extent/gain/loss areas.

Cleans up code

---

app/javascript/pages/dashboards/header/header.js
app/javascript/pages/dashboards/page/page-component.js

BUG FIX: when changing routes on the header of the dashboard, the widget settings for forestType and landCategory were not reseting (not good with whitelists). Now they do.

reset forestType and landCategory when changing route

---

app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js

Makes pie chart on global dashboard add to 100% by correctly removing plantations areas (not included in calc)

Global 100%

---

app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js

Quick update to gain sentences and defaults as per feedback.
- sentences no longer reference gain relative to extent (apples & oranges)
- removes extent year option

Updates gain widgets

---

app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
app/javascript/pages/dashboards/header/header-reducers.js

Last round of feedback implementations.
- Gain selectors removed. No extent year or % available
- Some Dynamic Sentences updated
- Plantations loss maths fixed!

Feedback implementation

---

app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
app/javascript/pages/dashboards/header/header-selectors.js

The Natural Forest Loss widget was missing the biomassToCo2 function to convert to the correct units for emissions. This fixes that and makes the value quoted in the header file consistent in format.

Fixes Emissions Calculations in Natural Forest Loss widget

---

app/assets/javascripts/map/services/LandsatService.js
app/assets/javascripts/map/templates/maptype.handlebars
app/assets/javascripts/map/templates/tabs/basemaps.handlebars
app/assets/javascripts/map/views/MapView.js
app/assets/javascripts/map/views/maptypes/landsatMaptype.js

2017 now appears in the basemaps > Landsat section and is fully functional.

Added Landsat 2017 to the basemaps

---

app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
app/javascript/services/alerts.js
app/javascript/services/forest-data.js
app/javascript/utils/strings.js

Fixes for:
- alerts queries to correctly use forestType and landCover
- fixes broken while loop logic on all widgets that use it (e.g. *The top 3 regions are responsible for 65% of GLAD alerts*)

Fixes GLAD ranking queries

---

app/javascript/components/widgets/widgets/climate/emissions/selectors.js
app/javascript/utils/format.js

We wanted to show the total emissions in the tooltip to give context to the emissions percentages shown in the chart

CW Historical emissions: add totals to the tooltip

---

app/assets/javascripts/map/cartocss/intact2013.cartocss
app/assets/javascripts/map/templates/layersNav.handlebars
app/assets/javascripts/map/templates/legend/intact2013.handlebars

Updated the IFL layer as per [BC thread](https://basecamp.com/3063126/projects/10726176/todos/354439702). Note, this layer needs to be updated on production by June 18th.
* 2016 data
* New table source
* New class
Updated table Carto name in layerspec (new table is called `ifl_2000_2013_2016` row 607 in nuclear hazard) - need to update the prod layerspec table on move to master.

updated the IFL layer

---

app/assets/javascripts/services/CountryService.js
app/controllers/dashboards_controller.rb
app/javascript/providers/country-data-provider/country-data-provider-actions.js
app/javascript/services/country.js
app/javascript/services/whitelists.js
app/models/dashboards.rb

To match the new GADM36 nomenclature, we need to update the blacklisting in rails and the country service in the js. This updates all the SQL and removes the uneeded blacklist fetch for subRegions.

update dashboard blacklists to use the new gid codes

---

app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
app/assets/javascripts/map/services/AnalysisNewService.js
app/assets/javascripts/map/templates/analysis/analysis-results.handlebars

Adds condition to allow multiple fetches in the case of All Forest Change layers, mapping the response values onto `results.loss`.
~SAD Alerts (aka IMAZON) does not work due to incorrect api response. Should work once fixed.~
This is now fixed and should work. See [example response](https://production-api.globalforestwatch.org/imazon-alerts?geostore=2d3970d94dd23b93697fef948da0cf6f&period=2008-01-01%2C2018-03-01&thresh=30&_=1530526547935).

Allows all forest change layers to be used in analysis

---

app/javascript/components/widgets/components/widget-pie-chart-legend/component.jsx
app/javascript/components/widgets/widgets/people/forestry-employment/initial-state.js

Pulls unit from `initial-state` config, instead of just `ha` for all widgets.

[Dashboards]: Fixes unit issue in employment pie-chart legend

---

app/assets/javascripts/services/CountryService.js

On the map, when triggering an analysis for admin 0 - admin 2 areas, green geometry shapes to be added to the map should now be returned from GADM 3.6 tables (via datasets in the API).
* Note - these tables are only in the production api (so if your env is pointing to staging, the shapes will not be returned).

Changed table sources to point at gadm3.6 tables in the API

---

app/javascript/components/widgets/widgets/people/forestry-employment/selectors.js

Added a simple factor to the widget that was missing during one case.
After the PR the result for Guatemala should be:
Countries with gender data should be unaffected.

Forestry employment widget: missing multiplication factor

---

app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js

Ensures all widgets that make a statement like: *"The top 10 regions represent X% of total"*, sort data before calculating the percentage.
- Also removes some unused code
- and adds some better/clearer naming conventions

[Country Dashboards] Ranking statement calculation fix

---

app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
app/assets/javascripts/map/services/AnalysisNewService.js

The hottest, dirtiest fix you'll see this year - _guaranteed!_
- Fixes loss for country/adm shapes, custom shapes, wdpa, tcl - you name it!
- Allows multiple layers to be analysed simultaneously in the above cases
**Note**: one issue remains...
When analysing GLAD, the api currently only returns 2000 extent, so switching between 2000 & 2010 is broken. Requires multiple fetches in this instance... but thats for another PR.

[ANALYSIS]: Fixes loss & multiple analyses

---

app/javascript/components/widgets/widgets/climate/emissions-deforestation/initial-state.js
app/javascript/components/widgets/widgets/climate/emissions-deforestation/selectors.js
app/javascript/data/forest-types.json
app/javascript/data/land-categories.json

Emissions from Charlies table comes back in Mg/ha (i.e. tonnes/ha). This value, converted to CO2 should be the default for the emissions widget. This PR makes it default, and also calculates it in a different way (summing the annual values in Mg/ha first, and then converting) so that the values are consistent with the values quoted in the loss widget too.
Emissions loss value should match value quoted in TC loss widget.
CO2 should be default choice.

update to emissions widget defaults and calculation order

---

app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js

Fires analysis service (map --> draw shape) is currently giving back loss instead of active fires, this PR returns the correct value.

fixed bug on active fires analysis service

---

app/assets/javascripts/map/views/layers/GladLayer.js

We were using the band3 incorrect on the encoded tiles for GLADs. Now we are not.
Additionally I have set staging to use the dynamic tiles from the new endpoint permanently so that charlie can test and we can close this mess.
BONUS: a great feeling of relief.

Fix: glads decoding using band3

---

app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
app/assets/javascripts/map/services/GeostoreService.js

VIIRS was using the ISO shape when analysing adm2 regions.
Please test that this does not break other adm2 analyses (looks good to me so far)

[ANALYSIS] Fix adm2 geostore fetch

---

app/javascript/pages/map/components/menu/menu-selectors.js
app/javascript/providers/datasets-provider/datasets-provider-actions.js
app/javascript/services/analysis.js
app/javascript/services/datasets.js

Extends filtering for datasets in the dataset provider to compare the FEATURE_ENV key against the layers`env` key from the API. This allows us to have staging layers on staging.

check for env key for datasets

---

app/javascript/services/alerts.js

Firstly. Great detective work @blayhem 👏.
Catches errors in `/latest` endpoint responses and replaces with a template of the expected response object.
This object by default sets the latest date to the previous friday (`moment().day(-2)`) in the correct format... friday as this should be the last time the data was updated.

Catch 500s in latest responses

---

app/javascript/pages/dashboards/header/header-reducers.js
app/javascript/pages/dashboards/header/header-selectors.js

Fixes this 👇 
Note missing 'ha' units. The calculation is also off (referencing the wrong value).
Calculation should now be 1.25Mha to match the loss in 2017 in the natural forest loss widget on the Forest Change tab.
This number (..._it lost 1.30M of tree cover..._):
...should match this number (_Natural forest 1.25Mha_):
for Indonesia, Brazil, Malaysia.

Indonesia Header

---

app/javascript/pages/dashboards/header/header-reducers.js
app/javascript/pages/dashboards/header/header-selectors.js

Puts naturalLoss, loss and primaryLoss keys in correct positions.
- loss should be equal to Loss widgets 2017 column
- primaryLoss should be equal to Loss widgets 2017 column with Primary forest selected
- naturalLoss should be equal to 2017 column of natural forest loss widget

Fix header keys for Indonesia

---

app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js

There was one missing piece from the last update, was returning NaN in the plantations loss widget for 2017.
Now fixed, should look like this (with shown natural forest numbers matching):

Update plantationsloss calc

---

app/javascript/components/widgets/widgets/climate/future-carbon-gains/actions.js
app/javascript/components/widgets/widgets/climate/future-carbon-gains/config.js
app/javascript/services/climate.js

Fixed a bug related to mixed content (http resources on a https page) that made this widget to not load any data in the production website. Instead of using climate.globalforestwatch, we are using wri-carto endpoint.

Fixed mixed http/https in climate indicators, now using carto

---

app/javascript/components/widgets/selectors.js
app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
app/javascript/components/widgets/widgets/climate/emissions/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/config.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
app/javascript/components/widgets/widgets/land-use/economic-impact/selectors.js
app/javascript/components/widgets/widgets/land-use/forestry-employment/selectors.js

The ranked gain widget should have access the parent locations (e.g. Acre's parent is Brazil, Brazils is Global etc)
This update the 'getLocationsObject' function to include parent information as well as teh admin level of the selected location.

Fix: Ranked gain widget parent location

---

app/javascript/components/widgets/widgets/forest-change/glad-ranked/config.js

Simply removes the Land category options that are not present in the data since KBA, TCL, AZE are no longer processed for glad.

Removes KBA, TCL etc from ranked glad

---

app/javascript/components/maps/components/menu/components/sections/search/component.jsx

The label for "decimal degrees" option was "decimal degress"; fixed

typo fix for degrees

---

app/javascript/components/scroll-to/scroll-to.js
app/javascript/pages/sgf/section-about/section-about-component.jsx

Anchor links in SGF tab weren't working on page load. Increased to 500 delay and allowed delay props in component.

Fix: increase scroll to speed for sgf about tab

---

app/javascript/components/widgets/widgets/forest-change/fao-deforest/selectors.js
app/javascript/components/widgets/widgets/forest-change/fao-reforest/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-global/config.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-tsc/config.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-tsc/selectors.js
app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js

1. Loss TSC widget: removes 'permanent deforestation'
2. Loss Global widget sentence fix
3. Refactors title logic to use getLocationName not getLocationType (depreciated). Global titles not all begin with `Global`

Update loss widgets text

---

app/javascript/components/widgets/widgets/forest-change/tree-loss-global/config.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/config.js
app/javascript/pages/dashboards/header/header-reducers.js
app/javascript/pages/dashboards/header/header-selectors.js

All daughter locations within indonesia now have the modified sentence which references intact forest and co2 emissions.
Extends this behaviour to any country-specific header sentence - in the future we can now add the ISO  code as a key in the header-config and it will automatically select it if it exists.

Adds parent location check in header sentences

---

app/javascript/components/widgets/components/widget/components/widget-header/selectors.js

Ensures info button forms correct request to `https://production-api.globalforestwatch.org/v1/gfw-metadata/widget_natural_vs_planted`

Fixes broken IDN Tree Cover metadata

---

config/environments/production.rb

Now we have SSL for staging and preproduction we can force SSL on the production env config.

force SSL on all deployed production environments

---

app/javascript/components/widgets/widgets/forest-change/fires-alerts/settings.js

Changed the fires widget to show VIIRS dataset by default, so when the user clicks analysis for regions on the map it will relate to the data layer (i.e. it will show VIIRS on the widget and the layer).

Feature: change default dataset for Fire Alerts widget to VIIRS instead of MODIS

---

app/javascript/components/maps/components/menu/components/sections/search/index.js

Fixed: "Info icons on map search not showing correct things" (toggling modal with metadata info).

Info icons on map search working correctly

---

app/javascript/components/widgets/widgets/forest-change/tree-loss/config.js

Removed the  the "of" between CO2 and emissions: From 2001 to 2017, Mexico lost 3.40Mha of tree cover, equivalent to a 6.4% decrease since 2000, and 209Mt of CO₂ ~~of~~ emissions."

Small change to dynamic sentence

---

app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings-component.js
app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings.js
app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-actions.js
app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-selectors.js
app/javascript/services/recent-imagery.js

This PR's objective is to fix several bugs related to recent imagery. Sometimes the fetch fails and both the error message and the previous tiles appeared, which is now fixed.
TODO: fix endless fetch loop that happens sometimes when switching from Vegetation health to Natural color, clear previous tiles.

Fix: recent imagery infinite fetching thumbs

---

app/javascript/components/analysis/components/show-analysis/selectors.js
app/javascript/components/analysis/selectors.js
app/javascript/components/widgets/selectors.js
app/javascript/utils/format.js

This PR hides TSC widget in `adm1` and `adm2` level analysis, also moving `locationLevelToStr` method to utils, as it's being used in different files.

move locationLevelToStr to utils, fixed TSC for geostores and high zoom levels

---

app/javascript/components/header/components/nav-alt/component.jsx
app/javascript/components/header/components/nav-alt/styles.scss

This PR addresses a ~~bug~~ feature related to Firefox in Windows where the menu opened on mobile view creating 2 scroll bars that pushed the menu content to the left. We added a class to the body that is applied when the menu opens, then removed when it's closed. This class controls the overflow.

Added custom class to avoid body scroll when header menu is open

---

app/javascript/components/basemaps/component.jsx
app/javascript/components/basemaps/selectors.js
app/javascript/components/basemaps/styles.scss

When retrieving planet basemap data, the default selected value caused a conflict with the empty data retrieved, causing the basemap settings menu to crash. Added a couple of checks to avoid this.

Fixed empty values that crashed the settings menu

---

app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js

Solves a problem with % values being 0 in "Location of deforestation alerts" widget.

Fixed percentage values for this widget

---

app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js

On the ranked GLAD widget, the percentages displayed for each subregion now displays the percentage of counts _relative to the total number_ in the super-region.

Change percent from area to counts

---

README.md

Hi team, I was looking at your project on https://explore.ovio.org and noticed that your preview image had a broken link.
I simply updated the link to target https://github.com/Vizzuality/gfw/blob/master/app/assets/images/preview.png.
Hope that works!

Fix link to preview image in README

---

app/javascript/components/widgets/components/widget/components/widget-footer/selectors.js
app/javascript/components/widgets/components/widget/selectors.js
app/javascript/components/widgets/widgets/climate/emissions-deforestation/selectors.js
app/javascript/components/widgets/widgets/forest-change/fires-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js

Related [thread](https://basecamp.com/3063126/projects/10727890/todos/404782334).
This PR fixes the capitalization of Key Biodiversity Areas in the dashboard widgets. However, because it's the only indicator that is kept with the original capitalization (see thread), I had to add a lot of "special cases" in the widget configs, and there's probably a better way of doing this.

Fixed lower caps for Key Biodiversity Areas indicator

---

app/javascript/components/map/components/legend/component.jsx

Moved the hover statement sentence a bit up. I'm creating this PR for the record, but I'm pushing this as hotfix as it's a small non-breaking change.

Moved statement up

---

app/javascript/components/forms/contact/component.jsx
app/javascript/components/forms/contact/config.js
app/javascript/components/forms/profile/component.jsx

Removed the ability to opt-in to user testing from both the Contact Us form and MyGFW Profile.

Removed user opt-in for testing

---

app/javascript/components/forms/login/actions.js

This PR fixes resetting password for MyGFW.
It sends the email to the API and the rest is handled there.
The issue was that the `resetUserPassword` was sending an empty string (incorrect destructuring issue)
- Go to My GFW tab
- Click Forgot Password
- Put your email
- Hit OK
- Check that you got the email or check in the Network tab that you're sending the **Request Payload**

Fix reset password for MyGFW

---

app/javascript/components/widgets/forest-change/tree-loss-tsc/index.js

Extension of the endyear for the TCL by driver dashboard to 2018 using the new table id (table id on staging d833af84-c790-4bbc-b081-6d27cb08c18d/ and table id on production 7610bcaf-4f3c-473e-8fa1-4625c92f14b4).

extend endyear to 2018 data for tcl by driver

---

app/javascript/components/analysis/components/show-analysis/selectors.js
app/javascript/components/analysis/selectors.js
app/javascript/components/widget/components/widget-header/component.jsx
app/javascript/components/widget/components/widget-header/components/widget-download-button/component.jsx
app/javascript/components/widget/components/widget-header/components/widget-download-button/styles.scss

Updated the widget header component to show the download button _also_ for widgets in the map legend so everybody can download data for the widgets directly from there. This allows downloads for GLAD and VIIRS datasets from the map, and more.

[Fix, not urgent] Fixed downloads for GLAD and VIIRS alerts on the map legend

---

app/javascript/components/widget/components/widget-header/components/widget-download-button/component.jsx
app/javascript/components/widget/components/widget-header/components/widget-download-button/index.js
app/javascript/components/widget/components/widget-header/components/widget-download-button/selectors.js
app/javascript/components/widgets/forest-change/glad-alerts/index.js
app/javascript/components/widgets/forest-change/glad-alerts/selectors.js

This PR adds a fix for the custom shape downloads for glad alerts widgets on the map.
It uses `downloadUrls.csv` property from /glad-alerts API request result to download the file:
The `Content-type` (coming from the BE)  of the `downloadUrls.csv` url is incorrect so as a workaround we change the tooltip text for the user to know to add an extension to the filename.
- Go to the map
- Activate `Deforestation alerts (GLAD)` layer
- Go to `Analysis` tab
- Choose the option to draw a shape
- Draw a shape in Brazil for example
- Click on the download icon to download the csv data
- Notice that for other types of analysis (not custom shapes) the download files are different (zip) as it uses a different logic.

Fix custom shape downloads for glads in the map widgets

---

app/javascript/components/widgets/climate/emissions-deforestation/index.js
app/javascript/components/widgets/forest-change/fires/index.js
app/javascript/components/widgets/forest-change/glad-alerts/index.js
app/javascript/components/widgets/forest-change/glads/index.js
app/javascript/components/widgets/forest-change/tree-cover-gain-simple/index.js
app/javascript/components/widgets/forest-change/tree-loss/index.js
app/javascript/components/widgets/land-cover/tree-cover/index.js
app/javascript/components/widgets/utils/helpers.js
app/javascript/services/analysis.js

This PR adds a decision tree that if the area is saved, the data for the widgets should be fetched from the precomputed tables endpoints or else it would be fetched from the custom endpoints (`umd-loss-gain`, `glad-alerts`, `viirs-active-fires`)
Effectively, the decision tree impacts these widgets on the dashboard:
- Loss, Gain, Extent and Glad alerts
Additionally, Fires widget and Glad last 7 days widget are disabled on the dashboards
- Go to My GFW
- Choose one of the saved custom shapes
- You will be redirected to the dashboard and can check there what endpoints are hit (filter by `?sql=`). If the area was saved correctly, the widgets should be populated with data from the precomputed tables.

Dashboard - use precomputed links for saved areas to populate widgets

---

app/javascript/components/widgets/forest-change/tree-cover-gain-simple/index.js
app/javascript/services/analysis-cached.js

Context - when a custom AOI with `status=true` is created, the Gain widget was failing to return data from the table.
Updates sql. Fixes issue with lodash/get. For some reason this isn't functioning and I'm unable to get it working with those keys.
Comments are left in (in case you can get it working). Please remove.

Fix aoi gain data parsing

---

app/javascript/components/map-geostore/component.jsx
app/javascript/components/map/selectors.js

This PR attempts to fix any issues that came up from merging Layer Manager v3 changes with the AOIs.
* It adds a guard for checking if `layerConfig` exists
* It fixes the AOI cards small map previews by adding a `type` prop to `<Layer />` component and adjusting the specification for aoi cards basemaps (`tiles` instead of `url`)
**Testing** 
Go to My GFW profile and go through the AOIs workflow.

Fix AOI cards for l mv3

---

app/javascript/components/widget/components/widget-header/components/widget-download-button/component.jsx
app/javascript/components/widgets/forest-change/glads/index.js
app/javascript/components/widgets/forest-change/tree-loss-tsc/index.js
app/javascript/data/layers-datasets.js

This PR removes two widgets from two views in the app, as requested:
- Loss By Driver widget from Custom AOI dashboards.
- Old GLAD widget (7 day widget) from the map analysis.

Removed TSC from aois and GLAD week from map

---

app/javascript/components/forms/components/select/component.jsx

Change the sublabel text in select component with `multiselect` option to a more accurate one. (For Mac users it's not the `control` button but the `command`)

Change sublabel text in the multi select component

---

app/javascript/components/forms/login/component.jsx
app/javascript/components/modals/area-of-interest/component.jsx

This PR fixes two issues:
* When logging in via **social** accounts on the saving an area flow - preserve the query params from the URL - keep the AOI modal open
* When logging in via typing login and password don't close the AOI model
Relevant Basecamp issue: https://basecamp.com/3063126/projects/10727890/todos/415045078

Fix AOI modal opening flow after logging in on the map to save an area

---

app/javascript/components/forms/profile/actions.js
app/javascript/components/forms/profile/index.js
app/javascript/components/modals/area-of-interest/component.jsx

We had some nice 'Other: undefined' values on the form, fixed those. Also forced the user form to open when we don't have data that is required only to save an area (added extra checks).

Fixed undefined 'Other' field values, added required fields to the saveAOI modal.

---

app/javascript/pages/about/section-projects/section-projects-component.jsx

Either we use `extLink=globalforestwatch.org/howto`, or we use a link within the app (Ended up using the 2nd approach).

Fixed howto link in about page

---

app/javascript/data/land-categories.json

Updates dashboard to use `is__landmark` key in queries In line with the new LandMark vector layer on staging.
Also, pulls the new layer for the dashboard map.
Awaiting feedback from LandMark, but can be pushed to staging in the meantime.
Affects all tables, please break me.

Update land rights config for dashboards

---

app/javascript/components/forms/profile/component.jsx
app/javascript/components/modals/area-of-interest/component.jsx

This fixes a bug where someone clicked "edit area" from the MyGFW page, the first page they saw is "my profile" page (see staging).
The reason behind this is that we didn't check for sub-sectors other than "Other: <something>". This caused the profile form to be considered "not filled" all the time if you selected another sub-sector.
To test:
1. Go to staging/my-gfw, try to update your profile with a sub-sector other than "Other", then try to edit an area.
2. Go to the branch deployment and try the same flow.
3. Also check the save AOI modal in the map.

Added check for subsector in save AOI modal

---

app/javascript/components/analysis/components/show-analysis/component.jsx

I made a PR to change this from "Save this area to create a dashboard with a more in-depth analysis and receive email alerts about forest cover change" to "Save this area to receive email alerts about forest cover change. We are currently developing the ability to create dashboards for custom areas" text on March 24. Now that AOIs are launched, it's time to change it back.

Updating language to reflect AOI launch

---

app/javascript/components/charts/components/chart-tooltip/chart-tooltip-component.js
app/javascript/components/widgets/forest-change/fires-alerts-cumulative/index.js
app/javascript/components/widgets/forest-change/fires-alerts-cumulative/selectors.js
app/javascript/components/widgets/manifest.js
app/javascript/components/widgets/utils/data.js

Cumulative fires chart

---

app/javascript/components/forms/validations.js
app/javascript/pages/about/section-projects/section-projects-component.jsx

- Fixed an issue (probably related to the router?) in which the /howto link in the About page showed an error. Changed this link into an external link (opening a new tab) to gfw.org/howto.
- Changed the email validator to allow up to 10 character top level domains. Longest TLD every is way longer, but this should be enough for now...

[FIX] Fixed /howto extLink in about page and TLD length in contact-us form.

---

app/javascript/components/charts/lollipop-chart/component.jsx
app/javascript/components/widget/components/widget-lollipop/component.jsx
app/javascript/components/widgets/fires/fires-ranked/index.js
app/javascript/components/widgets/fires/fires-ranked/selectors.js

Solves issue num. 8 of the Fire ranking widget (feedback doc): adding a legend to explain what the colours correspond to. Uses the chart legend component to draw a legend on top of the lollipop chart, as it's shown on the designs.

Added chart legend to lollipop widget

---

app/javascript/components/charts/components/chart-tooltip/component.jsx
app/javascript/components/charts/composed-chart/component.jsx
app/javascript/components/widgets/fires/fires-alerts-cumulative/selectors.js

Fixes issue num. 7 in the Cumulative Fires Widget: "Order tooltip by fire count, not chronologically".
I propose adding a sortBy=value key in the tooltip config of the widget, that is evaluated in the chart tooltip. The data is re-sorted every time the `payload` prop changes, as it needs to reevaluate the order.

Fix/order tooltip by values using a sortBy tooltip config key.

---

app/javascript/components/widgets/forest-change/glad-alerts/index.js
app/javascript/components/widgets/utils/config.js
app/javascript/data/land-categories.js
app/javascript/utils/format.js

Adds a general case check for all indicators.
If `upperCase =True` in the forestType or landCategory, then dynamic sentence preserves the original string (no lower casing).
Also, adds `dataType='glad'` in order to remove gain discalimer from the widget.

Add uppercase key to land categories

---

app/javascript/components/charts/lollipop-chart/component.jsx
app/javascript/data/units.json

Fixing rounding on small numbers (percentages) for the lollipop widget.

Fix / unitless pct lollipops

---

app/javascript/components/widgets/fires/fires-alerts-historical/selectors.js

This removes duplicated ticks on the xAxis as previously there were several ticks with the same month and year (daily resolution).

Added days to the xAxis ticks on the firesAlertsHistorical widget.

---

app/javascript/components/widgets/fires/fires-alerts-cumulative/index.js
app/javascript/components/widgets/fires/fires-alerts/index.js

Cumulative fires moves down 1 place to give the no.1 spot to fires weekly.

Fires weekly to the top

---

app/javascript/components/widgets/fires/fires-alerts-cumulative/selectors.js
app/javascript/components/widgets/fires/fires-alerts/selectors.js

Makes compare years tooltip dates consistent to the default year in both weekly fires widgets

Update tooltips for consitent date formatting

---

components/widgets/fires/fires-ranked/selectors.js
services/analysis-cached.js

Updates ranked fires widget's sql and selectors to account for user selected time periods that wrap around a calendar year (e.g. Nov 2019 to Feb 2020)

Account for period that overlaps years

---

components/widgets/fires/fires-alerts/selectors.js

Hotfix! The fire season statement can be incorrect if it wraps around a year. Now orders by descending years to always get the most recent.

Change year order to capture seasons across year

---

static/land-categories.js

- Sets AZE to `preserveString: true` on dashboards, capitalising  the sentence.
- Changes `Managed Forests` to `Logging concessions`
AZE `preserveString: true`:
- Go to Brazil or Indonesia dashboards
- Open settings on tree loss (or any) widget
- Open `Land Categories` dropdown
- Select `Alliance for Zero Extinction...`
- `Alliance for Zero Extinction...` should appear in the widget  sentence, capitalised.
`Managed Forests` to `Logging concessions`:
- Go to Brazil or Indonesia dashboards
- Open settings on tree loss (or any) widget
- Open `Land Categories` dropdown
- There should be a `Logging concessions` option
- There should not be a `Managed Forests` option

Preserve AZE string

---

components/widget/components/widget-header/component.jsx
components/widget/components/widget-header/components/widget-download-button/component.jsx
components/widget/components/widget-header/components/widget-download-button/styles.scss
components/widgets/forest-change/glad-alerts/index.js
components/widgets/forest-change/glad-ranked/index.js
components/widgets/utils/config.js

This pr disables download button for glad, and adds a disclamer to widget/layer
Notion: https://www.notion.so/9dd860f5dfd64475b92f4a3f79f0ff37?v=2098a476c4fa407981718cb4eafad507&p=4831737872e64d7793cebb1fea1f354a

fix: disable download for glad

---

components/url/index.js

This pr fixes a bug when you enter the map without defining a location, for example these scenarios: 
1. Using the blog/help-center and pressing map link within the header, redirects to /map/ without location
2. Using the browser url field and entering gfw.com/map only. 
3. Using any external link that does not specify location for entering the map
Initially the solution was to update the gfw header component and append `global` to the main navigation, but it still would break entering from an url. As its quite logical to just enter /map without global, its better to catch this scenario when rendering the map page. 
Locally you will see this error: https://github.com/zeit/next.js/blob/master/errors/incompatible-href-as.md and map properties wont update when panning the map, as its in a …

allow to enter map without location, and default to global

---

providers/datasets-provider/config.js

Adds a generic shader static remapping function to be used with any rgb tile layer.
Used to remove blurred edges from rgb tile cache layers at the (small) expense of performance.

Adds static decode/encode remapping

---

layouts/map/components/map-controls/component.jsx
layouts/map/components/map-controls/styles.scss
layouts/map/styles.scss

This pr adds search button to mobile map controls as seen here: https://projects.invisionapp.com/d/main?origin=v7#/console/17055239/353550704/preview?scrollOffset=533
[notion](https://www.notion.so/Bugs-47e054fc0652498d9fb555ca2070c238?p=a2618b6af8824de7842d5060430873cb)
Changes: 
1. Design increased btn size from 38 -> 40 px for bigger touch control on mobile navigation
2. new direction for mobile screen (vertical) and split RSI from search + share
3. Increased icon size for easier readability 
- Ensure search works as expected + resize window to make sure "desktop" menu does not break with these css changes.

add mobile search button

---

components/widgets/forest-change/tree-loss-tsc/index.js

2018 --> 2019
Production tables need testing.

Bump TCL by Driver year

---

components/ui/map/component.jsx

Due to this.map being called as a ref and overwritten in the map ui component there was an error appearing to react ref setters. This fixes this.

Fix/set mapRef in map ui component correctly

---

components/map/basemaps.js
pages/api/planet-tiles/[...params].js

Add api route for proxy to planet tiles to hide API key in requests.
- Go to the map and turn on planet basemaps, make sure the tiles load.
- Check the network for planet responses and check for API key

Feature/planet API proxy

---

components/widgets/forest-change/tree-loss-tsc/selectors.js

Implements correct sorting of drivers in the tooltip of the Deforestation by Drivers Widget
Old:
New:

Fix tooltip order

---

data/land-categories.js

Simple hotfix to rename `Indonesia peat lands` to `Indonesia & Malaysia peat lands` on the dashboard widget's Land Categories option.

Rename peat lands

---

providers/datasets-provider/config.js
providers/latest-provider/actions.js
services/stats-latest-decoder.js

Adds RADD Alerts specific `latestDate` parsing for the `endDate` param as well as the raster decode function `RADDsCoverage` to parse the RADD Alerts geographic coverage layer.
The `stats` endpoint for the RADD alerts dataset returns statistics (`min`, `max`, `histogram`) for the _encoded_ alert dates. Example response:
```
"data": {
"bands": [
{
"min": 21462,
"max": 32199,
"mean": 31221.31386,
"histogram": {
"bin_count": 8638,
"min": 21440.947059,
"max": 32220.052941,
"value_count": [ 1166, 89, 0 , 1455, ...
```
Statistics are returned in the format `abbbb` with:
- `a` = _Confidence level_ where: 3 is 'high confidence', 2 is 'nominal', 1 is 'low'
- `bbbb` = number of days since 2014-12-31.
Since stats are returned in their encoded form, the `max` value is **always high confidence** …

Decode latest date from stats response

---

components/widgets/forest-change/tree-loss-pct/selectors.js
components/widgets/manifest.js

Fixing primary forest loss widget.
Three climate widgets removed;
- Delete New York Declaration on Forests disturbance tracker widget 2 comments AJ Pain
- Delete Biomass loss emissions in natural forest vs. plantations widget 3 comments AJ Pain
- Delete historical emissions widget 2 comments AJ Pain
Data isn't filtering, but fix has cascading effects that need to be addressed
- Go to widget [url](globalforestwatch.org/embed/widget/treeLossPct/country/BRA?treeLossPct=eyJ0aHJlc2hvbGQiOjUwLCJzdGFydFllYXIiOjIwMDMsImhpZ2hsaWdodGVkIjpmYWxzZX0=), select date range, check loss and percentage and parameters change

fixing primary forest loss widget

---

components/map-menu/sections.js

Changes Climate tab sub-section title from `Carbon Emissions` to `Climate Flux`
The Dataset Vocabularies remain `categoryTab: carbonEmissions` we will have to change this in the future, but for now let's keep this update simple.

Update title to flux

---

components/basemaps/index.js
components/basemaps/planet-menu/component.jsx
components/basemaps/planet-menu/selectors.js
components/basemaps/selectors.js
components/map/selectors.js

Fix multiple issue with planet basemaps. 
1. Use dates from basemap response instead of parsing title
2. Filter basemaps based on selected image type
BC: https://basecamp.com/3063126/projects/10728552/todos/433532321
- Ensure dates + basemap corresponds to the correct image type
- Ensure basemaps render, or make sure this is not an issue on our side 
- Check interactivity and lets make sure we are updating the basemaps dynamically correct
- Make sure that when you land on planet basemap selected you get results 
- Make sure that when you toggle between image types that basemap renders correctly
- Ensure date ranges within the basemap options are correct and all of them works as expected (for both image types)

fix planet basemap date/image type serialisation

---

utils/hotjar.js

js trigger sent to hotjar needs to be a specific format to work, otherwise the survey wont show.

fix hotjar surver event

---

components/basemaps/selectors.js

This pr fixes an issue where dates are handled as local time, instead of UTC.
- Change timezone on your computer to US for example, check on prod where the dates will be wrong (nov 2020 instead of dec 2020), check this branch and make sure we get december.

utc date fix for planet basemap ranges

---

components/widgets/fires/fires-alerts/selectors.js

Fixes issue detecting fire season start date (date at which the mean line passes full-width-half-maximum) in locations with southern hemisphere-like seasonality.
- Go to Benin, Australia, Indonesia, Brazil
- Check that the dynamic sentence states that the fire season begins in the appropriate month.

Fix seasonStartDate issue

---

providers/latest-provider/actions.js

Adds a check for radd latest date. If in the future, falls back to `defaultDate`.
BONUS - implements new code that prioritises using the `content_date` key from the metadata in `https://data-api.globalforestwatch.org/dataset/gfw_radd_alerts/latest` 
- go to prod
- activate radd
- end date is currently in the future.
- with this fix it should default to today - 7 days

Fall back to default date if latest is in the future

---

components/ui/datepicker/datepicker-header/component.jsx

Datepickers when for example a US user uses GFW, we get out-of-bounds months, December twice. This is fixed by formating UTC in a normalized format so it gets parsed as local time, not UTC.
https://basecamp.com/3063126/projects/10728552/todos/434995459
- Change your timezone to Americas on your computer
- go to: /map/?map=eyJkYXRhc2V0cyI6W3siZGF0YXNldCI6ImRlZm9yZXN0YXRpb24tYWxlcnRzLXRlcnJhLWkiLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJsYXllcnMiOlsiZGVmb3Jlc3RhdGlvbi1hbGVydHMtdGVycmEtaSJdfSx7ImRhdGFzZXQiOiJwb2xpdGljYWwtYm91bmRhcmllcyIsImxheWVycyI6WyJkaXNwdXRlZC1wb2xpdGljYWwtYm91bmRhcmllcyIsInBvbGl0aWNhbC1ib3VuZGFyaWVzIl0sIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9XX0%3D and switch year, make sure you don't get December twice. Test on production the same URL to re produce the issue solved here

fix datepickers timezone issue

---

layouts/embed/widget/trase-embed-styles.scss

On the [Trase integration](https://trase.earth/profiles) we had a problem with two scrollbars on the widget. It could only be solved by changing these styles inside the GFW application.
We will need this to be deployed to staging/production to test it 😕

Make overflow visible for trase widget

---

components/charts/lollipop-chart/component.jsx
components/widgets/fires/fires-alerts-cumulative/index.js
components/widgets/fires/fires-alerts-historical-old/index.js
components/widgets/fires/fires-alerts-historical/index.js
components/widgets/fires/fires-alerts/index.js
components/widgets/fires/fires-ranked/index.js
components/widgets/fires/fires-ranked/selectors.js
components/widgets/fires/fires-within/index.js
services/analysis-cached.js

For fires widgets, changes default forest type label to `All land cover` (since fires needn't be _within_ forest)

Tree cover to land cover

---

components/map/components/legend/component.jsx
components/map/components/legend/components/legend-item-type-choropleth/index.js
components/map/components/legend/components/legend-item-type-choropleth/styles.scss
components/map/components/legend/components/legend-item-type-gradient/index.js
components/map/components/legend/components/legend-item-type-gradient/styles.scss

This PR adds a new custom component in map legend. It allows to show "labels" below ticks in legend type gradient and choropleth

custom legend type gradient added

---

.github/workflows/ci-deployment.yml
services/analysis-cached.js

This pr fixes the issue reported [here](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=11&projectKey=GFW&modal=detail&selectedIssue=GFW-92)
The problem was that our "isNumber" check within the `where` query selection was not accurate enough, as some query parameters passed from external sources will be parsed as `strings` so the previous check `typeof` will not work. What I'm doing now is checking if the string does not return `NaN`. Then we can assume that a current parameter is a number. 
In this case, `adm1` was returned as a string, so when performing the query in the API we get this error: `Operator [=] cannot work with [INTEGER, STRING].`. This fix will ensure that any comparison we sent to the API should be parsed as a number is. 
Check the link you posted within …

FIX GFW-92

---

services/analysis-cached.js

WDPA ID values are strings in the new tables - ensures sql wraps them in `'`.
MAP:  Go to map, activate wdpa, select and analyse... Should return an analysis for loss, gain, extent.
DASHBOARD: Go to `localhost.../dashboards/aoi/5ede8debd970e4001bbef545`, widgets should return for loss gain and extent
This section of `analysis-cached.js` where this logic is applied should by config based and not have complex logic when we know the type based on the table keys already. Tests can then verify that these keys are as expected.

Set wdpa_protected_area__id isNumeric to false

---

layouts/embed/widget/trase-embed-styles.scss

This is a little PR to remove the internal scrollbar on the embedded chart only on Trase. We removed the outer scroll but the internal one also needed to go
Before:
After:
This is not urgent. Just notify me when its deployed
- It should be tested on Trase Profiles country pages after deploy

Remove second nav bar from chart

---

components/widget/components/widget-header/components/widget-download-button/component.jsx
components/widgets/climate/emissions-deforestation-drivers/index.js
components/widgets/climate/emissions-deforestation-drivers/selectors.js
components/widgets/climate/emissions-deforestation/index.js
components/widgets/climate/emissions-deforestation/selectors.js
components/widgets/forest-change/tree-loss-plantations/index.js
components/widgets/forest-change/tree-loss/index.js
components/widgets/forest-change/tree-loss/selectors.js
components/widgets/manifest.js
components/widgets/options.js
cypress/integration/widget.js
data/colors.json
data/datasets.js
data/emission-gases.json
data/emission-types.json
data/layers.js
providers/geodescriber-provider/selectors.js
services/analysis-cached.js

Updates to new biomass loss keys from the postgres tables, updating the existing Biomass Loss widget and adding a new Loss by Driver widget.
More to follow...

Update biomass loss widget, add biomass loss by driver

---

components/widgets/fires/fires-ranked/selectors.js

fix divide by 0 issue on top region perc 
globalforestwatch.org/dashboards/country/IDN/9/?category=fires&location=WyJjb3VudHJ5IiwiSUROIiwiOSJd&map=eyJjZW50ZXIiOnsibGF0IjotNi44Njk1NTg0MjAwODg4NzIsImxuZyI6MTA3LjYwMjE0OTk5OTk4MTQ1fSwiem9vbSI6Ni44MjA2MTczNzUxNTE0NDcsImNhbkJvdW5kIjpmYWxzZSwiZGF0YXNldHMiOlt7ImRhdGFzZXQiOiJwb2xpdGljYWwtYm91bmRhcmllcyIsImxheWVycyI6WyJkaXNwdXRlZC1wb2xpdGljYWwtYm91bmRhcmllcyIsInBvbGl0aWNhbC1ib3VuZGFyaWVzIl0sImJvdW5kYXJ5Ijp0cnVlLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlfSx7ImRhdGFzZXQiOiJmaXJlLWFsZXJ0cy12aWlycyIsImxheWVycyI6WyJmaXJlLWFsZXJ0cy12aWlycyJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJ0aW1lbGluZVBhcmFtcyI6eyJzdGFydERhdGVBYnNvbHV0ZSI6IjIwMjEtMDItMTciLCJlbmREYXRlQWJzb2x1dGUiOiIyMDIxLTA1LTE4Iiwic3RhcnREYXRlIjoiMjAyMS0wMi0xNyIsImVuZERhdGUiOiIyMDIxLTA1LTE4IiwidHJpb …

fix top region percent divide by 0 check

---

services/analysis-cached.js

This pr fixes an issue where we instead of reading global params, end up reading adm0, which in return gives us the wrong dataset `adm1` as target from `typeByGrouped`.

fix global check

---

components/widgets/component.jsx
data/dashboard-summary-sentence.js
layouts/dashboards/component.jsx
layouts/dashboards/components/global-sentence/component.jsx
layouts/dashboards/components/global-sentence/index.js
layouts/dashboards/components/global-sentence/selectors.js
layouts/dashboards/components/global-sentence/styles.scss

This pr adds a global summary header by category. It acts as a widget but is not really a widget.
- Check each admin level on dashboard and make sure we are displaying the correct sentence
- As depending on category; We need to verify the correct sentence is shown for its category.
- Check that sentences gets feeded the correct properties for country + admin variables. 
- Ensure app does not crash in general
- Ensure widget looks good.

add global dashboard sentence

---

components/widgets/land-cover/intact-tree-cover/index.js
components/widgets/land-cover/tree-cover/index.js

Fix global tree cover widgets by summing over iso keys in data (previously the logic only selected the first element). Widgets effected:
- `treeCover`
- `intactTreeCover`

Sum over isos

---

components/widgets/fires/fires-ranked/selectors.js
services/analysis-cached.js
services/sentences.js

At global level, ignore filtering. Also adds some QoL improvements to the widget.
WARNING: when embedding the widget using `http://localhost:3000/embed/widget/firesRanked/global` the `getLocationsMeta` selector seems not to have access to data (returns `{}`)

FIx global fires Ranked widget

---

components/widgets/fires/burned-area-cumulative/index.js
components/widgets/fires/burned-area-cumulative/selectors.js
components/widgets/fires/burned-area-ranked/index.js
components/widgets/fires/burned-area-ranked/selectors.js
components/widgets/fires/burned-area/index.js
components/widgets/fires/burned-area/selectors.js
components/widgets/fires/fire-alerts-simple/index.js
components/widgets/fires/fires-alerts-historical-weekly/index.js
components/widgets/manifest.js
data/forest-types.js

Addresses feedback for Fires Widgets currently in develop branch.
- Adds whitelist to fires datasets in widgets not currently using burned areas (`firesHistorical`, `firesAlertsSimple`)
- Fixes intact forest issues (adds burned areas datasets
- Some cleaning of code

Final touches to burned areas widgets

---

components/widgets/fires/burned-area/selectors.js
components/widgets/fires/fires-alerts/selectors.js

When selecting a compare year in the fires alert widgets, if the current year had a week 53 whilst the comparison did not - the chart would show a null datapoint (missing point)
e.g. [Australia 2019](https://preproduction.globalforestwatch.org/dashboards/country/AUS/?category=fires&fireAlertStats=eyJjb21wYXJlWWVhciI6MjAxOX0%3D&location=WyJjb3VudHJ5IiwiQVVTIl0%3D&map=eyJjZW50ZXIiOnsibGF0IjotMjAuNjMyNzk3NDg3NTYyODA0LCJsbmciOjEzNi4wMTM4NDczNTAwNTUwN30sImNhbkJvdW5kIjpmYWxzZSwiZGF0YXNldHMiOlt7ImRhdGFzZXQiOiJwb2xpdGljYWwtYm91bmRhcmllcyIsImxheWVycyI6WyJkaXNwdXRlZC1wb2xpdGljYWwtYm91bmRhcmllcyIsInBvbGl0aWNhbC1ib3VuZGFyaWVzIl0sImJvdW5kYXJ5Ijp0cnVlLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlfSx7ImRhdGFzZXQiOiJmaXJlLWFsZXJ0cy12aWlycyIsImxheWVycyI6WyJmaXJlLWFsZXJ0cy12aWlycyJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR …

Fix missing week-53 when comparing years

---

components/widget/components/widget-header/component.jsx
components/widget/components/widget-header/components/widget-download-button/component.jsx
components/widgets/forest-change/tree-cover-gain-simple/index.js
components/widgets/selectors.js

Brings back download button for map analysis results. There are 4 contexts:
1. **On custom shape Map analysis**: show button, download disabled, prompt to save as AoI  (shape is not yet saved)
2. **In newly saved custom AoI dashboards:** show button, download disabled, prompt `Download unavailable` (shape saved but is` status='pending'` for processed data)
3. **In saved custom AoI dashboards**: show button, allow download (shape saved and processed, `status='saved'`)  
4. **All other dashboards (Coountry, WDPA)**: allow download as data tables exist

Unhide download button for geostore analysis on map

---

components/analysis/components/show-analysis/styles.scss
components/widgets/climate/carbon-flux/index.js
components/widgets/climate/emissions-deforestation/index.js
data/datasets.js
data/layers.js
services/analysis-cached.js

Adds Carbon Flux Widget _on the fly_ (OTF) analysis for custom shapes on the map.
*Carbon Flux*
*Carbon Emissions*
Open map, open `Climate` tab, select a layer in the  `CARBON FLUX` sub-section, create custom analysis by drawing an area.
Analysis functions in `analysis-cached.js` using OTF are slightly different to Postgre table analyses since they use different fields and require `geostore_id` and `geostore_orging` query params.
Additionally, since they hit a different dataset route in the data-api, they require `staticStatement.table` to be passed in the `params`.
As such, these functions are labelled as `<function_name>OTF` to distinguish them from regular (postgres) table analysis functions.

Add flux widget

---

components/basemaps/index.js
components/modals/welcome/index.js
components/satellite-basemaps/component.jsx
components/satellite-basemaps/planet-selectors.js
components/satellite-basemaps/settings/planet-menu/component.jsx
components/satellite-basemaps/settings/planet-menu/selectors.js
pages/api/planet-tiles/[...params].js

We need to implement this in a way that allows it to work when there are Visual basemaps (using the staging key) and when there are not (using the current production key).
The user should always see2 options:
1. Natural Colour (`proc=''` if visual basemaps are available, else `proc='rgb'` and analytic basemap if not)
2. False Colour (NIR) (always `proc='cir' and analytic basemap`)
Adds new code to test new visual basemaps for Planet. Note that is should fix a previous issue where visual basemaps were not returning correctly.
New basemaps have the the following nomenclature:
- `planet_medres_visual_20YY-MM_20YY-MM_mosaic` for 6-monthly mosaics
- `planet_medres_visual_20YY-MM_mosaic` for monthly mosaics
Here 'visual' basemaps need to be sent with the query param `proc=''`, whereas analytic …

Planet Visual and Analytic basemaps

---

components/forms/area-of-interest/actions.js
components/widget/component.jsx
components/widget/components/widget-header/component.jsx
components/widgets/component.jsx
components/widgets/selectors.js

This pr addresses two issues: 
1. When a user saves an area, we need to refresh widgets so we can show "download will be available soon" 
2. Another fix is to check authenticated user, so if a user is logged out, we will simply show download unavailable or log in to save AOI

widget downloads

---

providers/datasets-provider/actions.js
services/datasets.js

Reverts recent update to filter by staging/production layers by `Vocabulary['gfw_env']`

Filter datasets layers by env on first fetch

---

components/analysis/components/show-analysis/selectors.js
layouts/dashboards/components/header/selectors.js

This PR adds a new version of the country spreadsheets that include the new carbon data at s3://gfw2-data/country-pages/country_stats/download/20200331/ 
- Go to a country dashboard and select the download from the header (this should function for global, country and admin regions)
-  Same as for Map and country analysis.
- To test, compare to the current excel downloads in production

adds download version to map and dashborad excel downloads

---

components/widgets/utils/calculations.js

Updates biomass carbon calculation value from 0.5 to 0.47. This should affect to the values shown on this [dashboard](https://gfw.global/3DQa7zL).

updates biomass carbon calculations

---

components/widgets/index.js
components/widgets/reducers.js

Currently on flagship, when switching the active widget, it resets right away as we were syncing the map + resetting the active widget when we were not suppose to.

fix bug making it impossible to switch active widget on dashboards

---

providers/datasets-provider/config.js
services/datasets.js

WIP. 
Updates decoding function for integrated Alerts 8 bits based on the production tiles. Apparently the RGB bands are empty and therefore I have encoded temporally the day. I'm not making use of the intensity as result. 

update decode function for new integrated tiles

---

providers/datasets-provider/config.js

This PR should reactive and just show the high and highest confidence alerts when activating the high conf toggle in integrated deforestation alerts.

add high confidence alerts in the integrated deforestation alerts again

---

providers/datasets-provider/config.js

Change RGB values to individual alerts to match low confidence values of integrated deforestation alerts.

add new RGB values to individual alerts

---

components/map/utils.js
providers/datasets-provider/config.js

Update `getDayRange` function to include a `minDateAbsolut` param for decoding when this param is included in the`layerConfig.decodefuntion`. I've also updated the `layerConfig.decodefuntion` of the following layers to include this min value:
- Integrated alerts layer
- Glad l alerts layer
- Glad s alerts layer
- radd alerts layer
Finally, I've changed the Radd decode function for parsing this minDateAbsolut value from the layer config as min/max dayIndex instead of hardcoding the value directly in the code.

add min absolute date for decoding integrated

---

services/analysis-cached.js

Integrated deforestation alert count dashboard should be pointing at the following tables when glad-l is selected:
- gadm__glad__iso_daily_alerts
- gadm__glad__adm1_daily_alerts
- gadm__glad__adm2_daily_alerts
- geostore__glad__daily_alerts
- wdpa_protected_areas__glad__daily_alerts
For the rest of alerts we should use:
- "gadm__integrated_alerts__iso_daily_alerts",
- "gadm__integrated_alerts__adm1_daily_alerts",
- "gadm__integrated_alerts__adm2_daily_alerts",
The request should look like this one: 
```
https://data-api.globalforestwatch.org/dataset/gadm__glad__iso_daily_alerts/v20211231/query/json?sql=SELECT iso, SUM(alert__count) AS alert__count, SUM(alert_area__ha) AS alert_area__ha, umd_glad_landsat_alerts__confidence FROM data WHERE 
iso = 'BRA' AND umd_glad_landsat_alerts__date >= …
```

fix glad table for integrated dashboard

---

components/map/components/legend/component.jsx
components/widgets/forest-change/glad-alerts-simple/index.js

Similar to widgets, layers now support caution messages if needed. It works a bit different than widgets but you can now define inside a layer config the property "caution" with a text. if present it will show up under the specified layer.

add support for layer cautions

---

data/analysis-datasets.json

Add wdpa datasets for all integrated alerts, glad l, glad s and radd to fix maps protected areas dashboard. 

add wdpa integrated areas datasets

---

components/widgets/forest-change/integrated-deforestation-alerts/index.js

Parse geostoreId for download wdpa integrated alerts data. The query stills failing but the configuration is the same as they are providing in the following excel spreadsheet: https://docs.google.com/spreadsheets/d/16Ui_wfCHQj64qVpvyR_S4fY6HjLzzIxXDYavZsB4hm4/edit#gid=351780396
Current request: https://data-api.globalforestwatch.org/dataset/gfw_integrated_alerts/v20220205/download/csv?geostore_id=23d2f7cc-6b6c-d3e8-fe49-6e97f642448b&geostore_origin=rw&sql=SELECT+latitude%2C+longitude%2C+gfw_integrated_alerts__date%2C+umd_glad_landsat_alerts__confidence%2C+umd_glad_sentinel2_alerts__confidence%2C+wur_radd_alerts__confidence%2C+gfw_integrated_alerts__confidence+FROM+data+WHERE+gfw_integrated_alerts__date+%3E%3D+%272020-08-05%27+AND+gfw_integrated_alerts__date+%3C%3D+%272022-02-05%27
If …

parse geostore id for wdpa download data

---

layouts/dashboards/components/header/selectors.js

This PR modifies the version of the downloadable data in the dashboards page. Bumps from version '20200331' to '2021'
Approved by the client to be deployed, and now the S3 bucket has access permissions

Update dashboards downloadable data version to 2021

---

services/analysis-cached.js

Change geostoreOrigin in download when fetching Integrated Alerts. We need to check if this is a conscious change and if we need to update it also in the analysis part. 

change geostoreOrigin in download

---

providers/datasets-provider/config.js

Add a new decoding function for Tree Cover Loss by Fires, based on the one used for Tree Cover Loss, but adapting the RGB values to match the color of the legend and selector.
- The Tree Cover Loss by Fires layers now shows in the [staging map](https://staging.globalforestwatch.org/map/?map=eyJkYXRhc2V0cyI6W3siZGF0YXNldCI6InRyZWUtY292ZXItbG9zcy1maXJlcyIsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWUsImxheWVycyI6WyJ0cmVlLWNvdmVyLWxvc3MtZmlyZXMiXX0seyJkYXRhc2V0IjoicG9saXRpY2FsLWJvdW5kYXJpZXMiLCJsYXllcnMiOlsiZGlzcHV0ZWQtcG9saXRpY2FsLWJvdW5kYXJpZXMiLCJwb2xpdGljYWwtYm91bmRhcmllcyJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlfSx7ImRhdGFzZXQiOiJ0cmVlLWNvdmVyLWxvc3MiLCJsYXllcnMiOlsidHJlZS1jb3Zlci1sb3NzIl0sIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9XX0%3D&mapMenu=eyJkYXRhc2V0Q2F0ZWdvcnkiOiJmb3Jlc3RDaGFuZ2UifQ%3D …

Add decoding for TCLF

---

providers/datasets-provider/config.js

Adjust TCLF decoding function to show the correct legend color across all zoom levels (avoid color changes based on zoom). Increased intensity at global zoom levels for better visualization (might require further tweaks to reach the desired aspect)
With the new changes, global view should look like this:

Adjust TCLF decoding function

---

pages/privacy-policy.js
pages/terms.js
wrappers/head/component.jsx

This PR adds a `noindex` metatag to the header of the pages when:  
- Not in production, or
- a `noIndex` prop exists  
In addition, and following the suggestion from [here](https://gfw.atlassian.net/browse/FLAG-136?focusedCommentId=14279), `noIndex` was removed for the _Privacy Policy_ and _Terms of Service_ pages. 
https://gfw-staging-pr-4437.herokuapp.com/
[FLAG-136](https://gfw.atlassian.net/browse/FLAG-136)

Add a noindex metatag to staging and preprod environments

---

package.json
wrappers/cookies/component.jsx
wrappers/cookies/styles.scss
yarn.lock

~~https://github.com/Vizzuality/gfw-components/pull/60 (1.8.4) must be published first.~~ - _It has been published_
This PR implements the new cookies design.  
Given that the goal of this implementation is for the Cookies banner not obscure the _"My GFW"_ button on the top left of the map, I paid extra attention to the mobile layout so that the same issue didn't occur on mobile. When on the map pages, on mobile, the cookies banner will show up _above_ the bottom navigation buttons, as to not obscure the _"My GFW"_ buttons. 
[FLAG-484](https://gfw.atlassian.net/browse/FLAG-484)
https://gfw-staging-pr-4436.herokuapp.com/
**Desktop**
**Mobile**

New cookies design

---

data/rewrites-staging.json

This PR fixes the URL rewrites for the staging environment; the URLs currently set up for the help center are pointing to production instead of staging, causing the help center's `robots` `noindex` metatag to not work correctly. 
There are two other accompanying PRs to this one: 
- **Blog**: https://github.com/Vizzuality/gfw-blog/pull/70
- **Help center**: https://github.com/Vizzuality/gfw-help-center/pull/40
These PRs are follow ups to:  
- **Flagship**: https://github.com/Vizzuality/gfw/pull/4437
- **Blog**: https://github.com/Vizzuality/gfw-blog/pull/67
- **Help center**: https://github.com/Vizzuality/gfw-help-center/pull/37
1. `gfw` 
- Visit: https://staging.globalforestwatch.org  
- Open the browser's dev tools   
- Verify that:  
- There is only one `robots` meta tag  
- The tag's …

Fix help center staging urls in the staging environment

---

components/widgets/forest-change/net-change/index.js

This PR removes the second instance of the word _"change"_ in the net change widget's sentences. 
[FLAG-544 - Remove unnecessary “change” word from net change widget](https://gfw.atlassian.net/browse/FLAG-544)

Remove the second instance of the word "change" in the net change widget

---

components/charts/components/pie-chart-legend/component.jsx
components/charts/components/pie-chart-legend/styles.scss
components/charts/pie-chart/component.jsx
components/widget/component.jsx
components/widget/components/widget-pie-chart-legend/component.jsx
components/widget/index.js
components/widgets/actions.js
components/widgets/component.jsx
components/widgets/forest-change/net-change/index.js
components/widgets/forest-change/net-change/selectors.js
components/widgets/reducers.js
components/widgets/selectors.js
layouts/dashboards/component.jsx

This PR indents the net change widgets' pie chart's legend to the right, as well as moving the pie chart a bit to the left, as per open chosen in the JIRA task (see comments). 
- `PieChart` component can now accept styles for the legend and pie chart.  
- `Widget` components are now aware of which page they are being loaded in
(dashboard, analysis, embed)  
- NetChange widget spacing matches the option chosen (only for the dashboard and embed, when displayed in its "big" size)
- Added a new `chartType` setting where we can define custom settings on a per-widget basis  
- Added a new `getChartSettings` to allow us to define settings based on where the widget is being displayed  
[FLAG-545](https://gfw.atlassian.net/browse/FLAG-545)

Indent net change widgets categories further to the right

---

components/widgets/land-cover/tree-cover/index.js

This PR changes the treeCover widget's title from `Tree Cover in {country}` to `Tree Cover by Type in {country}`
[FLAG-553](https://gfw.atlassian.net/browse/FLAG-553)

Change the treeCover widget's title

---

components/charts/components/pie-chart-legend/component.jsx
components/widgets/forest-change/tree-loss-drivers/index.js
components/widgets/forest-change/tree-loss-drivers/selectors.js
data/colors.json
data/tsc-loss-categories.json
services/analysis-cached.js

Merge _just_ prior to #4469.  
We would like to keep this code; the feature is just paused. #4469 takes these changes and reverts them in a single easy to revert commit. 
- Change `treeLossTsc` widget from a bar chart to a pie chart  
- Change the SQL query used to fetch the chart's (as well as CSV download) data  
- Added the ability to specify a pie chart's legend sizing via prop  
- Simplified selectable settings  
- Added the _Unknown_ category  
- Custom alert for Indonesia only  
[FLAG-556](https://gfw.atlassian.net/browse/FLAG-556)

Change drivers widget from a graph to a donut chart

---

services/analysis-cached.js

Updates on the logic to use the column name `umd_tree_cover_density_2000__threshold`  for all cases, including MODIS burned areas (which used the old one, `umd_tree_cover_density__threshold`).
Also, and more importantly, update the logic for the use of this field in comparisons:
When using TCL datasets, should be = `threshold`
For every other dataset, should be >= `threshold`
Can be tested on [this page](https://www.globalforestwatch.org/dashboards/country/BRA/?category=fires&location=WyJjb3VudHJ5IiwiQlJBIl0%3D&map=eyJjZW50ZXIiOnsibGF0IjotMTUuMTI4MzAwNzgxNjEyMTQ5LCJsbmciOi01NC4zOTA1NzkyMjAwMDM2N30sImNhbkJvdW5kIjpmYWxzZSwiZGF0YXNldHMiOlt7ImRhdGFzZXQiOiJwb2xpdGljYWwtYm91bmRhcmllcyIsImxheWVycyI6WyJkaXNwdXRlZC1wb2xpdGljYWwtYm91bmRhcmllcyIsInBvbGl0aWNhbC1ib3VuZGFyaWVzIl0sImJvdW5kYXJ5Ijp0cnVlLCJ …

col names changes tree threshold logic update

---

components/forms/profile/actions.js
providers/mygfw-provider/actions.js
services/user.js

The `user` endpoint of the RW API has been updated to version 2. 
The structure changes a little bit, but I didn't want to change the behaviour of the Forms/Inputs, so I deconstructed the object when fetching and when sending it.
If you know how to clean up the construction of the object before sending to the API, I'd love to learn how! It's a bit... cumbersome.
- Open your profile, and change stuff on the Update Profile modal window.

[FLAG-499] Update GFW User data API to v2

---

package.json
yarn.lock

This PR bumps the `gfw-components` version to the new one with the LCL logo next to WRI's logo in the footer. 
[FLAG-550](https://gfw.atlassian.net/browse/FLAG-550)

Add LCL logo next to WRI logo in the footer

---

server.js

This PR sets up `301` (permanent) redirects from all `non-www` or `http` urls to their `https://www.` versions. 
**In this PR:** 
- Changed the `http` to `https` redirect from a `302` (temporary) to a `301` (permanent)  
- Added a `301` (permanent) redirect from `non-www` to `www` for all pages  
- Improved the `server.js` (custom `express` server file responsible for the redirects) code documentation on everything redirect related  
- The `http` to `https` redirects work on `staging`, `preproduction` and `production` environments.  
This is set up by the `NODE_ENV` environment variable (which is set to `production` in those environments)
- The `non-www` to `www` redirects **only** work on `production`. 
This is because `staging` and `preproduction` don't support `www` urls
This is set up …

Set up http/https and non-www/www redirects

---

components/map/components/popup/component.jsx
components/map/components/popup/components/data-table/styles.scss
components/map/components/popup/styles.scss

There was a bug related to "Alliance for Zero Extinction sites - 2019" pop-up box in which the text would overflow outside the modal window. This has been fixed and with that, the popup was also made a big wider and not ever higher than the viewport and will add scroll if the content doesn't fit.

[FLAG-538] Improve Map Popup size and text handling

---

layouts/dashboards/selectors.js

Silly bug that made Nav links in Dashboard not take admin areas into account, only country.

[FLAG-599] Fix Dashboard Nav links ignoring admin areas

---

components/aoi-card/component.jsx

The MyGFW page is now showing data for 1 week instead of 2 weeks.

[FLAG-512] Change MyGFW to show data for 1 week instead of 2

---

.github/workflows/ci.yml
package.json

Update node to v14 through package.json version bump.
- Check that heroku actually uses node 14 (for Pedro)
- Check that everything works correctly (maps, dashboards, analysis, login to MyGFW, internal links, external links) (for everyone involved)

[FLAG-516] Update to node v14

---

.gitignore
pages/api/data/[...params].js
pages/api/gfw/[...params].js
pages/api/metadata/[...params].js

This PR aims to solve the issue with geostore file uploads failing due to a size limit. 
It looks like the issue is that, in our proxied api implementation, the body of the requests is parsed. In the case of file uploads in particular, this inflates the request body, exceeding the default limit. Since we're only proxying the requests, we don't need to parse anything and the [bodyparser](https://nextjs.org/docs/api-routes/request-helpers#custom-config) can be disabled completely. 
[FLAG-675](https://gfw.atlassian.net/browse/FLAG-675)

Fix issues with file uploads

---

components/map-menu/component.jsx
components/map-menu/index.js

When the user is on mobile, and enables the "Analysis" tab, if they switch to the desktop version the charts/widgets are duplicated. If they are on the base layer selection tab, a blank tab will appear on desktop. In addition, if the user is on the "Legend" tab, upon switching to Desktop the "Analysis" one selected by default. This PR aims to fix these issues. 
Verify that the issues described above no longer happen.

Fix issues where, on the /map, switching from mobile to desktop duplicates the widgets/charts

---

utils/apis.js

This PR updates the Trase API endpoint URL to the current one. 
It looks like the Trase project changed their API endpoint urls a bit over 2 years ago. I was able to [track down the change](https://github.com/Vizzuality/trase/pull/1638/files#diff-4a38e8d9b6b0304b07f9103364921ba3268379d70eeb6c2fd5c540af53687420R3) and obtain the current url. 
1. Visit the dashboard  
2. Choose the country _"Peru"_   
3. Select the _"Land Use"_ category
4. Verify that the _"Commodities flow"_ widget works
_It will be the first one_
[FLAG-458](https://gfw.atlassian.net/browse/FLAG-458)

Fix trase api endpoint url

---

components/ui/refresh-button/component.jsx

Fix a typo (`occured` > `occured`) in error messages that _occur_ when a widget fails to fetch data. 
[FLAG-603](https://gfw.atlassian.net/browse/FLAG-603)

Fix typo in error message that occurs when a widget cannot load

---

providers/whitelists-provider/actions.js

Fix primary forest loss widget not appearing on country/region/subregion/custom dashboards
I was not able to place exactly _where_ this bug has been introduced, but it seems to be have introduced about a month ago. The issue described isn't specific to this widget; it turned out any widgets with custom whitelists (in this case, for primary forest type) could potentially be failing. 
The problem was that when fetching the whitelists, the frontend wasn't parsing them correctly and would fail silently
1. Open the Dashboard  
2. Select a country (eg: _Brazil_)  
3. Visit the _"Forest change"_ section  
- Verify that the `treeLossTsc` widget appears (titled: _PRIMARY FOREST LOSS IN BRAZIL_)  
- Verify that the widget appears for country, region, subregion, custom dashboards …

Fix primary forest loss widget not appearing on country/region/subregion/custom dashboards

---

components/map/component.jsx
components/map/components/attributions/attributions-content/component.jsx
components/map/components/attributions/component.jsx
components/map/components/attributions/styles.scss

This PR adds the missing map attributions to the map. 
[FLAG-598](https://gfw.atlassian.net/browse/FLAG-598)

Add the missing map attributions to the map (+ styling)

---

components/widgets/forest-change/net-change/index.js

This PR makes it so that the `netChange` widget no longer appears for custom AOIs or WDPAs
[FLAG-605](https://gfw.atlassian.net/browse/FLAG-605)

Remove "netChange" widget from custom AOIs and WDPAs

---

components/widgets/land-use/forestry-employment/index.js
utils/format.js

This PR fixes the incorrect units in the Forestry employment donut chart. 
The number of people employed should was in `kha` when it should be in `k`. 
TODO
[FLAG-534](https://gfw.atlassian.net/browse/FLAG-534)

Fix incorrect units in the Forestry employment donut chart

---

components/widgets/land-cover/primary-forest/index.js

This PR fixes the `primaryForest` widget not showing in dashboards for saved AOI. 
It also adds the correct layer to the widget, so that it is shown in analysis when the "Primary Forests" layer is selected. 
[FLAG-278](https://gfw.atlassian.net/browse/FLAG-278)

Fix primaryForest widget not showing in saved AOI/Dashboards

---

components/load-more/component.jsx
components/load-more/index.js
components/load-more/styles.scss
layouts/grants-and-fellowships/projects/component.jsx
layouts/grants-and-fellowships/projects/selectors.js
package.json
pages/about.js
pages/grants-and-fellowships/[section].js
services/projects.js
yarn.lock

Wordpress by default only lets us get 100 posts at once. If G&F gets more Projects (it’s now at 94), they won’t load.
Instead of editing things so that the page fetches more project cards at a time, we’ve opted to paginate and load 21 posts at a time. We’ll follow the same styling that’s done on the GFW Blog (image below). Pagination should improve the loading speed of this page and probably help SEO-wise.
To meet the criteria we had to change the way we provide filters/search in this page.
- From now on, both search and filter are requesting WP Rest API for new items instead just order/omit items on front. 
- Countries filter logic was moved to SSR to avoid these computation on frontend side. 
- WP Rest API was changed and its code is on Pantheon. We should deploy it after that deploy.
- …

[FLG-627] Grants and fellowships projets pagination

---

components/satellite-basemaps/component.jsx
components/satellite-basemaps/styles.scss

**In this PR:** 
- Fix the SatteliteBasemap settings info button not working after a user changes the language  
_was triggering a change in the basemap instead_  
- Fix application error when switching between basemaps after the user changes the language
**Note:** 
More technical explanation in the corresponding JIRA task. 
[FLAG-713](https://gfw.atlassian.net/browse/FLAG-713)
https://gfw-staging-pr-4527.herokuapp.com/map/
1. Visit the /map page
2. In the map legend, expand the basemap settings  
3. Verify that the info buttons work correctly and so does switching the basemaps  
4. Change the language of the page to a different one  
5. Verify that the info buttons work correctly and so does switching the basemaps  
https://user-images.githubusercontent.com/6273795/227187035-5c45004b-f59d …

[FLAG-713] Fix SatteliteBasemap settings info button not working + crashes

---

components/widgets/fires/fire-alerts-simple/index.js
components/widgets/forest-change/integrated-deforestation-alerts/index.js
utils/gfw-meta.js

This PR fixes an intermittent dashboard crash when switching admin areas.  
Occasionally, the fire-alerts-simple will attempt to access GFW_META before it has been fetched, and crashes while trying to access its properties. 
This is similar to what happened before in #4303, and finishes the fix. 
[FLAG-687](https://gfw.atlassian.net/browse/FLAG-687)

[FLAG-687] Fix intermittent dashboard crash when switching admin areas

---

components/charts/components/pie-chart-legend/component.jsx
components/charts/components/pie-chart-legend/styles.scss
components/widget/components/widget-pie-chart-legend/styles.scss
components/widgets/forest-change/integrated-deforestation-alerts/selectors.js

This PR improves the spacing between chart pie legend widgets legend and pie chart. 
In some browsers, due to the sidebars, the pie chart and legend get smooched together with no separation. 
In order to mitigate this, this PR adds a gap, slightly decreases the font size and overall improves the spacing to account for this (while allowing the chart to correctly resize itself). 
Fallback: 
[FLAG-582](https://gfw.atlassian.net/browse/FLAG-582)

Improve spacing between chart pie legend widgets legend and pie chart

---

components/widgets/fires/fire-alerts-simple/index.js

The fire alerts widget isn’t showing for this AOI on the map or dashboard: [Subri River Deforestation Rates & Statistics | GFW](https://gfw.global/3LCh7pW). Here is the link to the widget: [Subri River Deforestation Rates & Statistics | GFW](https://gfw.global/42oID0i)
According to https://resource-watch.github.io/doc-api/reference.html\#what-are-geostore-objects hash and id are the same type and value
- Open the [AOI link](https://gfw-staging-pr-4538.herokuapp.com/dashboards/aoi/6418c42f188ab7001bca0e5e/?category=summary&location=WyJhb2kiLCI2NDE4YzQyZjE4OGFiNzAwMWJjYTBlNWUiXQ%3D%3D&map=eyJjZW50ZXIiOnsibGF0Ijo1LjMxMzE4MDY2OTY2NzIzLCJsbmciOi0xLjczOTM0NTc0ODk3OTA3NTh9LCJ6b29tIjoxMC4wNzAxOTYxNjE1MzkwOTYsImJhc2VtYXAiOnsidmFsdWUiOiJwbGFuZXQiLCJjb2xvciI6IiIsIm5hbWUiOiJwbGFuZXRfbWVkcmVzX3Zpc3VhbF …

[FLAG-723] Fix the fire alerts widget in AOI view  

---

components/widgets/forest-change/integrated-deforestation-alerts/index.js
services/analysis-cached.js

The tree cover loss due to fires widget isn’t showing for this AOI on the map or dashboard: [Subri River Deforestation Rates & Statistics | GFW](https://gfw.global/3LCh7pW). Here is the link to the widget: [Subri River Deforestation Rates & Statistics | GFW](https://gfw.global/42vsoOT).
Now we are using geostore.id over `adm0` as a query parameter.  `adm0` stills as a fallback.
- Use the same AOI mentioned at the ticket.
- Try to see the widget

[FLAG-722] Fix OTF Tree Cover Loss Due Fires

---

components/widgets/forest-change/tree-loss-primary/index.js

this widget [https://gfw.global/3ZWKE2a](https://gfw.global/3ZWKE2a)
isn't showing for the AOI, it is displaying for the global and country dashboards.
it seems that the `whitelists` object in the widget config was misconfigured.
you should see the "Global Primary Forest Loss" widget correctly displayed in the page

[FLAG-748]: display "Global Primary Forest Loss" widget in AOI 

---

components/widgets/forest-change/tree-loss-drivers/selectors.js

The Tree Cover Loss by Drivers widget has a tooltip that appears upon hovering. It lists “Forestry” under “Drivers of permanent deforestation”, which is incorrect. 
the tooltip array was rearranged to display the Forestry entry correct.

[FLAG-757]: move Forestry outside incorrect group

---

layouts/topics/components/topics-header/topics-intro/component.jsx

The explore fire alerts on the map button at the top of the [fire topics page](https://www.globalforestwatch.org/topics/fires/#intro) does not work. Clicking it does nothing but should open the map with [the fire alerts layer](https://www.globalforestwatch.org/map/?analysis=eyJzaG93RHJhdyI6dHJ1ZX0%3D&map=eyJjZW50ZXIiOnsibGF0Ijo5LjkxMDE2Mjc1MTc4ODAyNywibG5nIjotMTIuMTQ5OTA1MDAwMDIxNDg5fSwiem9vbSI6OS41NzgzMjYyMTg4MzMxMDksImRhdGFzZXRzIjpbeyJkYXRhc2V0IjoiZmlyZS1hbGVydHMtdmlpcnMiLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJsYXllcnMiOlsiZmlyZS1hbGVydHMtdmlpcnMiXX0seyJkYXRhc2V0IjoicG9saXRpY2FsLWJvdW5kYXJpZXMiLCJsYXllcnMiOlsiZGlzcHV0ZWQtcG9saXRpY2FsLWJvdW5kYXJpZXMiLCJwb2xpdGljYWwtYm91bmRhcmllcyJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlfV19&mapMenu=eyJtZW51U2VjdGlvbiI6ImRhdGFzZXRzIiwiZGF0YXNldENhdGVnb …

[FLAG-669] Fix the explore fire alerts button

---

layouts/home/config.js

The 'browse our apps' Link on homepage links to https://developers.globalforestwatch.org/
Change this to link to the Help Center here: https://www.globalforestwatch.org/help/
- Open the [page](https://gfw-staging-pr-4542.herokuapp.com/)
- Try to click on "browse our apps"
- Check if it redirects to help page

[FLAG-625] Fix browse our apps button link

---

components/widgets/forest-change/integrated-deforestation-alerts/index.js

The integrated deforestation alerts widget isn’t showing for this AOI on the map or dashboard: [Subri River Deforestation Rates & Statistics | GFW](https://gfw.global/3LCh7pW). Here is the link to the widget: [Subri River Deforestation Rates & Statistics | GFW](https://gfw.global/42CTlR0).
According to https://resource-watch.github.io/doc-api/reference.html\#what-are-geostore-objects hash and id are the same type and value
- Open the [AOI link](https://gfw-staging-pr-4537.herokuapp.com/dashboards/aoi/6418c42f188ab7001bca0e5e/?category=summary&location=WyJhb2kiLCI2NDE4YzQyZjE4OGFiNzAwMWJjYTBlNWUiXQ%3D%3D&map=eyJjZW50ZXIiOnsibGF0Ijo1LjMxMzE4MDY2OTY2NzI1NiwibG5nIjotMS43MzkzNDU3NDg5NzkwNTAzfSwiem9vbSI6MTAuMDcwMTk2MTYxNTM5MDk2LCJiYXNlbWFwIjp7InZhbHVlIjoicGxhbmV0IiwiY29sb3IiOiIiLCJuYW1lIjoicGxhb …

[FLAG-721] Fix the integrated deforestation alerts widget in AOI view

---

components/widgets/fires/fire-alerts-simple/index.js
components/widgets/forest-change/glad-alerts-simple/index.js
components/widgets/forest-change/integrated-deforestation-alerts/index.js
utils/gfw-meta.js

This PR refactors `handleGladMeta`, `handleViirsMeta ` and `handleIntegratedMeta` into a single universal function to be used by widgets. It is a follow up for the quick fix implemented in #4528. 
[Direct link](https://gfw-production.herokuapp.com/dashboards/country/BRA/22/?category=summary&dashboardPrompts=eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkYXNoYm9hcmRBbmFseXNlcyJdLCJzZXR0aW5ncyI6eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6W10sInNldHRpbmdzIjp7Im9wZW4iOmZhbHNlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5IjoiIn0sIm9wZW4iOnRydWUsInN0ZXBJbmRleCI6MCwic3RlcHNLZXkiOiJkYXNoYm9hcmRBbmFseXNlcyJ9LCJvcGVuIjp0cnVlLCJzdGVwc0tleSI6ImRvd25sb2FkRGFzaGJvYXJkU3RhdHMifQ%3D%3D&location=WyJjb3VudHJ5IiwiQlJBIiwiMjIiXQ%3D%3D&map=eyJjZW50ZXIiOnsibGF0IjotMTAuNzc2NDE0ODMxODAxNzExLCJsbmciOi02My4yOTAzOTk5OTk5 …

Refactor handling of GFW_META VIIRS, GLAD and INTEGRATED alerts

---

components/widgets/utils/config.js

Updating filter label from "Intact Forest Landscapes (2016)" to "Intact Forest Landscapes (2000)"

FLAG-719: update filter label from 2016 to 2000

---

components/map/components/legend/component.jsx
components/map/components/legend/components/layer-selector-menu/component.jsx
components/map/components/legend/components/layer-selector-menu/styles.scss
components/map/components/legend/components/layer-statement/component.jsx
components/map/components/legend/components/layer-statement/styles.scss
components/map/components/legend/index.js
components/ui/switch/component.jsx
components/ui/switch/styles.scss
components/ui/switch/themes/switch-light-alternate.scss
components/ui/switch/themes/switch-small.scss
package.json
providers/datasets-provider/actions.js
services/datasets.js
yarn.lock

https://github.com/Vizzuality/gfw/pull/4517/commits/bf4bfb1139d777b4da34c2cf8aa4e7a627a4cf0a needs to be removed before this PR is merged. It is only included at the moment to facilitate testing for both FE and Science. 
This PR adds the possibility of using a toggle/switch in the map legend, in order to switch dataset layers. 
**In this PR:**
- Added the possibility to use a toggle switch to switch between a dataset's layers
- It is enabled when the `isToggleLayer` property is set on a dataset  
- Added a new `light-alternate` theme to the existing `<Switch />` component  
- The `<Switch />` component can now also be displayed in a smaller size  
- Updated `gfw-components` to the latest version  
- Fixed an error _"state mutation detected between dispatches' error when switching layers"_ …

Updated tropical tree cover layer | Toggle switch implementation

---

pages/_document.js

Adding new GTM script alongside existing one
To test this we need to have installed the Tag Assistant Companion
[https://chrome.google.com/webstore/detail/tag-assistant-companion/jmekfmbnaedfebfnmakmokmlfpblbfdm?hl=en](https://chrome.google.com/webstore/detail/tag-assistant-companion/jmekfmbnaedfebfnmakmokmlfpblbfdm?hl=en)

FLAG-751: insert new GTM script

---

components/widgets/land-cover/intact-tree-cover/index.js

We need to make some changes to the Intact Forest widget. The query the widget runs (an example from [Angola](https://gfw.global/3AIc5ma)) looks like this:
```https://data-api.globalforestwatch.org/dataset/gadm__tcl__iso_summary/v202204.2/query/json?sql=SELECT iso, SUM(umd_tree_cover_extent_2010__ha) AS umd_tree_cover_extent_2010__ha, SUM(area__ha) AS area__ha FROM data WHERE iso = 'AGO' AND is__ifl_intact_forest_landscapes_2000 = 'true' AND umd_tree_cover_density_2000__threshold = 30 GROUP BY iso ORDER BY iso```
And the widget says, "As of 2016, 0.53% of Angola's tree cover was intact forest." See the screenshot below.
This sentence does not accurately reflect the query. 
It looks like the query uses the 2010 extent with the 2000 IFL extent. Unfortunately, since we do not have an IFL …

[FLAG-491]: Make changes to the Intact Forest widget

---

components/widgets/forest-change/tree-loss-located/index.js

The location of tree cover loss in [country] widget needs years added. For example, the [LOCATION OF TREE COVER LOSS IN MEXICO](https://gfw.global/3odKntI) widget includes the data from 2001 - 2017. In the settings menu, I can only filter and customize the data from 2001-2017. We need this widget to include the latest data (e.g., 2001-2021) for all the available countries.
- Open the env test link
- Find the widget
- Try to change the data range and/or check the sentence.

[FLAG-761]: Location tree cover widget is missing the latest years

---

services/analysis-cached.js
utils/apis.js
utils/gfw-meta.js
utils/request.js

`fetchVIIRSLatest` is a method to fetch the `updateAt` date before request anything to Data API, however, the endpoint used is deprecated and needs to be updated.
Old endpoint: https://tiles.globalforestwatch.org/nasa_viirs_fire_alerts/v20220726/max_alert__date
New endpoint:  https://data-api.globalforestwatch.org/dataset/nasa_viirs_fire_alerts/latest/
We need to update this endpoint to solve issues with date in Fire Alerts Widget.
This ticket needs Data API team implementation.
Waiting implementation from Data API to test

[FLAG-784] Update VIIRS metadata request URL

---

components/modals/meta/component.jsx

Using replaceAll to avoid errors when we have more than one occurrence of the same variable in metadata modal. Ex: [date]
- Open the map
- Select Tropical Tree Cover layer
- Open metadata info
- check the text

fix(metadata): change method replace to replaceAll

---

components/widgets/land-cover/ranked-forest-types/index.js

For some reason when we add ifl 2016 the extent year changes to 2010 we dont need ifl 2016 for this widget

[FLAG-692] Remove IFL 2016 from rankedForestTypes

---

components/widgets/forest-change/tree-loss-primary/index.js

Primary forest loss widget is showing up on the dashboard (with no data) outside the tropics - e.g. [Romania Deforestation Rates & Statistics | GFW](https://www.globalforestwatch.org/dashboards/country/ROU/) 
This widget should not appear on the dashboard of countries outside the tropics.
We have removed whitelist from Primary Forest Loss to fix an [AOI error](https://gfw.global/3NDPD2L). Indeed we made the right choice since the whitelist was wrongly configured, however, this widget needs tropicalIsos as whitelist. 
Reference: https://github.com/wri/gfw/pull/4539
- Open the dashboard
- Select Romania or any country outside the tropic
- Verify if Primary Forest Loss widget is hidden.

[FLAG-845] adding whitelists with tropicalIsos in primary forest loss widget

---

layouts/dashboards/components/header/component.jsx
layouts/dashboards/components/header/styles.scss

Currently, the download button is hidden behind the three dots on the dashboards (in areas dashboard and global dashboard). We are moving this button outside the dropdown.
The open Map button circled in the screenshot below doesn’t work in the [global](https://www.globalforestwatch.org/dashboards/global/?category=summary&location=WyJnbG9iYWwiXQ%3D%3D&map=eyJkYXRhc2V0cyI6W3sib3BhY2l0eSI6MC43LCJ2aXNpYmlsaXR5Ijp0cnVlLCJkYXRhc2V0IjoicHJpbWFyeS1mb3Jlc3RzIiwibGF5ZXJzIjpbInByaW1hcnktZm9yZXN0cy0yMDAxIl19LHsiZGF0YXNldCI6InBvbGl0aWNhbC1ib3VuZGFyaWVzIiwibGF5ZXJzIjpbImRpc3B1dGVkLXBvbGl0aWNhbC1ib3VuZGFyaWVzIiwicG9saXRpY2FsLWJvdW5kYXJpZXMiXSwiYm91bmRhcnkiOnRydWUsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9LHsiZGF0YXNldCI6InRyZWUtY292ZXItbG9zcyIsImxheWVycyI6WyJ0cmVlLWNvdmVyLWxvc3MiXSwib3BhY2l0eSI6MSwidmlzaWJ …

[FLAG-487/840] Move download button and remove open map 

---

pages/dashboards/[[...location]].js

Fixing issue when trying to paste a url in the browser with query params, the app replaced those query params incorrectly:
original url (it has `category=forest-change`):  
```
https://www.globalforestwatch.org/dashboards/global/?category=forest-change&location=WyJnbG9iYWwiXQ%3D%3D&map=eyJkYXRhc2V0cyI6W3siZGF0YXNldCI6InBvbGl0aWNhbC1ib3VuZGFyaWVzIiwibGF5ZXJzIjpbImRpc3B1dGVkLXBvbGl0aWNhbC1ib3VuZGFyaWVzIiwicG9saXRpY2FsLWJvdW5kYXJpZXMiXSwiYm91bmRhcnkiOnRydWUsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9LHsiZGF0YXNldCI6Ik5ldC1DaGFuZ2UtU1RBR0lORyIsImxheWVycyI6WyJmb3Jlc3QtbmV0LWNoYW5nZSJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJwYXJhbXMiOnsidmlzaWJpbGl0eSI6dHJ1ZSwiYWRtX2xldmVsIjoiYWRtMCJ9fV19&scrollTo=treeLossPct&showMap=false&treeLossPct=eyJoaWdobGlnaHRlZCI6ZmFsc2V9&widget=treeLossPct
```
server …

FLAG-894: page reload with incorrect query params

---

.env.sample
.gitignore
components/header/component.jsx
fixtures/notifications/index.js
pages/dashboards/[[...location]].js
pages/grants-and-fellowships/[section].js
pages/index.js
pages/map/[[...location]].js
pages/my-gfw.js
services/__tests__/notifications.spec.js
services/notifications.js
wrappers/fullscreen/component.jsx
wrappers/page/component.jsx

Fetching notifications for all pages. Notifications aren't visible yet, that is going to be addressed in a separate ticket.

FLAG-866: fetch notifications and pass them as props to Header

---

components/widgets/fires/tree-loss-fires-annual/index.js
services/analysis-cached.js

I accidentally merged #4681 into `develop` after review, but before QA. 
The accidental merged was promptly reverted by #4684.
This PR is to revert the revert after QA (and spin up a new test environment for the QA team).

FLAG-900: Undefined year causing an error in the TCL due to Fires widget in protected and some custom area dashboards

---

components/charts/composed-chart/axis-label.jsx
components/charts/composed-chart/component.jsx
components/charts/composed-chart/styles.scss
components/widget/components/widget-footer/styles.scss
components/widgets/land-cover/tree-cover-density/index.js

It makes no sense to use the “tree cover by type” widget for both tree cover 2000/2010 data and tropical tree cover analyses. Taking that into consideration, researchers are ok with us instead using the widget you created, “Tree Cover Density in [area]“, for Tropical Tree Cover analysis. 
[From user stories](https://gfw.atlassian.net/jira/software/c/projects/FLAG/issues/FLAG-693?jql=project%20%3D%20%22FLAG%22%20and%20text%20~%20%22priority%205%22%20and%20status%20%3D%20Released%20ORDER%20BY%20created%20DESC), this should appear only at the country, region, and sub-region level, as well as for saved custom areas.
- Open [the map](https://gfw-staging-pr-4683.herokuapp.com/map/). 
- Select an Admin or Custom Area. 
- Click to analyse the area
- Select Tropical Tree cover Layer
- Verify if …

[FLAG-844] Add tree cover density to analysis

---

components/legend/components/legend-item-types/legend-item-type-basic/legend-item-type-basic-item/index.js

The map legend's colored circles are being squished in some legend items, independently of the layer and/or legend in question. 
It looks like this happens when the text next to the circle is too long, causing the circle's element to get squished. Setting a `minWidth` alongside the `width` seems to fix the issue. 
N/A
1. Visit the corresponding [JIRA task](https://gfw.atlassian.net/browse/FLAG-876)  
2. Review that the items/links in the description now work correctly
https://gfw.atlassian.net/browse/FLAG-876

FLAG-876: Fix map legend circles being squished

---

components/map/components/layer-manager/component.jsx

This PR fixes an issue in sattelite imagery basemaps "stick". 
From what I've gathered the issue was due to the `key="basemap"` when adding the basemap layer; switching to `key={basemap.url}` also solves it.
I've chosen to merge the basemap back into the `allLayers` instead for a couple reasons: 
- I feel like it's clearer to pass an array of layers (basemap or not) to the LayerManager and let it handle them  
- Avoiding issues with keys in the future  
- It was done that way in the past. It was changed in an attempt to fix basemap issues in [#4533](https://github.com/wri/gfw/pull/4533), though it turned out that change only made the issue more frequent. The ultimate solution was found later on, with [#4633](https://github.com/wri/gfw/pull/4633), in which we finally figured out it was due …

[FLAG-791] Issues turning the satellite imagery toggle on and off 

---

components/widgets/index.js
components/widgets/reducers.js
components/widgets/selectors.js
layouts/dashboards/components/global-sentence/selectors.js
layouts/dashboards/selectors.js
pages/dashboards/[[...location]].js

 PROD Deploy 2023-10-10 06:42am EST 

---

jest.config.js
services/__tests__/get-where-query.spec.js
services/analysis-cached.js
services/get-where-query.js
utils/get-where-query-allowed-params.js
utils/get-where-query-translation.js

Tree Cover Density widget doesn't work correctly on Analysis when threshold is added as parameter. 
This widget has its own threshold (>10 as default), but when a user selects Tropical Tree Cover layer and changes the threshold, a new parameter was added to the query, making the request fail.
We did a major refactor at the `getWHEREQuery` to improve readability and add some new validations.
- Open the map
- Select Tropical Tree Cover
- Change the threshold
- Try to see Tree Cover Density Widget (it should work normally)

[FLAG-943] Tropical Tree Cover analysis malfunctioning

---

components/widgets/fires/burned-area-cumulative/index.js
components/widgets/fires/burned-area-ranked/index.js
components/widgets/fires/burned-area/index.js
components/widgets/fires/fires-alerts-cumulative/index.js
data/fires-datasets.json

Removing "MODIS Burned Areas" from the web application.
This release will require updating the RW API to unpublish the corresponding layer and dataset.
before:
after:

FLAG-901: remove MODIS Burned Areas from widgets

---

pages/api/gfw/[...params].js
utils/request.js

RW API now validates Api Key. So for now, we are removing the x-api-key until we have the right value for that.

fix(rw-api): remove x-api-key from RW API requests

---

components/widgets/forest-change/net-change/index.js

FLAG-975 | remove survey alert

---

components/widgets/forest-change/fao-reforest/index.js
components/widgets/forest-change/fao-reforest/selectors.js
services/forest-data.js

Update the current widget (shown below) to the 2020 data and update the year selector.
Data sources: we previously stored the data for FAO widgets in Carto. The engineering team has opted to move this data to the Data API, using [these spreadsheets](https://onewri.sharepoint.com/sites/globalforest/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fglobalforest%2FShared%20Documents%2FPlatform%2FProjects%20and%20Tasks%2FFAO%202020%20updates%2Fdata&p=true&ga=1) as a source. They’re hoping that constructing queries will be relatively straightforward, but Justin and Maanas are available in case we need help. The data on the Data API is available here:
FAO Forest Change: https://data-api.globalforestwatch.org/dataset/fao_forest_change/v2020/query/
FAO Forestry Employment: …

[FLAG-926]  FAO reforestation widget

---

components/widgets/fires/fires-alerts/selectors.js
components/widgets/utils/data.js

When doing a year comparison for the[ weekly fire alerts widget](https://gfw.global/47ESukX), the selected year or the blue line shows a previous year. For example, 2022 was selected, but 2021 is shown instead. We must ensure that Dec 2022-Dec 2022 is displayed when 2022 is selected. I’m noticing the same pattern for all selected years. 
- Check whether the data or just the label is incorrect
- Implement a fix so that the blue label shows a full year (in the example below, should be Dec 2021 - Dec 2022)
- Open the [widget](https://gfw-staging-pr-4735.herokuapp.com/dashboards/country/BRA/?category=fires)
- Select the year to compare
- Validate which year appears at year label

[FLAG-982] Weekly Fire Alerts wrong date comparison

---

utils/request.js

removing api key form `apiRequest` function since it was breaking my gfw areas requests.

FLAG-1038: remove api key from apiRequest function

---

components/forms/components/field-wrapper/styles.scss
components/forms/components/select/component.jsx
components/forms/newsletter/component.jsx
components/map-menu/components/sections/explore/sections.js
components/success-message/component.jsx
services/forms.js

- Add/change/reorder fields in the `/subscribe` form  
- `interests` is now sent as an array of interests, instead of a string with comma separated positions  
- Updated the form handler link to the new one  
- Updated message displayed after the user successfully submits the form  
- Added the possibility to add descriptions to the select input  
- Removed an unused pardot extra field  
- The _"Places to Watch"_ link now points to this subscribe form  
[FLAG-1014](https://gfw.atlassian.net/browse/FLAG-1014)

FLAG-1014: Change main subscribe form and PTW to use Ortto instead of Pardot

---

components/forms/newsletter/component.jsx

This is a minor fix to join the interest values in the subscribe form; or Ortto will only receive the first interest selected. 
[FLAG-1014](https://gfw.atlassian.net/browse/FLAG-1014)

[FLAG-1014] Newsletter changes tweaks

---

layouts/privacy-policy/component.jsx
layouts/privacy-policy/styles.scss

This PR updates the Privacy Policy text in order to match the updated copy/version in the main WRI website, as per task's description. 
**Notes:**  
I made a couple quick changes, unrequested, under review by the QA team:  
- I've noticed WRI's Privacy Policy often mentions other sections, which are linked to the respective section via hash tags. This was not working nor implemented at all in the GFW website; I took the liberty of implementing it (no animations, just making them work. If necessary, we can animate the scroll later on)    
- Verified that all links have `rel="noopener noreferrer"`  
Some were missing it. `noopener` ends up being redundant in this context, but as standard practice I've added both anyways. 
- While going through the Privacy Policy, I noticed it was both …

[FLAG-1012] Update privacy policy language

---

components/widgets/climate/carbon-flux/index.js
components/widgets/climate/emissions-deforestation/index.js
components/widgets/fires/tree-loss-fires-annual/index.js
components/widgets/fires/tree-loss-fires-annual/selectors.js
components/widgets/fires/tree-loss-fires-proportion/index.js
components/widgets/fires/tree-loss-fires-proportion/selectors.js
components/widgets/fires/tree-loss-fires/index.js
components/widgets/forest-change/tree-loss-drivers/index.js
components/widgets/forest-change/tree-loss-global/selectors.js
components/widgets/forest-change/tree-loss-plantations/selectors.js
components/widgets/forest-change/tree-loss/selectors.js
data/dashboard-summary-sentence.js
services/get-where-query.js
services/sentences.js

While we work to complete final TCL items and prepare for the full launch, we’ll need to also prepare to remove the MVP-specific work that we did. Since we didn’t initially launch all the data we normally do (drivers, carbon, etc), we made a number of changes (all included below) that we will need to revert.
We need to remove the sentence that we added to the paragraphs at the top of the “summary” and “forest change” tabs: “Download global 2023 tree cover loss data by country here.”
in 1070, we hid parts of the sentence that related to carbon; we need to ensure they appear again with the updated data we’re doing in FLAG-1049: Update dashboard + map widgets with new TCL tables
We added a caveat to dashboards and layers explaining that data weren’t updated; we need to remove it with the …

[FLAG-1094] Remove MVP items 

---

components/charts/sankey-chart/component.jsx

The Sankey component was trying to use a `getPresentationAttributes` function which doesn't exist neither in gfw codebase nor in recharts library.
Removing those calls to that non-existing function fixed the widget component.

FLAG-1003: remove nonexistent getPresentationAttributes function

---

components/widgets/forest-change/tree-loss-primary/index.js

adding a validation for widget embed for the specific case in Indonesia, to avoid displaying the hardcoded image when embedding a widget.

FLAG-1111: fix widget embed for IDN

---

components/widgets/forest-change/integrated-alerts-ranked/index.js
components/widgets/forest-change/integrated-deforestation-alerts/index.js

This PR removes the integrated alerts widgets' alerts/survey link added in [#4673](https://github.com/wri/gfw/pull/4673). 
[FLAG-940](https://gfw.atlassian.net/browse/FLAG-940)

[FLAG-940] Remove alert message from integrated alerts widgets

---

components/map-menu/components/sections/explore/sections.js

This PR changes the map/explore mongabay stores _Read more_ link to the new version. 
Although it implements [FLAG-942](https://gfw.atlassian.net/browse/FLAG-942), all the changes, including bugfix were implemented Science side; FE only debugged it. 
We're leveraging an existing mechanism to link to an external page. 
[FLAG-942](https://gfw.atlassian.net/browse/FLAG-942)

[FLAG-942] Update MongabayStories map/explore link to the new external link

---

pages/api/set-cookie.js
pages/my-gfw.js
providers/mygfw-provider/actions.js
services/user.js

A user shared their area with me: http://www.globalforestwatch.org/dashboards/aoi/6557f6b9695f90001af381ea (currently it’s set to public), but when a user chooses to change it to private, it’s no longer accessible: https://www.globalforestwatch.org/dashboards/aoi/6557f6b9695f90001af381ea/?lang=en in their own My GFW account.
The issue was related to an specific cookie (gfw-token) that once expired, the user remained logged in because the same cookie is found in the localStorage. The token must be validated by cookies instead of local Storage, so I removed this validation to ensure that every time the cookie expires, a new login is required. 
Cookie was set to expires in 1 year.

[FLAG-973] Private saved areas are not accessible in a user's own My GFW account

---

utils/request.js

Observed behavior: When I set my area of interest to public and I share the link to that area, other users see a non-stop spinner and cannot see the area of interest when they visit the link. I also see authorization errors in the browser network panel.
[Public areas cannot be viewed by other users](https://www.loom.com/share/a8478e7b1e0f47cda6546ca8dce75e6c?sid=8a595233-fe08-404c-8795-8b4c4f7d375d) 
Expected behavior: When I share a link to an area of interest set to public, then other users can visit the link and see the area of interest without errors.

[FLAG-1131] Public areas cannot be viewed by other users

---

components/widgets/forest-change/net-change/index.js
package.json
pages/api/datamart/net-change/index.js
services/analysis-cached.js
utils/proxies.js
utils/request.js
yarn.lock

Create a new api route that serves as a proxy to hide all SQL details from client side, this PoC will serve as the first step to implement a data mart on the API side by the engineering team.
The new api route only works for the net change widget since it is a simple one that doesn't have dynamic filters.
**Original client request:**
```
https://gfw-staging-pr-4810.herokuapp.com/api/data/dataset/umd_adm2_net_tree_cover_change_from_height/v202209/query/?sql=SELECT iso, adm1, adm2, iso, adm1_name, adm2_name, stable, loss, gain, disturb, net, change, gfw_area__ha FROM data WHERE iso = 'MEX' AND adm1 = '9' AND adm2 = '3' 
```
**New client request:**
```
https://gfw-staging-pr-4810.herokuapp.com/api/datamart/net-change/?type=global&version=v202209&fields=iso,stable,loss,gain,disturb,net,change, …
```

FLAG-1114: create datamart api route

---

components/widgets/forest-change/net-change/index.js
package.json
pages/api/datamart/net-change/index.js
services/analysis-cached.js
utils/proxies.js
utils/request.js
yarn.lock

https://github.com/wri/gfw/pull/4810

PROD Deploy 2024-06-28 03:52pm EST

---

components/widgets/fires/fires-alerts/index.js
components/widgets/fires/fires-alerts/selectors.js
components/widgets/utils/data.js

[In Slack](https://globalforestwatch.slack.com/archives/C0V94B8PK/p1719242065970669), Jimmy noted that something seems to be wrong with weekly VIIRS alert widget; he thinks it is a front end issue and has to do with the way it is being queried. The downloaded data looks correct and has data through this week. 
Alongside this task, new bugs were found.
Example from Yukon, Canada:

[FLAG-1128] Incorrect query in weekly VIIRS alert widget

---

components/widgets/land-use/economic-impact/index.js
components/widgets/land-use/economic-impact/selectors.js
components/widgets/land-use/forestry-employment/index.js
components/widgets/land-use/forestry-employment/selectors.js
data/colors.json
services/forest-data.js

- FAO forestry employment widget:  
- Now pulls data from the data API, instead of Carto  
- Now displays percentages by sector in the donut chart  
_instead of the percentage by male/female_  
- Donut chart colors have been tweaked  
_It used to use the same colors as the Economic Impact widget, now the color definitions are separate due to the changes_  
- Minor tweaks to the sentence wording  
- New query for fetching the data, following the same standards as other calls in the same `forest-data` service  
- Adapted the years that can be selected to match the acceptance criteria: 
- We removed `1990` and '2005', added `2015`  
- `2015` is now the default  
- Download URL is working, with the csv provided by the dataset endpoint  
**Notes:**  
- The codebase for this …

[FLAG-927]  Change design/layout for existing FAO forestry employment 

---

components/widgets/land-use/forestry-employment/selectors.js

This PR adds the `unit` to the forestry-employment widget chart data, in order to eliminate the space between value and unit (`%`)
[FLAG-927](https://gfw.atlassian.net/browse/FLAG-927)

[FLAG-927] Remove space between percentage and numbers for the forestry-employment widget

---

components/widgets/forest-change/tree-cover-gain-simple/index.js
components/widgets/forest-change/tree-loss/index.js
components/widgets/land-cover/tree-cover/index.js
services/analysis-cached.js
services/otf-analysis.js

Replacing `zonal` with `query` endpoints on the following widgets:
- treeCoverGainSimple
- treeLoss
- treeCover

FLAG-861: replace /zonal with /query

---

components/widgets/utils/helpers.js

Fixing WDPA widget:
- removes deprecated zonal endpoint
- uses correct request and parameters
See "Tree Cover Loss in Subri River"
`/dashboards/aoi/668825063b906900209f55da/`

FLAG-755: add isWdpaArea check on shouldQueryPrecomputedTables function

---

utils/url-param.js
utils/url.js

The FE makes use of [btoa()](https://developer.mozilla.org/en-US/docs/Web/API/Window/btoa) to Base64 encode parameters for the URL. However, [this method fails when strings include characters that take more than one byte](https://developer.mozilla.org/en-US/docs/Web/API/Window/btoa#unicode_strings), which is the case of _"Bình Thuận"_, the string that when searched caused the FE to crash. 
This is known as [the Unicode Problem](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem). 
The MDN Web Docs offer a solution, which passes by first encoding the string with [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) (and later using the [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) counterpart to reverse it), …

[FLAG-923] Pasting a special character into search by location lead to an error occurred

---

components/map/components/legend/components/layer-select-menu/component.jsx
components/widgets/fires/burned-area-cumulative/selectors.js
components/widgets/fires/burned-area/selectors.js
components/widgets/fires/fire-alerts-simple/selectors.js
components/widgets/fires/fires-alerts-cumulative/selectors.js
components/widgets/fires/fires-alerts-historical-daily/selectors.js
components/widgets/fires/fires-alerts-historical-weekly/selectors.js
components/widgets/fires/fires-alerts-historical/selectors.js
components/widgets/fires/fires-alerts/selectors.js
components/widgets/forest-change/glad-alerts-simple/selectors.js
components/widgets/forest-change/glad-alerts/selectors.js
components/widgets/forest-change/integrated-deforestation-alerts/selectors.js
utils/localize-date.js

This PR aims to address _a few_ issues with _the integration deforestation alerts_ widget's translations, as well as a few others. This implementation focuses mainly on two aspects:  
- Localize dates 
_with a setup similar (but not quite the same, due to the requirements and implementation) to the one [implemented for the blog](https://github.com/wri/gfw-blog/pull/155)_
- Address issues with strings (some with value interpolation) not being correctly sent to Transifex
_in a way that'd allow for variable interpolation (in Transifex)_   
- Integrated deforestation alerts dropdown not translating for the selected item  
&nbsp;  
**Date localization**  
A similar setup to the one used for localizing dates in the blog (see here)[https://github.com/wri/gfw-blog/pull/155] was implemented. It …

[FLAG-1035] Fix variables in the integrated deforestation alerts widget for translations to work properly

---

components/widget/index.js

Many widgets (list below) use the `shouldQueryPrecomputedTables` helper to decide whether they should query precomputed tables for AOIs or do an on-the-fly analysis. When an area was not yet precomputed, OTF should be used, but if there was a nightly run the data will have a `saved` `status`, and precomputed tables should be used instead. 
The issue is that `status` is always `undefined`, as it is not being passed to the widgets `getData` function. This PR passes that data again, and adds a comment so that we know what the `status` is used for. 
[FLAG-875](https://gfw.atlassian.net/browse/FLAG-875)

[FLAG-875] Fix widgets never using precalc tables due to missing `status`

---

components/widgets/land-cover/tree-cover/index.js
components/widgets/land-cover/tree-cover/selectors.js
data/colors.json
data/land-categories.js

As a user, I can view how much tree cover and other land cover exists in my area of interest for 3 tree cover datasets (UMD tree cover 2000 and 2010, tropical tree cover 2020). I can also see the area of tree plantations in my area of interest.
Given that:
- The user is viewing the [“tree cover by type” widget](https://gfw.global/47W8RKt) on the summary or land cover tabs.
- The user has selected any of the options in the “Tree cover dataset” selector in the settings of this widget (“Tree cover 2000”, “Tree cover 2010”, or “Tropical tree cover 2020”)
- We will change the name of the widget to: Global: “Global tree cover”Country/subnational: “Tree cover in [area]
- Change categories shown on the widget
- The default categories will now be:
- tree cover (hex: #506917)
- other land cover …

[FLAG-1098] Priority 2: Rename the “tree cover by type” widget and add “Plantations” intersection

---

components/widgets/forest-change/tree-loss-ranked/index.js
components/widgets/forest-change/tree-loss-ranked/selectors.js

There are a couple of issues with the TCL compared to other areas widget https://gfw.global/4dDrVi3:
The percentage in the sentence equivalent to a 100% decrease since 2000 is incorrect and instead should be equivalent to a 6.3% decrease in tree cover since 2000. Please reference this widget for the correct query: https://gfw.global/3A1zhyg.
Replace part of the sentence and 0.20% of the global total with and X% of all tree cover loss in [name of region]. Please reference the tree cover compared to other areas widget: https://gfw.global/486J02Q .

[FLAG-1197] Fix the TCL compared to other areas widget

---

components/charts/composed-chart/component.jsx
components/widget/component.jsx
components/widget/components/widget-chart-legend/component.jsx
components/widget/components/widget-chart-legend/index.js
components/widget/components/widget-chart-legend/styles.scss
components/widget/components/widget-composed-chart/component.jsx
components/widgets/climate/emissions-deforestation-drivers/selectors.js
components/widgets/component.jsx
components/widgets/forest-change/tree-loss-primary/selectors.js
pages/_app.js

This PR adds a new `WidgetChartLegend` component to display legends below _a_ chart.  
Although it's currently being imported in `WidgetComposedChart`, it is made to be very generic and to work in a widget's body. It could potentially be displayed below other chart types.
Although it is built focused on column support (with optional titles), it does have a `vertical` prop to display columns vertically. This support is due to the inability to display columns in the map/analysis, but could be used if added to other widgets that are half size. 
**Notes:** 
- This PR is primarily to add support for this type of legend as requested; I've added a legend quickly to the emissions widget just for demonstration of the multi-column & title support. There is no active task to add the legend to the …

[FLAG-1145][FLAG-1110] Support legend in bar chart widgets + add legend primary forest loss widget

---

components/widgets/climate/soil-organic/index.js
components/widgets/climate/soil-organic/selectors.js
services/analysis-cached.js

This PR adds a new request to `analysis-cached` to get request the widget's data from the pre-calculated tables and adapts the widget to work with the new data. The original call `getSoilOrganicCarbon` found in `services/climate.js` was not removed as it is still used by the carbon stock widget. 
In order to keep the implementation/calculations (`selectors.js`), the implementation implements the same logic found in the `whrc-biomass` widget (albeit adapted), as it is a known good one with a similar display. 
Verify that the widget is pulling data from the precalculated tables, and not the carto query. 
[FLAG-1121](https://gfw.atlassian.net/browse/FLAG-1121)
[FLAG-1121]: https://gfw.atlassian.net/browse/FLAG-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

[FLAG-1121] soilOrganic widget to pull data from the precalculated tables instead of the carto ones

---

components/map/components/legend/components/timeline/index.js
components/map/components/legend/components/timeline/selectors.js
components/slider/index.js
components/timestep/index.js
providers/datasets-provider/actions.js
providers/datasets-provider/config.js

This PR is focused on the code implementation (decoding functions, adding FE support for the desired behaviours) that enables this functionality. 
Enabling this functionality is done in the datasets configuration. 
At the moment this can be tested by enabling the _"Tree cover gain (TEST)"_ layer (it is currently defined as a separate one dataset side, `staging`). 
Text and metadata, likewise, is set in the dataset side and not currently up to date, I'm passing the original JIRA task to @AngelArcones. The FE code can be reviewed in advance though. 
A new version Tree Cover Gain is in development, including year encoding with a similar decoding function to Tree Cover Loss. This PR aims to create a new decoding function `treeCoverGain5y` to correctly display this new layer data, adapting the …

[FLAG-1016] Priority 1: Update gain layer with 5-year baselines

---

components/widgets/forest-change/tree-loss-plantations/index.js
components/widgets/forest-change/tree-loss-plantations/selectors.js
services/analysis-cached.js
services/get-where-query.js
services/sentences.js

With Natural Forest epic, the dashboard sentences need to be updated, this PR address that.

FLAG-1154: update dashboard sentences for natural forest

---

components/widgets/forest-change/tree-loss-plantations/selectors.js

A user reported an issue with the Forest Change tab for the [Gujarat region](https://www.globalforestwatch.org/dashboards/country/IND/11/?category=forest-change&map=eyJjYW5Cb3VuZCI6dHJ1ZX0%3D) in India. When selecting this region and switching to the Forest Change tab, an error occurs.
It appears to be a front-end issue, as the system is reading an undefined value, which causes the error.

[FLAG-1208]: Dashboard error in the forest change tab for Gujarat region in India

---

components/widgets/climate/emissions-deforestation-drivers/selectors.js

FLAG-1199: move tooltips to correct place

---

pages/api/metadata/[...params].js
providers/datasets-provider/actions.js
services/datasets.js
services/shape.js

Now we can set each API separatedly, making it easier to test different environments at once

[FLAG-1095] Split RW and GFW API's keys to make it more flexible

---

components/widgets/utils/data.js

FLAG-1238: replace moment for date-fns in getDatesData function

---

.eslintignore
components/widgets/forest-change/tree-cover-gain/index.js
services/analysis-cached.js

We have an object called `typeByGrouped` used to set the correct adm level depending if we need a "grouped" data (comparing regions and subregions for example). I changed the value for adm1 to keep using adm1 even for grouped data, however it didn't work as expected for some widgets. I rolled it back to use adm2. 
```
const typeByGrouped = {
global: {
default: 'adm0',
grouped: 'adm0',
},
adm0: {
default: 'adm0',
grouped: 'adm1',
},
adm1: {
default: 'adm1',
grouped: 'adm2', // here
},
adm2: {
default: 'adm2',
grouped: 'adm2',
},
};
```

fix(tree-gain): widgets are not displaying data

---

components/analysis/components/show-analysis/component.jsx
components/analysis/selectors.js
components/widgets/forest-change/tree-loss-plantations/index.js
components/widgets/forest-change/tree-loss-plantations/selectors.js
components/widgets/forest-change/tree-loss-ranked/selectors.js
components/widgets/land-cover/natural-forest/index.js
components/widgets/land-cover/natural-forest/selectors.js
components/widgets/land-cover/tree-cover-ranked/index.js
components/widgets/manifest.js
components/widgets/utils/config.js
components/widgets/utils/data.js
data/datasets.js
data/layers.js
services/analysis-cached.js
services/get-where-query.js
services/sentences.js

Given that: 
- the user is on the “land cover“ tab of the dashboards
- the user is viewing the “natural forest” widget
- the user is viewing the world or an admin area (no custom area analysis)
- this widget will appear before the current “tree cover by type” widget; it should be the first to appear in the “land cover” section of the dashboards
- this widget will appear before the “tree cover by type” widget
-  to the right of/after the “location of tree cover” widget

FLAG-1155: natural forest widget

---

components/charts/components/pie-chart-legend/component.jsx
components/charts/components/pie-chart-legend/styles.scss
components/widget/components/widget-pie-chart-legend/component.jsx
components/widget/components/widget-pie-chart-legend/styles.scss
components/widgets/forest-change/_tree-loss-drivers/index.js
components/widgets/forest-change/_tree-loss-drivers/selectors.js
components/widgets/manifest.js

Support adding groups of legend items in doughnut charts. A legend item is composed of (1) a color swatch, (2) a label, and (3) a statistic.
Groups stack vertically (i.e. flex-direction: column)
Items within a group wrap to form multiple rows if their total width exceeds the parent container (i.e. flex-wrap: wrap)
Groups can have an optional header with the following styles (anything not listed here should be the default for GFW’s typical style):
font-size: 14px
font-weight: bold
There should be a 5px gap between the optional header and the items in the group. This can be achieved though padding, margin, or any other styling that is convenient.
When the widget is shown in full width (e.g. on the dashboard), then the legend should appear to the left of the doughnut. (This is the current …

[FLAG-1226] Support grouped legend in doughnut charts

---

components/charts/components/pie-chart-legend/component.jsx
components/charts/components/pie-chart-legend/styles.scss
components/widget/components/widget-pie-chart-legend/component.jsx
components/widget/components/widget-pie-chart-legend/styles.scss
components/widgets/forest-change/_tree-loss-drivers/index.js
components/widgets/forest-change/_tree-loss-drivers/selectors.js

Revert deploy

---

components/widgets/forest-change/tree-loss-global/index.js
components/widgets/forest-change/tree-loss/index.js

To be consistent with the SDPT layer being available as a “forest type” filter in the tree cover loss due to fires in [area] widget and forest-related greenhouse gas emissions in [area] widget, we would like to add it to the tree cover loss in [area] widget
The user is viewing the [tree cover loss in [area] widget](https://gfw.global/4asb4NQ) on the summary and forest change tabs, and is available for all admin levels
In the “settings” button for this widget, there is a “Forest type” dropdown - we will need to add an option for “Plantations” just as we have for the tree cover loss due to fires in [area] widget and forest-related greenhouse gas emissions in [area] widget.
It can be before “Primary forests” just as it is in other widgets.
When the user has selected the “Plantations” option …

[FLAG-1106] Priority 6: Add Plantations as a filter to the 'Forest Type' dropdown of tree cover loss in [area] widget

---

components/widgets/climate/carbon-stock/index.js
components/widgets/climate/carbon-stock/selectors.js
components/widgets/climate/soil-organic/index.js
components/widgets/climate/soil-organic/selectors.js
components/widgets/manifest.js
services/analysis-cached.js
services/climate.js

FLAG-1210: replace carto query with precalculated table for soil organic widget

---

components/widgets/forest-change/tree-loss-drivers/index.js
components/widgets/forest-change/tree-loss-drivers/selectors.js

To be consistent with the SDPT layer being available as a “forest type” filter in the tree cover loss due to fires in [area] widget and forest-related greenhouse gas emissions in [area] widget, we would like to add it to the annual tree cover loss by dominant driver in [area] widget
We need to add a “forest type” dropdown in the settings for this widget. It will have two options:All tree cover (the default)PlantationsLuis and Will will see how easy it would be to make this change; it’s a new way of doing things. Please let Teresa know if this won’t work.
In the “settings” button for this widget, there is a “Forest type” dropdown - we will need to add an option for “Plantations” just as we have for the tree cover loss due to fires in [area] widget and forest-related greenhouse gas …

[FLAG-1107] Add forest type 'plantations' to tree loss drivers widget

---

services/__tests__/geostore.spec.js
services/geostore.js

This card makes the geojson simplification explicit when a geostore is requested from the Data API Area microservice.
Previously, Flagship passed a thresh query parameter when GETing administrative boundary geostores. The RW Geostore MS ignored the param because it wasn’t named correctly.
It looked like it worked because the RW Geostore MS implemented its own default simplification values. I’ve documented [this on the miro board](https://miro.com/app/board/uXjVLKsI-90=/?moveToWidget=3458764605651383931&cot=14).
Going forward, we want to make sure we’re sending (and receiving) the simplified geostores that we’ve asked for and not rely on the RW Geostore MS defaults.
This involves adding one query parameter to the Data API geostore GET request.
Currently, requests for a user’s Areas look …

[FLAG-1271] Add `simplify` query param when GETing admin geostores

---

components/forms/newsletter/component.jsx
components/forms/profile/actions.js
components/forms/profile/component.jsx
components/forms/profile/config.js
components/forms/profile/index.js
pages/api/ortto/index.js

Updating profile form to account for new updates and new fields
1. Match the topics in the field WHAT TOPICS ARE YOU INTERESTED IN? * to the topics and their order as shown in the screenshot below
2. Add PREFERRED LANGUAGE (Please note that most communications will be sent in English.) dropdown and place it underneath HOW DO YOU USE GLOBAL FOREST WATCH? *
3. Add email opt-in checkbox, WOULD YOU LIKE TO RECEIVE UPDATES ON NEWS AND EVENTS FROM GLOBAL FOREST WATCH? and place it underneath WOULD YOU LIKE TO HELPS US TEST NEW APPLICATION FEATURES?

FLAG-1204: update profile form

---

components/forms/area-of-interest/actions.js

The RW Area microservice and Flagship are aware of the concept of a provider and version for Areas that are administrative boundaries (GADM 3.6 or 4.1).
Therefore, when areas are created or updated using the Areas microservice, it’s necessary to provide the provider and version as part of the Area payload.
Implementation Details
[Areas Service where Areas are saved/updated](https://github.com/wri/gfw/blob/2d31f12257cc0783b85938bd662ad49acf2f3f52/services/areas.js#L68) in Flagship
Area payloads should have a source attribute in either its iso or admin object (or both) when saving/updating an Area representing an administrative boundary.
This schema is the same shape as what is currently returned in an Area representation from the MS:
```
"iso": {
"source": {                   <= If the new …
```

[FLAG-1261] Provide GADM Version when Creating/Updating an Area

---

services/__tests__/areas.spec.js
services/areas.js

The RW Areas MS allows clients to filter administrative areas with a source[provider] and source[version] filter.
Regardless of the filter, all custom areas are always returned
For backward compatibility, when the filter isn’t used OR it’s used with the values gadm and 3.6, administrative boundary areas (those with iso or admin values) with a 3.6 version will also be returned. Any user’s administrative boundary that is only 4.1 will NOT be returned. This is so legacy clients do not try to interpret the 4.1 GADM IDs as 3.6 
Going forward, when the filter is used for values gadm and 4.1, administrative boundary areas with a 4.1 version will be returned. Any user’s administrative boundary area that is only 3.6 (areas that could not be automatically updated to 4.1) are NOT returned. …

[FLAG-1274] Update Areas Service to get both 3.6 and 4.1 User Areas

---

services/__tests__/areas.spec.js
services/areas.js

Since we're still on 3.6 in production. We need to remove the second 4.1 request to the RW Areas MS.
#4957

chore(gadm): comment gadm 4.1 logic inside getAreas

---

components/map/selectors.js
components/ui/map/component.jsx

This PR fixes a regression from [dbfa56b](https://github.com/wri/gfw/commit/dbfa56b6179407b6410bdfd58d6ad6a1caf0af2c) when React was bumped to v18. The problem meant that the map was unresponsive when panning and zooming.
The proposed fix implies removing any map transition duration unless when flying between location (and in such case only temporarily).
[FLAG-1297](https://gfw.atlassian.net/browse/FLAG-1297)
[FLAG-1297]: https://gfw.atlassian.net/browse/FLAG-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FLAG-1297 - Fix unresponsive map when panning or zooming

---

components/widgets/forest-change/integrated-deforestation-alerts/index.js
components/widgets/forest-change/integrated-deforestation-alerts/selectors.js

When any individual alert system (GLAD-S2, GLAD-L, RADD) is selected in the [Integrated Deforestation Alerts in Brazil widget](https://gfw.global/3HVq7nm), an extra “high confidence alerts” appears after the widget sentence’s period. This underlined area that produces a modal when a user hovers it should replace the bolded high confidence alerts” text before it. We want users to be able to hover over “high confidence alerts” and see this explanation (“Alerts are classified as high confidence when…”).

[FLAG-1174] Remove repeat words in integrated alerts widget

---

components/recent-imagery/components/recent-imagery-settings/component.jsx

Since the default max cloud cover is 25%, images often won't appear for a location unless the cloud cover % is bumped up. It may not be clear to users that they need to manually increase the max cloud cover percentage if they get the message "We can't find additional images for the selection." Adding a note here such as "increase cloud cover % to retrieve more images" could be helpful.
Steps to Reproduce:
Select [Landsat 8 / Sentinel 2](https://gfw.global/3Fkw3rQ) from the list of available imagery options.
Find a location on the map with no imagery coverage.
The message will read: “We can’t find additional images for the selection.”
If you increase the cloud cover from 25% to 50% or higher, it's likely that the images will appear.
Users may not realize they need to manually increase the …

[FLAG-1304] Add note in cloud cover selector: "Increase cloud cover % to retrieve more images" 

---

components/charts/composed-chart/styles.scss
components/widgets/component.jsx

There is an appearance issue with dashboard widget embeds within all blog posts. [This blog post](https://www.globalforestwatch.org/blog/data-and-research/trends-tree-loss-from-fires-unprecedented-detail/) shows three scroll bars in the TREE COVER LOSS DUE TO FIRES IN RUSSIA embed. This issue surfaced a few months ago and happens across different browsers (chrome, firefox). 
Luis noted this may be because Wordpress adds some sort of styling or that the embed has a defined height; we can add a style/remove default to remove the scroll bar. This is only seen in Windows. 
The three scroll bars that you see to the right of the TCL due to fires in Russia widget shouldn’t be there.

[FLAG-972] Dashboard widget embeds are displayed incorrectly within all blog posts

---

components/widgets/forest-change/_tree-loss-drivers/index.js
components/widgets/forest-change/_tree-loss-drivers/selectors.js
components/widgets/forest-change/tree-loss-drivers/index.js
components/widgets/manifest.js
pages/api/data/[...params].js
services/datamart.js
utils/request.js

FLAG-1263: Data mart api client

---

components/legend/components/legend-item-types/legend-item-type-basic/legend-item-type-basic-item/index.js
components/legend/components/legend-item-types/legend-item-type-basic/legend-item-type-basic-item/styles.scss
components/legend/components/legend-item-types/legend-item-type-basic/styles.scss
providers/datasets-provider/actions.js

Support adding groups of legend items in layer panel items. A legend item is composed of (1) a color swatch, (2) a label, and (3) a statistic.
Groups stack vertically (i.e. flex-direction: column)
Items within a group stack vertically
Groups can have an optional header with the following styles (anything not listed here should be the default for GFW’s typical style):
font-size: 14px
font-weight: bold
There should be a 5px gap between the optional header and the items in the group. This can be achieved though padding, margin, or any other styling that is convenient.
Sample data for a country
Possible values for drivers_type:
- Drivers of temporary disturbances
- Logging
- Shifting cultivation
- Wildfires
- Other natural disturbances
- Drivers of deforestation
- Hard commodities
- Permanent …

[FLAG-1231] Support grouped legend in layer panel item

---

components/widgets/climate/emissions-deforestation-drivers/index.js
components/widgets/forest-change/_tree-loss-drivers/index.js

hide both widgets when user draws a custom area in the map and then goes to the dashboard of that custom area

hide widgets for geostore and aoi types

---

layouts/dashboards/components/header/component.jsx
layouts/dashboards/components/header/styles.scss

Users are finding it difficult to find the global, country, or admin download button on the dashboards. 
To enhance its visibility, we can add a label to the download icon.

[FLAG-1119] Add a label to the data download button

---

components/widgets/manifest.js

In [this Slack thread](https://gfwlcl.slack.com/archives/C0JRCDUQH/p1714415846710529), we discussed hiding the widget for now while the Zeno/LCL team ensure they’re able to examine/save code.

[FLAG-1306] Hide "Land cover change in United States" widget

---

components/forms/newsletter/component.jsx

Completing the Subscribe to the GFW newsletter form from https://www.globalforestwatch.org/subscribe/ no longer leads to the following URL: https://www.globalforestwatch.org/thank-you/ Instead taken here (see the screenshot). After completing the form, can we ensure that the URL changes to https://www.globalforestwatch.org/thank-you/? Our comms team needs that to track campaign conversions.

[FLAG-816] Subscribe to the GFW newsletter URL

---

components/widgets/utils/config.js

The currently displayed button in the integrated deforestation alerts widget doesn’t work correctly. When I click on it for the first time, I believe it shows the correct alert count on the map, but if I readjust the date ranges in the settings and then click this button, the map on the right doesn’t change. See an example for this area: http://www.globalforestwatch.org/dashboards/aoi/606d3074b53b46001b771b48. Or this area: https://gfw.global/440gEa4.
We need to ensure that this button works correctly, everytime a user adjusts date ranges in the settings.

[FLAG-1000] The map visualization of the integrated deforestation alerts widget doesn't reflect the actual alert count

---

components/widgets/climate/emissions-deforestation-drivers/selectors.js

Description: Error occurs when loading statistics for tree cover loss by dominant driver when an administrative area is selected from the map view
Products/Environments Affected: GFW Flagship
Time of occurrence: At least as of Monday
Details: A journalist who is writing a story on the drivers data let me know that the analysis on the platform doesn't seem to be working. I have checked and it appears that when you click on an administrative area on the map and then click 'analyze' with the drivers data selected, an error occurs (see screenshot). The statistics via the dashboard still appear to be working.

[FLAG-1348] Error occurs when loading statistics for tree cover loss by dominant driver

---

layouts/about/impacts/config.js
pages/about.js
services/projects.js

From Will’s work on https://gfw.atlassian.net/browse/FLAG-1336?atlOrigin=eyJpIjoiYzU5OWU4YTIxY2Y2NDQ3ZWI5ZDA2YjkxYzViYTNmOWMiLCJwIjoiaiJ9 , we now know that the “Impacts” section of the https://www.globalforestwatch.org/about/ page pulls from Carto. We’ll want to ensure that we’re able to store this outside of Carto (maybe Wordpress).
Carto is also used to retrieve the list of impact projects shown on the “About” page.
Method: `getImpactProjects`
```
SELECT * FROM gfw_outcomes_for_about_page_images
```

[FLAG-1347] Create new home for "Impact" cards on about page

---

components/widgets/selectors.js

An external user inquired that data appears in the "[Tree Cover Loss in CAR](https://gfw.global/4maO6lg)" widget when the mining concessions filter is selected, however, we do not have mining concessions data for CAR. The mining concession boundaries from Cameroon and Republic of the Congo spill over slightly into CAR which is causing data to appear. We'd like to disable the mining concessions land category filter for all relevant CAR widgets to avoid having this filter option available to users.
Remove the mining concessions filter from all listed CAR widgets below:
- Natural Forests in [Central African Republic]: https://gfw.global/4meZz3i
- Forests in [Central African Republic]: https://gfw.global/4m8DwLB
- Tree Cover in [Central African Republic]: https://gfw.global/3HoiZiO
- Location …

[FLAG-1333] Blacklist the minining concessions intersections for all listed CAR widgets

---

layouts/about/projects/component.jsx

Can we update the following sentence on the about page: https://www.globalforestwatch.org/about/ to say over 8 million users instead of over 4 million users.

[FLAG-1021] update the number of GFW users

---

wrappers/embed/styles.scss

[In this blog](https://www.globalforestwatch.org/blog/data-and-tools/new-drivers-data-forest-loss/), there is a dashboard widget embed where the "Explore on GFW" button is appearing in the middle of the embed instead of at the bottom, cutting off some of the text (see first screenshot). Both the “For more info” and “Explore on gfw” buttons should be moved to the bottom to avoid obstructing the donut chart.

[FLAG-1343] "Explore on GFW" button misplaced in blog widget embed
