wri/gfw

- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/views/layers/WoodFiberPlantationsLayer.js
Following [BC thread](https://basecamp.com/3063126/projects/10726176/todos/308048597), we have updated the tool-tips that display on the Wood Fiber layer.
> Wood Fiber tool-tip update

- app/views/shared/_notifications.html.erb
Addresses issue posted here: [BC thread](https://basecamp.com/3063126/projects/10726176/todos/311259571)
> Update glad notice

- app/assets/javascripts/countries/templates/widgets/annualTreeCoverLoss.handlebars
- app/assets/javascripts/countries/templates/widgets/annualTreeCoverLossLegend.handlebars
- https://www.pivotaltracker.com/story/show/147093605
- https://www.pivotaltracker.com/story/show/147093319
> Delete and fix content texts

- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- https://www.pivotaltracker.com/story/show/147093275
> Fix total cover loss value

- app/assets/javascripts/map/views/layers/IdnWoodFiberPlantationsLayer.js
- app/assets/javascripts/map/views/layers/WoodFiberPlantationsLayer.js
This change:
* Adds an improved tool-tip to the Indonesian Wood Fiber Concessions layer
* It also fixes a bug in general wood fiber layer, that prevented the analysis
> Indonesian wood fiber concessions tooltip

- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
> Fix error on countries page.

- app/assets/javascripts/map/views/layers/IdnWoodFiberPlantationsLayer.js
- app/assets/javascripts/map/views/layers/WoodFiberPlantationsLayer.js
This merges PR #2925 to Master. Relating to [BC thread](https://basecamp.com/3063126/projects/10726176/todos/308048597)
> Merge wood fiber concessions from PR 

- app/assets/javascripts/map/cartocss/IdnForestArea.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/templates/legend/IdnForestArea.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/IdnForestArea.js
Adding new data layer for Indonesia based on [BC thread](https://basecamp.com/3063126/projects/10726176/todos/303918841).
* New table in WRI carto account (forest_area).
(Note, metadata is not hooked up yet, as it doesn't exist.)
> New: Indonesia Forest Area Layer

- app/assets/javascripts/countries/templates/countryDashboard.handlebars
- app/assets/javascripts/countries/templates/widgets/treeCoverGain.handlebars
- https://www.pivotaltracker.com/story/show/147093559
> change texts

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/views/layers/FormaCoverageLayer.js
- app/views/shared/_sources_map.html.erb
Added geographic coverage layers and metadata to `Forma alerts` and `Forma Active Clearing Alerts`.
> Forma geographic coverage layers

- app/assets/javascripts/common/views/LineGraphView.js
- app/assets/javascripts/countries/views/widgets/TreeCoverLossAlertsView.js
Add:
- Follow mouse and move the dot element.
> Move dot/circle on line graphs.

- app/assets/javascripts/common/views/GroupedGraphView.js
- app/assets/javascripts/common/views/PieGraphView.js
- app/assets/javascripts/countries/templates/countryTooltip.handlebars
- app/assets/javascripts/countries/views/CountryShowView.js
- app/assets/stylesheets/countries.scss
- app/assets/stylesheets/modules/common/charts/_pie-chart.scss
- app/assets/stylesheets/modules/countries/_tooltip.scss
- Include function on donut chart.
- Changes values when changing the zone.
- Disappear tooltip function.
- Follow tooltip function.
> Tooltip on donut and bars chart.

- app/assets/javascripts/countries/templates/widgets/treeCoverReforestation.handlebars
- app/assets/javascripts/countries/views/widgets/TreeCoverReforestationView.js
- app/assets/stylesheets/modules/countries/widgets/_tree-cover-reforestation.scss
Add
- Ranking reforestation
Before:
After:
> Include reforestation rate ranking

- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/views/ShareView.js
- https://www.pivotaltracker.com/story/show/147207041
> Change name events.

- app/assets/javascripts/common/views/GroupedGraphView.js
- app/assets/stylesheets/modules/countries/_tooltip.scss
- Include units on the tooltip.
- Fix problems with integer yaxis values.
- https://www.pivotaltracker.com/story/show/147828167
> Fix group-graph features.

- app/assets/javascripts/common/views/GroupedGraphView.js
- app/assets/javascripts/common/views/PieGraphView.js
- app/assets/javascripts/countries/templates/countryTooltip.handlebars
- app/assets/javascripts/countries/templates/widgets/annualTreeCoverLoss.handlebars
- app/assets/javascripts/countries/templates/widgets/modals/treeCoverLossModal.handlebars
- app/assets/javascripts/countries/templates/widgets/treeCoverLoss.handlebars
- app/assets/javascripts/countries/templates/widgets/treeCoverLossRanking.handlebars
- app/assets/javascripts/countries/templates/widgets/treeCoverReforestation.handlebars
- app/assets/javascripts/countries/views/CountryHeaderView_old.js
- app/assets/javascripts/countries/views/CountryOverviewView.js
- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- app/assets/javascripts/countries/views/widgets/TreeCoverGainView.js
- app/assets/javascripts/countries/views/widgets/TreeCoverView.js
- https://www.pivotaltracker.com/story/show/147832831
> Change Ha to ha

- app/assets/javascripts/countries/helpers/StickyMap.js
- app/assets/javascripts/countries/templates/widgets/legendMap.handlebars
- app/assets/javascripts/countries/views/widgets/MapCountry.js
- app/assets/stylesheets/modules/countries/_country-page-legend.scss
- app/assets/stylesheets/modules/countries/_show.scss
- app/views/shared/icons/_svg_icons_countries.html.erb
- Add custom controllers on the map.
- Add a custom function to make zoom.
- Functions to see always the zoom control on top o bottom.
- https://www.pivotaltracker.com/story/show/147828185
> Fix zoom controllers

- app/assets/javascripts/common/views/GroupedGraphView.js
- https://www.pivotaltracker.com/story/show/147833577
> include commas on values

- app/assets/javascripts/countries/templates/widgets/legendMap.handlebars
- app/assets/javascripts/countries/views/widgets/MapCountry.js
> Change switch colors

- app/assets/javascripts/countries/views/widgets/AnnualTreeCoverLossView.js
- https://www.pivotaltracker.com/story/show/147845589
> fix bug on total values and group graph

- app/assets/javascripts/countries/templates/widgets/treeCoverLossRanking.handlebars
- app/assets/javascripts/countries/views/widgets/TreeCoverLossRankingView.js
- https://www.pivotaltracker.com/story/show/147843837
> Change text

- app/assets/javascripts/map/cartocss/IdnForestArea.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/templates/legend/IdnForestArea.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/IdnForestArea.js
Relates to this [BC issue](https://basecamp.com/3063126/projects/10726176/todos/303918841#comment_539259672).
* Adds Indonesian Forest Area to Indonesian country data on GFW map.
* Updated Layerspec
* Removed analyse/subscribe buttons from info window
> Disposable Indonesian forest area

- app/assets/javascripts/map/cartocss/palm_oil_mills.cartocss
Mikela asked us to change:
* the size of the points at various Z levels
* change the colour to higher visibility
> Palm oil mills layer: style changes

- app/assets/javascripts/map/templates/legend/glad.handlebars
- app/assets/javascripts/map/templates/legend/legend.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/views/SourceModalView.js
- app/assets/stylesheets/layouts/_embed-map.scss
- app/assets/stylesheets/modules/map/_layer-nav.scss
- app/assets/stylesheets/modules/map/_module-legend.scss
- app/assets/stylesheets/modules/map/_onoffswitch.scss
- Tooltip shadow.
- Change circle´s colors when the layer is hidden.
- Change cursor pointers on the eye icon and switch options.
- Change text color on switch options.
- Fix icon error on animation and colors.
- Change icon styles when the layer is hidden.
> Fix legends styles

- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/templates/legend/idnSuitability.handlebars
- app/assets/javascripts/map/views/LegendView.js
- app/assets/javascripts/map/views/layers/IdnSuitabilityLayer.js
> Indonesian Palm Oil Suitability map

- app/assets/javascripts/map/views/LegendView.js
- app/assets/stylesheets/modules/map/_layer-nav.scss
-Different functions for countries and the other layers.
> Fix countries selector on plantations option

- app/assets/javascripts/map/views/maptypes/landsatMaptype.js
> changed max zoom on landsat 2015 and 2016 to z17

- app/assets/javascripts/helpers/datasetsHelper.js
#	app/assets/javascripts/helpers/datasetsHelper.js
> Fix dataset names

- app/assets/javascripts/map/views/layers/CanMiningLayer.js
Do not merge to MASTER. The data source and layer for staging for Canadian mining data is now different [by request](https://basecamp.com/3063126/projects/10726176/todos/311612858).
> Regressed Canadian mining data to older version (only for staging)

- app/assets/javascripts/map/views/layers/CanMiningLayer.js
Applies PR #2996 to master, to revert Canadian mining layer back to correct data.
> Regressed Canadian mining data layer

- app/assets/javascripts/map/views/MapView.js
- app/assets/javascripts/map/views/maptypes/landsatMaptype.js
> Disposable/apply Landsat 2013 2014

- app/assets/javascripts/map/views/layers/RaisgLayer.js
- app/assets/javascripts/map/views/layers/RaisgMiningLayer.js
[BC thread](https://basecamp.com/3063126/projects/10726176/messages/71119648#events_message_71119648)
Issue around RAISG WMS data. They have some bad encoding on a layer they updated that is messing with our layer styles. 
* This verifies that switching to default style still shows the data.
* WMS server also changed url.
Only partial fix (don't merge to master)
> Styles are the problem - reverted to default

- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/views/layers/RaisgLayer.js
- app/assets/javascripts/map/views/layers/RaisgMiningLayer.js
This merges PR #3005 and #3006 to deactivate the RASG layers and remove them from the menus.
> Disposable/remove RASG layers

- app/controllers/landing_controller.rb
fires is now global so I removed the part about the ASEAN region
> update fires text

- app/assets/stylesheets/modules/map/_module-legend.scss
> Add arrow on selects

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/helpers/layersHelper.js
- app/assets/javascripts/map/models/LayerSpecModel.js
- app/assets/javascripts/map/views/layers/BraSoyCerradoLayer.js
[Basecamp thread](https://basecamp.com/3063126/projects/10726176/todos/311103798). Merges PR #2988 .
> Added brazilian soy in cerrado data layer

- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/global_land_cover.handlebars
- app/assets/javascripts/map/views/layers/GlobalLandCoverLayer.js
[BC Thread](https://basecamp.com/3063126/projects/10726176/todos/302645619)
* Changed to 2015 source
* Changed legend
> Updated Land Cover data 

- app/assets/javascripts/map/templates/layersNav.handlebars
* Tweak to subtitle in menu to change `(2015)` to `(ESA CCI, 2015)`
> Modified subtitle of new Landcover layer according to request

- app/assets/javascripts/map/views/MapView.js
- package-lock.json
- Fix error when modal close clicking on the background.
(No demo)
(No notes)
- Open "More" dashboard.
- Click at the bottom (background).
- Test that menu continues visible.
> fix map error when close dash board

- app/controllers/landing_controller.rb
> Moves forest watcher to first position and updates link

- app/assets/stylesheets/components/country/_c-widget-tree-cover-gain.scss
- app/assets/stylesheets/country.scss
- app/javascript/pages/country/actions.js
- app/javascript/pages/country/components/root/root-component.js
- app/javascript/pages/country/components/widget-tree-cover-gain/widget-tree-cover-gain-actions.js
- app/javascript/pages/country/components/widget-tree-cover-gain/widget-tree-cover-gain-component.js
- app/javascript/pages/country/components/widget-tree-cover-gain/widget-tree-cover-gain-reducers.js
- app/javascript/pages/country/components/widget-tree-cover-gain/widget-tree-cover-gain.js
- app/javascript/pages/country/initial-state.js
- app/javascript/pages/country/reducers.js
- Structure for cover gain widget.
(No notes)
(No testing)
> Include cover gain widget structure

- app/assets/stylesheets/components/country/_c-footer.scss
- app/assets/stylesheets/components/country/_c-widget-stories.scss
- app/assets/stylesheets/country.scss
- app/javascript/pages/country/actions.js
- app/javascript/pages/country/components/root/root-component.js
- app/javascript/pages/country/components/widget-stories/widget-stories-actions.js
- app/javascript/pages/country/components/widget-stories/widget-stories-component.js
- app/javascript/pages/country/components/widget-stories/widget-stories-reducers.js
- app/javascript/pages/country/components/widget-stories/widget-stories.js
- app/javascript/pages/country/initial-state.js
- app/javascript/pages/country/reducers.js
- package-lock.json
- Widget stories structure/styles.
(No testing)
> include widget stories structure

- app/assets/stylesheets/components/country/_c-loading.scss
- app/assets/stylesheets/components/country/_c-widget-plantation-area.scss
- app/assets/stylesheets/components/country/_c-widget-tree-located.scss
- app/assets/stylesheets/country.scss
- app/javascript/pages/country/components/root/root-component.js
- app/javascript/pages/country/components/widget-plantation-area/widget-plantation-area-component.js
- app/javascript/pages/country/components/widget-tree-located/widget-tree-located-component.js
- app/javascript/pages/country/components/widget-tree-loss/widget-tree-loss-component.js
- Improve height and width for loading banner.
- Responsive charts.
- Include scroll button on widgets.
- Improve some styles.
- Responsive charts.
(No notes)
(No testing)
> Styles loading, scroll, charts

- app/views/shared/_notifications.html.erb
https://basecamp.com/3063126/projects/10726176/todos/325670048
> Updates notification for GLAD alerts

- app/javascript/pages/country/components/widget-tree-cover-loss-areas/widget-tree-cover-loss-areas-settings-component.js
- app/javascript/pages/country/components/widget-tree-cover/widget-tree-cover-settings-component.js
- app/javascript/pages/country/components/widget-tree-located/widget-tree-located-settings-component.js
- app/javascript/pages/country/components/widget-tree-loss/widget-tree-loss-settings-component.js
- package-lock.json
- package.json
- Fix canopy select´s values.
When value is 0.
Before:
After:
(No notes)
(No testing)
> fix canopy select options on widgets

- app/assets/javascripts/map/templates/layersNav.handlebars
Based on [Basecamp thread](https://basecamp.com/3063126/projects/10726176/todos/328118052#comment_568894985) we have updated the sub-title of ESA 2015 landcover data.
> Updated subtitle for landcover 2015 ESA data

- app/assets/javascripts/map/services/GladDateService.js
Updates GLAD dataset as provided by Charlie from WRI.
- Going to the map and toggling on GLAD alerts should show data in the map;
- GLAD timeline should also work when played;
> Updates GLAD dataset id

- app/views/landing/index.html.erb
- app/views/layouts/countries.html.erb
- app/views/shared/_footer_landing.erb
Brings missed commit to production.
> Removes duplication of social links from the footer

- app/assets/javascripts/map/templates/layersNav.handlebars
- Removes option that shouldn't have been deployed to production.
> Remove wrongfully deployed menu item

- app/assets/javascripts/landing/views/CoverView.js
Deploy fix to the home video stop issue.
> Fix stop video button

- app/views/layouts/small_grants_fund.html.erb
- app/views/small_grants_fund/_gfw_assets.html.erb
We don't need all the menu items, so I separated it from the global one and used a smaller version of that file, instead of adding another check, it's using a different layout anyway.
> Small grants fund menu works differently

- app/assets/javascripts/map/services/PlaceService.js
This PR addresses this [BC thread](https://basecamp.com/3063126/projects/10728552/todos/327509924) - by adding Tree cover 2000 to the map by default.
> Added tree cover 2000 by default to map

- app/views/shared/_sources_map.html.erb
See [BC thread](https://basecamp.com/3063126/projects/10728552/todos/243955671):
* Added extra info to the download tool regarding WKT format
> Add extra info to the shape upload tool

- app/assets/javascripts/map/services/LayerSpecService.js
Starting to try and address issues in [BC thread](https://basecamp.com/3063126/projects/10728552/todos/331321730) related to forbidden combinations of layers. (This may be only a partial fix, and require further testing.)
> Layer combination exceptions

- app/assets/javascripts/map/services/LayerSpecService.js
Quick fix so that no two Forest Change Layers can be viewed simultaneously (except gain/loss layers!)
> Forest Change Layer bugfix

- app/assets/stylesheets/components/about/_c-about-contactus.scss
- app/assets/stylesheets/components/about/_c-about-cover.scss
- app/assets/stylesheets/components/about/_c-about-impacts.scss
- app/assets/stylesheets/components/about/_c-about-modal-world.scss
- app/javascript/pages/about/components/AboutAnchors/AboutAnchors.jsx
- app/javascript/pages/about/components/AboutContactUs/AboutContactUs.js
- app/javascript/pages/about/components/AboutImpacts/AboutImpacts.jsx
- app/javascript/pages/about/components/AboutModals/AboutModalWorld.jsx
- app/javascript/pages/about/components/AboutUsers/AboutUsers.jsx
(No demo)
(No notes)
(No testing)
> Bugs, quick changes & UI improvements

- app/assets/stylesheets/layouts/_embed-map.scss
Small fix to show header correctly in embeds
> remove absolute positioning of map on embeds

- app/assets/stylesheets/global/_base.scss
- app/assets/stylesheets/layouts/_header.scss
This changes fixes the map height on mobile.
> fix mobile styles for map

- app/assets/javascripts/map/templates/infowindow.handlebars
- app/assets/javascripts/map/views/layers/Places2WatchLayer.js
This PR adds tracking for the PTW infowindow
> PTW trackings

- app/assets/stylesheets/layouts/_map.scss
This code remove the repositioning  of the header that the previous header needed
> fix map header position

- app/assets/javascripts/map/cartocss/MangroveWatch.cartocss
- app/assets/javascripts/map/services/LayerSpecService.js
- app/assets/javascripts/map/templates/layersNav.handlebars
Finishes off the new Mangrove layer started in PR #2736 , and discussed in [BC thread](https://basecamp.com/3063126/projects/10726176/todos/294291962).
Layerspec has been changed accordingly.
> updated mangrove watch layer

- app/javascript/pages/country/widget/widgets/widget-tree-loss/widget-tree-loss.js
Use the extent year like variable in the sentence
> use extentYear like variable

- app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
- app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
- app/assets/javascripts/map/presenters/tabs/AnalysisNewPresenter.js
- app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
Merges PR #3201 to Master which adds Tree Cover analysis 2010 layer front end connection.
> Adds analysis capability to Tree Cover 2010 layer

- app/javascript/components/scroll-to/scroll-to.js
- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/header/header.js
- app/javascript/pages/country/root/root-component.js
- app/javascript/pages/country/root/root.js
- app/javascript/pages/country/widget/components/widget-bar-chart/widget-bar-chart-component.js
- app/javascript/pages/country/widget/components/widget-chart-tooltip/widget-chart-tooltip-component.js
- app/javascript/pages/country/widget/components/widget-chart-tooltip/widget-chart-tooltip-styles.scss
- app/javascript/pages/country/widget/components/widget-header/widget-header.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss-plantations/widget-tree-loss-plantations-actions.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss-plantations/widget-tree-loss-plantations-component.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss-plantations/widget-tree-loss-plantations-selectors.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss-plantations/widget-tree-loss-plantations.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss/widget-tree-loss-selectors.js
- app/javascript/utils/calculations.js
Sometime you need to see something. You might not know what it is, or where it is, but some proactive chump has sent you a link with a fancy #link in it and you just NEED to check it out. Luckily we got your back FAM. Introducing the new ScrollTo component.
This cheeky chap takes a target element, scrolls to it, highlights it with a dope animation, and then removes the highlight a few seconds later. Now you are always going to find what you are looking for.
My machine is playing up so taking a gif is tricky. Please go to `/country/BRA#treeCover`
> scroll to component to target and highlight div

- app/javascript/components/modal-meta/modal-meta-component.jsx
- app/javascript/components/modal-meta/modal-meta.js
Update modal to use correct fields as per request.
> update modal to show correct fields

- app/controllers/landing_controller.rb
Link was pointing to the old URL of developers corner
> Update link on homepage 

- app/javascript/pages/country/widget/widgets/widget-tree-cover-plantations/widget-tree-cover-plantations-selectors.js
> fix widget when doesn't have more than 1 result

- app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts-selectors.js
I know you like cool graphs. But how about _correct_ cool graphs!?
Well, straight outta Porto, I've got the hottest PR that'll bring the thickest standard deviation bounds to your statistical means - even for countries without any deforestation alerts before 2017!
Now countries like Suriname, French Guiana, and even lesser know admins of Brazil will always show the correct graph, means and standard deviations... **100% guaranteed**.
TLDR:
- No longer returns zero standard deviation in no alerts before 2017
- Fixes date bounds
- Fills zeros in years with no data
> Fix GLADS graph calcs

- app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts-selectors.js
- app/javascript/pages/country/widget/widgets/widget-ranked-plantations/widget-ranked-plantations-selectors.js
A quick update to make the statements about plantation species & type more consistent.
> Updates dynamic sentence for consistency between type and species

- app/assets/javascripts/map/templates/legend/bra_mapBiomas.handlebars
- app/assets/javascripts/map/views/layers/BraMapBiomasLayer.js
Simply updates the colour palette of the layer.
> Updates colour palette for Brazil Land Cover layer and legend

- app/javascript/pages/country/widget/widgets/widget-intact-tree-cover/widget-intact-tree-cover-selectors.js
- app/javascript/pages/country/widget/widgets/widget-primary-tree-cover/widget-primary-tree-cover-selectors.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover/widget-tree-cover-selectors.js
Updates Extent widgets according to [this](https://basecamp.com/3063126/projects/10727890/todos/340010987#comment_595534096) basecamp thread.
Please test on local! I was unable to do so due to config mismatch.
> Sentence change.

- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/header/header-component.js
- app/javascript/pages/country/root/root-selectors.js
- app/javascript/pages/country/widget/widget-component.jsx
- app/javascript/pages/country/widget/widgets/widget-emissions/widget-emissions.js
- app/javascript/pages/country/widget/widgets/widget-fao-cover/widget-fao-cover.js
- app/javascript/pages/country/widget/widgets/widget-fao-reforestation/widget-fao-reforestation.js
- app/javascript/pages/country/widget/widgets/widget-fires/widget-fires.js
- app/javascript/pages/country/widget/widgets/widget-gain-located/widget-gain-located.js
- app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts.js
- app/javascript/pages/country/widget/widgets/widget-intact-tree-cover/widget-intact-tree-cover.js
- app/javascript/pages/country/widget/widgets/widget-loss-located/widget-loss-located.js
- app/javascript/pages/country/widget/widgets/widget-primary-tree-cover/widget-primary-tree-cover.js
- app/javascript/pages/country/widget/widgets/widget-ranked-plantations/widget-ranked-plantations.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover-plantations/widget-tree-cover-plantations.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover/widget-tree-cover.js
- app/javascript/pages/country/widget/widgets/widget-tree-gain/widget-tree-gain.js
- app/javascript/pages/country/widget/widgets/widget-tree-located/widget-tree-located.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss-plantations/widget-tree-loss-plantations.js
- app/javascript/pages/country/widget/widgets/widget-tree-loss/widget-tree-loss.js
- Remove widget color dependancy as it is now global
- Fix prop types bug
> stop repeating colors, fix bug with prop types

- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/widget/components/widget-settings/widget-settings-component.jsx
* modified widget order
* changed pages of some widgets
* changed Tree cover extent to extent year in settings menu
* hooked up several missing metadata slugs
> various settings changes and metadata hook-ups requested by clients

- app/javascript/services/country.js
- app/javascript/services/total-area.js
Modified SQL for admin-1 level name and area retrieval
> updated sql to new table

- app/javascript/pages/country/data/widgets-config.json
Added missing metadata slugs from Mikaela [BC thread](https://basecamp.com/3063126/projects/10727890/todos/335196351#comment_597118313)
> added two missing metadata slugs

- app/javascript/pages/country/data/widgets-config.json
Changed DRC to correct iso code (COD)
> Corrected DRC iso code to COD

- app/javascript/components/map/components/mini-legend/mini-legend-component.jsx
- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/widget/components/widget-header/widget-header-component.js
- app/javascript/pages/country/widget/widgets/widget-tree-gain/widget-tree-gain-selectors.js
> Bugfix/tool tips and menu order (#3274)

- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts-actions.js
- app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts-selectors.js
- app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts.js
- app/javascript/services/glad.js
Fixes the issue with GLAD alerts not finding the latest date. Now we use the /latest end point to get this and fill zeros up until there.
> use latest endpoint to get last date of glads

- app/javascript/pages/country/data/indicators.json
- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/widget/widget-selectors.js
Sort the indicators in the selector by whether they are an intersection or not
> sort indicators labels by intersection or not

- app/assets/stylesheets/global/_base.scss
Finally fix that awful white background below the map layer menu
> fix map layers menu background issue

- app/assets/javascripts/map/templates/layersNav.handlebars
Remove layers from staging:
```
Peru MINAM tree cover loss
Mangrove Change
WWF Terrestrial ecoregions
Verified Carbon standards
```
> remove unneeded layers from menu

- app/assets/javascripts/map/templates/legend/bra_mapBiomas.handlebars
- app/assets/javascripts/map/views/layers/BraMapBiomasLayer.js
Updates colours and adds categories as per this Basecamp [thread](https://basecamp.com/3063126/projects/10726176/todos/340053669#comment_594550497).
Needs to go to prod asap!
> Updates colours and adds new categories

- app/assets/javascripts/map/templates/legend/glad.handlebars
- app/assets/javascripts/map/views/LegendView.js
Fixes the issue of Places to Watch toggles not changing when the user selects them.
> check for toggled layers in templates and layers

- app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
Add flag to check for glads layers when adding green dots to glads calendar
> remove green dots from glad calendar

- app/javascript/pages/country/data/analytics.js
- app/javascript/pages/country/widget/components/widget-header/widget-header-component.js
Quick PR to add widget settings tracking to GA.
> add custom ga events for tracking widget settings

- app/javascript/pages/country/meta/meta-component.jsx
- app/javascript/services/country.js
- app/models/country.rb
Update the fetches for the rails country helper to use the latest gamd28 tables instead of the old API (which doesn't exist).
> update rails country model to use gadm28 tables for country names

- app/javascript/pages/country/data/widgets-config.json
- app/javascript/pages/country/reducers.js
- app/javascript/pages/country/widget/widget-actions.js
- app/javascript/pages/country/widget/widget-component.jsx
- app/javascript/pages/country/widget/widgets/widget-tree-cover-ranked/widget-tree-cover-ranked-actions.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover-ranked/widget-tree-cover-ranked-component.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover-ranked/widget-tree-cover-ranked-reducers.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover-ranked/widget-tree-cover-ranked-selectors.js
- app/javascript/pages/country/widget/widgets/widget-tree-cover-ranked/widget-tree-cover-ranked-styles.scss
- app/javascript/pages/country/widget/widgets/widget-tree-cover-ranked/widget-tree-cover-ranked.js
- app/javascript/services/forest-data.js
New widget to show tree cover ranked by admin 0 level.
> Feature: tree cover ranked widget

- app/assets/javascripts/map/templates/layersNav.handlebars
Adds logic statement to hide biodiversity layers toggle on PROD.
> Hides biodiversity layers from PROD temporarily

- app/assets/javascripts/map/templates/layersNav.handlebars
- app/assets/javascripts/map/templates/legend/biodiversity_completeness.handlebars
- app/assets/javascripts/map/templates/legend/biodiversity_intactness.handlebars
Swaps the default view from *intactness* to *significance*.
Adds 'Forest' to layer name.
> Biodiversity Layer Update

- app/assets/javascripts/map/cartocss/IdnForestArea.cartocss
- app/assets/javascripts/map/views/layers/IdnForestArea.js
One of our layers stopped working due to a change to table column names. This PR fixes that change.
> Indonesian forest area layer update

- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
Fixes dynamic sentences for tree cover extent and extent ranked widgets.
> QA for Tree Cover Widgets

- app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
Small fixes to Loss, Gain and GLAD widgets.
> Fixes dynamic sentences for Loss, Gain, Glad.

- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
Fixes global state for gain widget.
- Dynamic sentences now render correctly at global level
- Corrects % calculations
> Fixes global gain widget

- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Grabs correct meta data and successfully renders ranked list.
> Hot Fix for global tree cover located

- app/javascript/components/widgets/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/actions.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Path links now work correctly. Widget renders in all dashboards.
> Fixes Tree-Cover-located widget in all dashboards

- app/javascript/components/widgets/components/widget-numbered-list/component.jsx
- app/javascript/components/widgets/components/widget/widget.js
- app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
- % is now the default for all ranked lists.
- Ups # of sig figs to 2(%) and 3(ha)
> Default setting for ranked lists

- app/javascript/components/widgets/components/widget/widget.js
- app/javascript/components/widgets/widgets/land-cover/fao-cover/actions.js
- app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
- app/javascript/pages/country/header/header.js
- app/javascript/services/forest-data.js
Fixes/Updates FAO cover widget in line with staging version.
> Fixes calculations for fao cover

- app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
Fixes maths issues and adds logic checks for null values.
> Fao cover pie pt.2

- app/javascript/components/widgets/widgets/climate/emissions/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/fao-deforest/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/fao-reforest/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/fao-cover/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
First round of Dynamic Sentence, titles and default settings updates.
> Updates dynamic sentences and defaults

- app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/actions.js
- app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
- app/javascript/components/widgets/widgets/land-cover/primary-forest/actions.js
- app/javascript/components/widgets/widgets/land-cover/primary-forest/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
Fixes both widgets to handle new Forest Type / Land Category indicators.
Also bundles in new dynamic sentences.
> Fix - intact & primary widgets

- app/javascript/components/widgets/widgets/forest-change/tree-loss-global/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/fao-cover/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
> Global sentences updates

- app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
- Updates global dynamic sentences
- Fixes maths issue when unit = %
- Updates while loop logic across all affected widgets
> Fix cover located list

- app/javascript/pages/dashboards/header/header-selectors.js
Adds logic to remove plantations info from header sentence when on Global Dashboard.
> Updates global header

- app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/actions.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/actions.js
Updates widget to use forestType instead of indicator.
> Plantations loss

- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
Simply updates titles in line with feedback.
> Updates titles

- app/javascript/components/widgets/components/widget-settings-statement/widget-settings-statement-selectors.js
- app/javascript/components/widgets/widgets/forest-change/fao-deforest/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/fao-reforest/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/fires/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/glad-alerts/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
Firstly, I like the branch name.
Secondly, this PR contains many default updates including:
- Reordering the Forest Change tab
- Adding logic for when there is no intact forest
- adding/removing settings options
> Random assortment of updates

- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Replaces percentages like 0.0000045% with '<0.1%'
> Fixes small percent

- app/javascript/pages/dashboards/header/header-component.js
- app/javascript/pages/dashboards/header/header.js
Dashboards download link for the global route was failing. Updated to remove iso.
> Fix: download global data

- app/javascript/components/widgets/actions.js
- app/javascript/pages/dashboards/analytics.js
Updates the GA event for the widget settings menu to now:
- Send the widget 
- Send the selector changed
- Send the settings value that has changed
This should allow us to analyse better how to improve the widget settings 💯
> Feature: GA events for widget settings menu

- app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
- app/javascript/pages/dashboards/header/header-selectors.js
Updates dynamic sentences as per feedback, as well as fixing a bug on PROD where units appear as undefined on gain ranking widgets.
Deploy to master ASAP!
> Minor Feedback Updates

- app/assets/javascripts/map/views/layers/LossLayer.js
Update url for tiles and extent timeline
> Update loss layer to have 2017 data

- app/assets/javascripts/map/services/AnalysisNewService.js
Prepare yourself for the largest commit in history! This is a truly groundbreaking feature.
Updates admin analysis to use gadm36 tables...
> GADM36: Update Analysis to /v3/

- app/assets/javascripts/map/services/AnalysisNewService.js
Ensures response data is parsed with the same schema regardless of request.
> [ANALYSIS] Parses response data correctly

- app/assets/javascripts/map/templates/layersNav.handlebars
A thrilling update to the primary forest layer.
> Added subtitle to primary forests

- app/javascript/components/widgets/widgets/forest-change/fires-alerts/selectors.js
Resets latest week to latest fires data updates (currently -5 weeks)
> [FIRES STATS] Updates latest date

- app/javascript/components/widgets/widgets/land-cover/global-land-cover/initial-state.js
> Updates land cover widget metadata key

- app/controllers/landing_controller.rb
Change descriptive text on "Be the first to see new deforestation" card to "Subscribe and get email notifications straight to your inbox as forest clearing happens in select countries."
>  edits to "be the first to see new deforestation" card

- app/javascript/components/map/components/legend/legend-styles.scss
- app/javascript/pages/map/data-analysis-menu/styles.scss
Makes the data analysis menu scrollable with a fixed tab menu header.
> data menu scrolable with fixed header

- app/javascript/pages/dashboards/header/header-reducers.js
- app/javascript/pages/dashboards/header/header-selectors.js
Adds a `global` condition to the header sentence.
> Add global sentence to header

- app/javascript/components/widgets/components/widget-header/widget-header.js
- app/javascript/components/widgets/components/widget-settings/widget-settings-component.jsx
- app/javascript/components/widgets/widgets/climate/emissions-deforestation/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/primary-forest/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
A few updates to dynamic sentences and the header as per feedback. Also updates a few indicator defaults.
> Header and dynamic sentence fixes

- app/javascript/pages/dashboards/header/header-actions.js
- app/javascript/pages/dashboards/header/header-reducers.js
- app/javascript/pages/dashboards/header/header-selectors.js
For countries with plantations, subtracts plantations extent from total to give Natural Forest.
> Calculates natural forest for header in plantations countries

- app/javascript/pages/dashboards/header/header-actions.js
- app/javascript/pages/dashboards/header/header-reducers.js
- app/javascript/pages/dashboards/header/header-selectors.js
Indonesia requires a bespoke header. This does that.
Adds:
- primary forest loss fetch
- indonesia sentence
- logic and data parsing for primary forest in IDN
APPROVED
> Adds IDN-specific header sentence

- app/javascript/components/widgets/manifest.js
- app/javascript/components/widgets/widgets/forest-change/fires/initial-state.js
Goodbye fires. We barely knew ye.
🔥 ⚰️ 🔥  
NOTE: Should we delete the code? May be useful in the future...
> Removes 7-day fires widget

- app/javascript/components/map/components/mini-legend/mini-legend-component.jsx
> Remove dot, indent left

- app/javascript/components/modals/meta/meta-styles.scss
- app/javascript/components/ui/dynamic-sentence/dynamic-sentence-component.jsx
- app/javascript/components/ui/dynamic-sentence/dynamic-sentence-styles.scss
- app/javascript/components/widgets/components/widget-footer/component.jsx
- app/javascript/components/widgets/components/widget/component.jsx
- app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-tsc/initial-state.js
- app/javascript/components/widgets/widgets/forest-change/tree-loss-tsc/selectors.js
Adds ability to add a component replacement in the dynamic sentence component. Also updates config for TSC widget to make this happen.
> dynamic sentences with components

- app/javascript/pages/map/components/menu/menu-sections.js
Create conservation subheading under land use
API should be updated
- After API update the new conservation subheading should appear.
> Create conservation subheading under land use

- app/assets/javascripts/map/cartocss/style.cartocss
- app/assets/javascripts/map/views/layers/GladCoverageLayer.js
- app/javascript/components/map/assets/cartocss/style.cartocss
Updates glad extent and coverage
> Update Extended GLADs

- app/javascript/components/widgets/widgets/land-use/economic-impact/selectors.js
> Change <0.1 string

- app/javascript/components/map-v2/components/data-analysis-menu/component.jsx
- app/javascript/components/map-v2/components/data-analysis-menu/reducers.js
- app/javascript/components/map-v2/components/data-analysis-menu/selectors.js
Allow data/analysis menu to be totally collapsable
Test both buttons and verify that any scenario is working as expected.
> Allow data/analysis menu to be totally collapsable

- app/javascript/components/widgets/widgets/forest-change/glad-alerts/selectors.js
Datasets for each country begin at different years, so we need to find the first (full) year with non-zero values.
> Adds dynamic min year to Glad-stats widget

- app/javascript/components/map-v2/components/analysis/components/draw-analysis/component.jsx
- app/javascript/components/map-v2/components/analysis/components/draw-analysis/selectors.js
Only showing the analysis message "This algorithm approximates the results by sampling the selected area. Results are more accurate at closer zoom levels." when you are zoomed out (on zoom levels 0 to 10).
> Showing disclaimer for analysis data from Z0-Z10 only

- app/controllers/landing_controller.rb
Quick update to the home page related to changes in the cards order & content.
> Small changes on homepage cards

- app/javascript/providers/datasets-provider/datasets-decode-config.js
- app/javascript/providers/datasets-provider/datasets-provider-actions.js
Allows timeline to render without decodeFunction.
> Fix decode error

- app/javascript/components/widgets/widgets/biodiversity/intactness/selectors.js
Simple update to category names to _"High, Medium-high, Medium Medium-low, Low"_
> Update category names

- app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
Adds "CO₂/C emissions" to pie chart label to match the sentence.
> Fixed units in the graph to show more detail

- app/javascript/pages/sgf/section-about/section-about-component.jsx
This PR adds sharable anchor links to the sections ("small-grants-fund", "tech-fellowship" and "support") in SGF's About tab.
> Added anchor links to sections in SGF About tab

- app/javascript/pages/sgf/section-apply/section-apply-component.jsx
Updated link to 2019 webinar and deleted application deadline notice.
> 2019-section-apply-comment

- app/javascript/components/maps/components/basemaps/basemaps-component.jsx
- app/javascript/components/maps/components/basemaps/basemaps.js
- app/javascript/components/maps/components/basemaps/styles.scss
Added basemap metadata info button to the basemaps tooltip window, as in the recent imagery tooltip.
> Added basemap metadata info button to the tooltip

- app/javascript/components/ui/datepicker/datepicker-component.js
Fixes bug in GLAD alerts and similar related to the time interval selector calendar malfunctioning.
> Fixed an issue with the datepicker dropdowns showing the wrong month

- app/javascript/pages/about/section-projects/section-projects-component.jsx
Changing the wording so that it doesn't sound like 1.5 million people launched in 2014
> Updating wording

- app/javascript/pages/sgf/section-apply/section-apply-component.jsx
Updated text regarding application opening dates, as deadlines for the SGF and tech fellowship have both passed.
> updated application information

- app/javascript/components/maps/components/menu/menu-sections.js
...that's about it. Let's keep not deploy to prod until all changes are made to layer. For now, staging only.
> Changes biodiv/consv tab to biodiv/biodiv

- app/javascript/components/footer/footer-component.jsx
- app/javascript/components/header/component.jsx
- app/javascript/components/header/components/submenu-panel/component.jsx
- app/javascript/components/header/components/submenu-panel/styles.scss
- app/javascript/components/header/index.js
Adds contact us link to open modal to header
> Feature: add contact us to header

- app/javascript/components/widgets/widgets/climate/cumulative-emissions/config.js
Adds correct endpoint to config 👇
> Adds metadata to widget

- README.md
* plus some minor change on paragraph #114
Some typos fixed on this `readme.md` file
There is no need to show this minor PR.
There is no notes appended to this PR.
-- There is no break on code. Just fixing some typos found. No collateral damage over the horizon.
> Syntax issue on #66

- app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
Updates GLAD ranked widget to accept new sql. Fixes some existing bugs.
> Make glad ranked compatible with new sql

- app/javascript/components/forms/form-styles.scss
- app/javascript/components/maps/components/analysis/components/chose-analysis/component.jsx
- app/javascript/components/maps/components/analysis/components/chose-analysis/styles.scss
- app/javascript/components/maps/main-map/components/map-controls/map-controls-styles.scss
- app/javascript/components/maps/map/components/popup/component.js
- app/javascript/components/maps/map/components/popup/styles.scss
- app/javascript/components/modals/share/share-styles.scss
Small visual bug present in the "Start drawing" button in the analysis tab of the map. Fixed on mobile and desktop.
> Fixed width of analysis 'start drawing' button in map

- app/javascript/components/maps/components/menu/components/sections/explore/explore-sections.js
Changed the frequency of the updates in the PTW description on the map, as requested.
> Changed frequency in the PTW description

- app/javascript/pages/sgf/section-projects/section-projects-component.jsx
> typo fixes

- app/javascript/analytics/map.js
- app/javascript/analytics/shared.js
- app/javascript/components/cookies/component.jsx
- app/javascript/components/map/components/mini-legend/mini-legend-component.jsx
- app/javascript/components/maps/components/analysis/component.jsx
- app/javascript/components/maps/map/components/draw/index.js
- app/javascript/components/maps/map/index.js
- app/javascript/components/ui/button/button-component.jsx
- app/javascript/components/widgets/components/widget/components/widget-footer/component.jsx
This PR fixes some analytics events that are not being triggered (WIP).
Currently it fixes the analytics events in the dashboards, but map and homepage events are pending.
> Fixing analytics events through the page

- app/javascript/components/widgets/widgets/land-cover/ranked-plantations/settings.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/settings.js
- app/javascript/components/widgets/widgets/land-cover/tree-cover/settings.js
Changed:
- ranked plantations
- tree cover ranked
- tree cover
> Changed extent year to 2000 for some ranked widgets

- app/javascript/app/store.js
> I did this and my browser and my computer are finally breathing.
— @sorodrigo
> God gave me choice between good memory and devtools with a lot of info on them, I don't remember what I chose.
— me
> Changed config to remove some big elements from redux devtools state

- app/javascript/pages/about/section-projects/section-projects-component.jsx
Updating usership number from 1.5 to 2.5
> Update for analytics' sake

- app/javascript/components/widgets/widgets/forest-change/fires-alerts/selectors.js
Uses the data to find the latest week and year value.
Please test with prod table and dataset. Should get to w/o 19th Aug.
**WORKS ASSUMING WE HAVE WEEKS WITH ZERO DATA**
> Update fires to use most recent data

- app/javascript/components/forms/contact/contact-component.jsx
- app/javascript/components/forms/form-fields.js
- app/javascript/components/forms/form-styles.scss
- app/javascript/components/modals/contact-us/component.jsx
Changed the contact us form with the changes WRI requested, plus some fixes and new functionality for the `select` Field in form-fields: it admits now a placeholder that adds an extra option, and adds a validator to use when the select needs a valid value.
It's WIP because it's probably missing work on the mail micro service.
> Updated contact us form

- app/javascript/components/modals/contact-us/component.jsx
> Updating contact-us form with Katie Lyons

- app/javascript/pages/stories/component.jsx
> Removing 2019 date from stories page

- app/javascript/pages/about/section-projects/section-projects-component.jsx
> adding question mark to "What is GFW"

- app/javascript/components/map-prompts/index.js
> clarifying drawing/upload prompt

- app/javascript/pages/about/section-projects/section-projects-component.jsx
> updating user count from 2019

- app/javascript/pages/about/section-projects/section-projects-component.jsx
> updating user count

- app/javascript/pages/sgf/section-apply/section-apply-component.jsx
> updating SGF page with 2020 information

- app/javascript/pages/sgf/section-apply/section-apply-component.jsx
> first link had incorrect info, updating

- app/javascript/components/forms/newsletter/component.jsx
> correcting typo

- app/javascript/pages/sgf/section-apply/section-apply-component.jsx
> updating description

- app/javascript/components/map/components/legend/components/layer-statement/component.jsx
- app/javascript/components/map/components/legend/components/layer-statement/config.js
- app/javascript/components/map/components/legend/components/layer-statement/index.js
- app/javascript/components/map/components/legend/components/layer-statement/styles.scss
- app/javascript/components/widgets/forest-change/tree-loss-tsc/selectors.js
- app/javascript/providers/datasets-provider/datasets-provider-actions.js
Modifies the widget hover text for the TCL by driver on the dashboards. The new text has been added to the selector.js 
> modifies the hover on the TCL by driver widget

- app/javascript/providers/datasets-provider/datasets-decode-config.js
updates ids for gain and loss carbon layers for the decoding using the new exported tiles.
> update ids of new carbon flux decoded layers

- app/javascript/pages/sgf/section-apply/section-apply-component.jsx
> Updating page after deadline's passed

- app/javascript/pages/topics/config/biodiversity.js
I'm unsure whether this was intended to read "great" or "greatest", but to me "greatest" reads better if still accurate.
> Great -> Greatest

- app/javascript/components/analysis/components/show-analysis/component.jsx
> updating language pre-aoi launch

- app/javascript/pages/topics/config/climate.js
> updating link because it doesn't work currently

- app/javascript/components/forms/profile/component.jsx
Small Profile Form modal changes:
* Change Profile Form subtitle text
* Make `Company` a required field
* Make `Where are you located?` a required field
* Sort alphabetically interests in the dropdown
* Sort alphabetically `How do you use` options in the dropdown
* Set `How do you use` select dropdown a required field
> Set required fields in Profile Form, change subtitle text

- app/javascript/components/forms/area-of-interest/component.jsx
- app/javascript/components/forms/components/field-wrapper/component.jsx
- app/javascript/components/forms/components/input/component.jsx
- app/javascript/components/forms/components/radio/component.jsx
- app/javascript/components/forms/components/radio/styles.scss
- app/javascript/components/forms/profile/component.jsx
- Makes language required always in the save area form.
- Hides the label from the form Input if there isn't any (and adds a prop class to the Input)
- Radio input now uses Input instead of Field
- Styled radio input to add indentation
> 'Other' Input component, conditional label, required fields, other

- app.json
- app/javascript/components/modals/share/share-actions.js
- app/javascript/services/bitly.js
> update bitly links

- app/javascript/components/widgets/land-cover/tree-cover-located/selectors.js
- app/javascript/components/widgets/land-cover/tree-cover-ranked/selectors.js
- app/javascript/data/land-categories.json
- Changes landmark category name
- Adds new metadata key
- Fixes settings issue with forestType/landCategory for 'tree cover ranked' widgets
> Update landmark config. Fix forestType landCat settings

- app/javascript/components/widgets/climate/emissions-deforestation/index.js
Biomass-loss endpoint bumped from v1 --> v2 for [this](https://bit.ly/2WwwRBB) widget.
> Fix version

- app/javascript/providers/datasets-provider/datasets-provider-actions.js
> Filters unpublished layers/datasets

- app/javascript/pages/about/section-projects/section-projects-component.jsx
> updating usership count

- app/javascript/components/forms/components/select/component.jsx
- app/javascript/components/forms/components/select/styles.scss
- app/javascript/components/forms/profile/actions.js
- app/javascript/components/forms/profile/component.jsx
- app/javascript/components/forms/profile/config.js
- app/javascript/components/forms/profile/index.js
[Reference here](https://basecamp.com/3063126/projects/10727890/todos/415117549). This PR adds a write-in box for the multi-select option when 'Other' is selected.
> Added a select input for multiple select form component

- app/javascript/data/land-categories.js
Swaps land rights for land mark
> Add landmark key to land-categories

- app/javascript/components/charts/lollipop-chart/lollipop-chart-component.jsx
- app/javascript/components/charts/lollipop-chart/lollipop-chart-styles.scss
- app/javascript/components/charts/lollipop-chart/lollipop-chart.js
- app/javascript/components/widget/components/widget-body/component.jsx
- app/javascript/components/widget/components/widget-lollipop/component.jsx
- app/javascript/components/widget/components/widget-lollipop/index.js
- app/javascript/components/widgets/fires/fires-ranked/index.js
- app/javascript/components/widgets/fires/fires-ranked/selectors.js
- app/javascript/services/analysis-cached.js
HTML version of [this PR](https://github.com/Vizzuality/gfw/pull/3990).
> Lollipop widget (HTML)

- app/javascript/components/forms/login/component.jsx
> wording change

- app/javascript/components/ui/refresh-button/refresh-button-component.jsx
Adding "You can try again, or save the shape and check back tomorrow." so that users have other options when/if analyses fail.
> Adding in-between solution for analysis failure

- app/javascript/components/map-menu/components/sections/my-gfw/component.jsx
- app/javascript/components/map-menu/components/sections/my-gfw/selectors.js
- app/javascript/pages/my-gfw/components/areas-table/component.jsx
- app/javascript/providers/areas-provider/selectors.js
Fixes [this issue](https://basecamp.com/3063126/projects/10728552/todos/418214819). Areas of interest are now sorted alphabetically in myGFW page and myGFW section in the map.
> Alphabetically sorted aois.

- app/javascript/components/widgets/fires/fires-alerts/selectors.js
Fixes a small issue where if the fire season straddled a year, the start date would be incorrect.
> Improve sort of fire season dates

- app/javascript/data/land-categories.js
> Point to correct column

- app/javascript/data/datasets.json
> remove metakey

- app/javascript/components/widgets/forest-change/tree-loss-pct/index.js
Adds primary forest layer to map for Primary Loss widget.
> Adds primary forest to dashboard on add to map

- app/javascript/components/widgets/fires/fires-alerts-cumulative/index.js
- app/javascript/components/widgets/fires/fires-alerts-historical-old/index.js
- app/javascript/components/widgets/fires/fires-alerts-historical/index.js
- app/javascript/components/widgets/fires/fires-ranked/index.js
- app/javascript/components/widgets/fires/fires-within/index.js
1. cumulative
1. weekly
1. ranking widget
1. donut chart
1. daily fire count
> Reorder fire tab

- app/javascript/components/widgets/fires/fires-ranked/index.js
- app/javascript/components/widgets/fires/fires-within/index.js
> Adds info buttons

- app/javascript/services/analysis-cached.js
Gets dates inside selected week range for each year.
> Grabs correct week range

- app/javascript/components/widgets/fires/fires-alerts-cumulative/selectors.js
Removes use of `periodVariance` (not appropriate for accumulated counts this widget) and instead tests status against the standard deviations shown in the graph.
> Update status calculation to match visualisation

- components/widgets/climate/whrc-biomass/index.js
- utils/calculations.js
Re-adjusts the climate functions to make them linear (again).
> Reimplement carbon equations

- components/ui/map/component.jsx
This pr fixes the issue when you are entering from the areas table and basemap wont render for you. 
[Notion](https://www.notion.so/My-GFW-Basemap-not-loading-from-areas-table-98ac2b2046fa474b83b97df1aa2d5ecb)
> Bugfix/basemap not loading from areas table 

- static/land-categories.js
- Add **sites** to Alliance for Zero Extinction dynamic sentence
Go to Brazil or Indonesia dashboards
Open settings on tree loss (or any) widget
Open Land Categories dropdown
Select Alliance for Zero Extinction...
Alliance for Zero Extinction **sites**... should appear in the widget sentence, capitalised.
> add sites to Alliance for Zero Extinction dynamic sentence

- providers/datasets-provider/config.js
Adds RADD alert decode function.
Work in progress - waiting confirmation of band encoding! Current encoding is likely incorrect but is useful to demonstrate animation and the nature of the data.
That said, feel free to merge with develop.
> WIP decode function for RADD

- components/widgets/forest-change/tree-loss-pct/selectors.js
Totals in the selectors now filter out the 2001 loss year.
> Filter 2001 fromo totals

- layouts/map/component.jsx
This pr disables the welcome modal as requested for today
> disable welcome modal

- .eslintignore
- .eslintrc.json
- package.json
- pages/api/__coverage__.js
- yarn.lock
> add eslint security configuration

- layouts/grants-and-fellowships/component.jsx
> Fixing a typo

- components/widgets/forest-change/tree-loss-pct/selectors.js
Fixes maths for the header sentence in the primary loss widget.
> Calculate ext difference

- components/widgets/manifest.js
Removes Future Carbon Gains widget from manifest: https://gfw.global/2J4RpfF
> Remove widget from manifest

- providers/datasets-provider/config.js
Quick update for RADD alerts to include correct intensity scale.
> Update decode for easier reading

- data/land-categories.js
Adds peat lands back to dashboard land categories.
> Remove hidden peat lands

- providers/datasets-provider/config.js
Adds 'high confidence' toggle to radd alerts (and correctly filters)
See: https://gfw.global/2INmtAX
> add confidence levels

- pages/_document.js
This pr adds GA4 gtag logic for analytics tracking.
> add google analytics 4 tags

- components/forms/area-of-interest/actions.js
> add geostoreDataAPI when saving AOI

- components/map/components/legend/components/layer-statement/config.js
- components/statement/config.js
> add missing space for country specific data disclamer

- providers/datasets-provider/config.js
Updates tree cover height palette to match UMD demo. Also makes shader code a little more human friendly.
> Update palette, make code more readable

- README.md
this pr only acts as a test to deploy pre-prod and staging enviroments.
> fix README spelling

- layouts/404/component.jsx
> test preprod

- layouts/grants-and-fellowships/apply/component.jsx
This pr includes as title specifies
> update of SGF page for 2021

- providers/latest-provider/actions.js
Removes `moment().subtract(7, 'days')` and replaces with `moment().add(-7, 'days')`.
Some issue with `.subtract`
> Fix moment subtract

- .eslintrc.json
- components/basemaps/index.js
- utils/cookies.js
- utils/hotjar.js
- wrappers/cookies/component.jsx
This pr adds a hotjar js tracking event that will trigger a survey after 70 seconds after enabling the planet basemap. The delay is handled through hotjar interface so all we need to do is to trigger the event whenever we have the basemap we want.
> hotjar planet basemap toggle event

- components/map-menu/sections.js
> Update carbon Flux to Carbon Emissions

- components/widgets/manifest.js
ESA land cover widget deleted from dashboards as per gfw request.
> removing esa land cover widget

- layouts/grants-and-fellowships/apply/component.jsx
> Updating with link to webinar

- components/map/components/legend/components/timeline/index.js
- utils/date-range.js
Notion: https://www.notion.so/BUG-high-priority-VIIRS-layer-defaults-to-3-month-period-even-past-date-of-coverage-3940eedd731e4b62b0e27d87e28e95f4
> fix mod range not possible to put less than 3 months

- .slugignore
> add slugignore for our heruku images

- layouts/grants-and-fellowships/apply/component.jsx
> updating from application window closing

- providers/datasets-provider/actions.js
- services/datasets.js
Allows data to publish on staging+preprod at any time without deployment needed.
> add support for mixed env

- data/rewrites-staging.json
- next.config.js
> add env rewrites

- data/analysis-datasets.json
- services/analysis-cached.js
Hotfix to correct wdpa id casting in sql parsing factory. Ugly but does the job (and we will refactor later, anyway)
> Update table, remove wdpa id casting

- components/widgets/climate/emissions-deforestation/index.js
Adds metadata keys to carbon emissions widgets
> Add metadata keys

- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation/index.js
- components/widgets/utils/config.js
Hotfix for climate widgets:
- adds metadata
- updates statement for 'flux' widgets (bottom text)
> Update meta, widget statement text

- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation/index.js
- components/widgets/utils/config.js
Adds value to metadata.csv download, updates statement for carbon widgets
> Update download and statement for carbon widgets

- services/datasets.js
> fix typo in dataset query

- components/charts/composed-chart/component.jsx
- components/widget/components/widgets-custom/component.jsx
- components/widgets/climate/carbon-flux/selectors.js
We needed the widget to be a bit more clever when it comes to simple mode, I updated the logic to support It for this widget.
+ as i had to remove the labels, just did not work in this tiny space, i added a simple legend that can be added for these analysis widgets on the map.
> fix carbon widget on map analysis summary

- components/forms/components/select/component.jsx
The intent of this PR is to give users instructions on how to select multiple options in the MyGFW profile modal
> Adding instructions

- providers/geodescriber-provider/actions.js
Updates header to sum all extent values
> Fix header

- components/widgets/fires/fires-ranked/selectors.js
Fixes ranking widget: http://localhost:3000/embed/widget/firesRanked
Now works at country and global levels, enrishing child location with alerts data
> Fix metadata labels

- layouts/dashboards/components/global-sentence/component.jsx
- pages/dashboards/[[...location]].js
+ Adds basepath + category to canonical link
+ Renders correct global sentence on the server based on query category param.
> fix global dashboard sentence ssr

- layouts/embed/widget/component.jsx
- providers/geodescriber-provider/index.js
As previous fix broke dashboard summary sentence, i now send embed as a prop so we get access to the location within our embeds, without breaking dashboards.
> fix widget title embed

- components/charts/lollipop-chart/component.jsx
This fixes an issue where we don't have a selected unit, and the app crashes, reproducible using this URL 
https://preproduction.globalforestwatch.org/dashboards/country/BRA/?burnedAreaRanked=eyJ1bml0IjoiYnVybl9wcm9wb3J0aW9uIiwid2Vla3MiOjUyLCJkYXRhc2V0IjoibW9kaXMifQ%3D%3D&category=fires&dashboardPrompts=eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJzaGFyZVdpZGdldCIsImRvd25sb2FkRGFzaGJvYXJkU3RhdHMiLCJ3aWRnZXRTZXR0aW5ncyJdLCJzZXR0aW5ncyI6eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJzaGFyZVdpZGdldCIsImRvd25sb2FkRGFzaGJvYXJkU3RhdHMiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOlsic2hhcmVXaWRnZXQiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOltdLCJzZXR0aW5ncyI6eyJvcGVuIjpmYWxzZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6IiJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXg …
> hotfix - selected unit is undefined

- components/map/components/popup/components/data-table/component.jsx
- components/map/components/popup/components/data-table/styles.scss
You can now include `type: link` and `linkText: 'your txt'` to the Interaction Config on layers, which will render as a clickable link.
To test, use `ENV=staging` and go to `http://localhost:3000/map/?map=eyJjZW50ZXIiOnsibGF0IjoxMS40ODI2MjczNDM3MDQ3ODgsImxuZyI6MjIuOTM2NTg1ODM5OTEyNzk0fSwiem9vbSI6NS42ODU1Nzk2NTgwMDU2MiwiZGF0YXNldHMiOlt7ImRhdGFzZXQiOiJrZXktYmlvZGl2ZXJzaXR5LWFyZWFzLXRlc3QiLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJsYXllcnMiOlsia2V5LWJpb2RpdmVyc2l0eS1hcmVhcy0yMDIxIl19LHsiZGF0YXNldCI6InBvbGl0aWNhbC1ib3VuZGFyaWVzIiwibGF5ZXJzIjpbImRpc3B1dGVkLXBvbGl0aWNhbC1ib3VuZGFyaWVzIiwicG9saXRpY2FsLWJvdW5kYXJpZXMiXSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZX1dfQ%3D%3D&mapMenu=eyJtZW51U2VjdGlvbiI6ImRhdGFzZXRzIiwiZGF0YXNldENhdGVnb3J5IjoidGVzdCJ9`
> Add clickable links to interactionConfig

- components/widgets/fires/fire-alerts-simple/index.js
> Remove download nested object from staticStatement

- layouts/dashboards/components/header/component.jsx
- pages/dashboards/[[...location]].js
Testing: 
Ensure dashboards do not crash on load + switching between admins
> dashboard ssr feedback

- package.json
- pages/api/set-cookie.js
- pages/dashboards/[[...location]].js
- pages/embed/map/[[...location]].js
- pages/map/[[...location]].js
- providers/mygfw-provider/index.js
- services/areas.js
- services/location.js
- services/user.js
- yarn.lock
1. make one of your areas private
2. You should be available to see them if logged in.
_A logout + login is required to make this work._
> Fix issue where users cant see their private areas map+dashboard

- components/widgets/index.js
- providers/datasets-provider/actions.js
- providers/datasets-provider/reducers.js
- services/datasets.js
BS: https://basecamp.com/3063126/projects/10728552/todos/452110233
Fixes issue causing category to change on dashboard when an inactive widget changes threshold.
> fix bug causing tab to change on dashboard when changing threshold

- components/widget/components/widget-caution/component.js
- components/widget/components/widget-caution/styles.scss
- components/widgets/forest-change/glad-alerts-simple/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
> add gladL data alert message

- components/widgets/forest-change/integrated-deforestation-alerts/index.js
The PR contains a change in the logic for handling individual alerts downloads. Please take a look and merge if you are happy with it.  
> handle individual alerts download

- components/forms/contact/component.jsx
> Staff change / email change

- components/widgets/forest-change/glad-alerts-simple/index.js
> updating GLAD-L warning label text

- package.json
- yarn.lock
> Update gfw-components to 1.7.8

- cypress/integration/widget.js
- services/sentences.js
> FLAG-141 Fix typo in analysis

- services/analysis-cached.js
> removes casting from queries

- components/widgets/manifest.js
> [FLAG-225] Remove GLAD Ranked widget

- layouts/grants-and-fellowships/apply/component.jsx
- providers/datasets-provider/config.js
- services/analysis-cached.js
> production release

- components/map/components/legend/component.jsx
> Fix empty integrated alerts caution

- components/map/components/legend/component.jsx
- layouts/grants-and-fellowships/apply/component.jsx
- services/analysis-cached.js
> Merge Burned areas query fix [FLAG-307]

- layouts/grants-and-fellowships/apply/component.jsx
> update to webinar recording

- providers/datasets-provider/config.js
Changing intensity values of GLAD-L and Integrated alerts for testing.
Test intensity value in this PR = 150
> alerts intensity value set to 150

- providers/datasets-provider/config.js
RADD and GLAD-S2 alerts intensity value set to 150 for GFW team to review options
> RADD and GLAD-S2 intensity 150

- layouts/grants-and-fellowships/apply/component.jsx
> Updating the SGF cycle information

- providers/datasets-provider/config.js
Changes on the decode function used on Tree Cover Loss from Fires to update to new desired color (#9A5B50) for new release.
> Decode color change TCLF

- components/scroll-to/index.js
- components/tags-list/component.jsx
- components/widgets/component.jsx
- components/widgets/forest-change/fao-deforest/index.js
- components/widgets/forest-change/fao-reforest/index.js
- components/widgets/forest-change/glad-alerts-simple/index.js
- components/widgets/forest-change/glad-alerts/index.js
- components/widgets/forest-change/glad-ranked/index.js
- components/widgets/forest-change/glads/index.js
- components/widgets/forest-change/integrated-alerts-ranked/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
- components/widgets/forest-change/net-change/index.js
- components/widgets/forest-change/tree-cover-gain-outside-plantations/index.js
- components/widgets/forest-change/tree-cover-gain-simple/index.js
- components/widgets/forest-change/tree-cover-gain/index.js
- components/widgets/forest-change/tree-gain-located/index.js
- components/widgets/forest-change/tree-loss-located/index.js
- components/widgets/forest-change/tree-loss-plantations/index.js
- components/widgets/forest-change/tree-loss-primary/index.js
- components/widgets/forest-change/tree-loss-ranked/index.js
- components/widgets/forest-change/tree-loss/index.js
- components/widgets/selectors.js
- components/widgets/styles.scss
- data/categories.json
- layouts/dashboards/component.jsx
- layouts/dashboards/components/subcategories/component.jsx
- layouts/dashboards/components/subcategories/index.js
- layouts/dashboards/components/subcategories/styles.scss
- layouts/dashboards/selectors.js
- layouts/dashboards/styles.scss
This PR adds subcategory navigation to the _Forest Change_ tab in the _Dashboard_. 
[FLAG-445](https://gfw.atlassian.net/browse/FLAG-445)
> Add Subcat navigation to Forest change tab in Dashboard

- components/charts/components/pie-chart-legend/component.jsx
- components/widgets/forest-change/_tree-loss-drivers/README.MD
- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
- components/widgets/forest-change/tree-loss-drivers/index.js
- components/widgets/forest-change/tree-loss-drivers/selectors.js
- data/colors.json
- data/tsc-loss-categories.json
- services/analysis-cached.js
This PR reverts the new PieChart version in #4462 (while keeping the code for a future rollout), and updates the original widget's alert in Indonesia only. 
[FLAG-569](https://gfw.atlassian.net/browse/FLAG-569)
Only the last commit belongs to this particular task.
The remaining ones are from #4462 as this PR builds on top of it.
> Adjust Indonesia Drivers widget caveat (+ PieChart revert)

- providers/datasets-provider/config.js
Changes in the `staticRemap` for the gain layer (`staticRemapGain`) to resolve the blurry pixel edges at zoom **level > 12**
New decode function `staticRemapGain` now has an if statement where it only applies **alpha=1** at **zoom>12**
> attempt to modyfy staticRemap decoding function

- components/widgets/forest-change/tree-loss/selectors.js
The extent area comes in a different format when querying pre-calculated area (as an array) or an OTF query (as a single value). This will will parse it one way or another depending on the type.
> OTF analysis shows 0% decrease

- components/forms/profile/actions.js
- components/forms/profile/component.jsx
Add a new field on the user profile to be able to sign up for testing new features on the platform.
> Add Sign Up for Testing field to user profile

- components/forms/profile/actions.js
- components/forms/profile/component.jsx
> FLAG-217 - Merge aioCity and aioState fields in user profile form

- components/aoi-card/component.jsx
- components/widget/components/widget-header/components/widget-download-button/component.jsx
- components/widgets/fires/fire-alerts-simple/index.js
- services/analysis-cached.js
`startDate` and `endDate` are now correctly passed on to the VIIRS function
> [FLAG-290] Add missing starDate and endDate on VIIRS function

- components/forms/profile/component.jsx
> fix email error - high priority

- components/map/components/attributions/attributions-content/component.jsx
- components/map/components/attributions/attributions-content/index.js
- components/map/components/attributions/attributions-modal/component.jsx
- components/map/components/attributions/component.jsx
- Extracted the attribution content from map/modal into a separate file  
_In order to reuse logic and information_  
- Removed hardcoded INEGI from the attribution
_which is a map provider for some but not all regions and is currently hard-coded into the attribution text_    
- Copyright uses the current year  
_instead of being hardcoded, currently to 2016!_
**Notes:**  
Despite extracting the attribution code into a separate component, the display logic/styling (narrow screen, modal alignment, etc was kept) the same. 
[FLAG-246 | Google Satellite Imagery basemap needs an update ](https://gfw.atlassian.net/browse/FLAG-246)
> Map attribution updates

- services/shape.js
Remove proxying of AoI zip files uploads. 
[FLAG-660](https://gfw.atlassian.net/browse/FLAG-660) | "Invalid .zip file format" and "Invalid .kmz file format" error when trying to upload areas of interest
> Do not proxy uploads or a 404 will be returned

- pages/api/gfw/[...params].js
- utils/request.js
> Fix layers on staging

- README.md
This PR updates the `README.md` to reference Heroku, especially our two staging environments (`staging` and `preproduction`) as well as review apps. 
[FLAG-631](https://gfw.atlassian.net/browse/FLAG-631)
> Update README to reference Heroku, the environments and review apps. 

- components/widgets/climate/carbon-flux/index.js
- components/widgets/climate/carbon-flux/selectors.js
This PR changes the sentence/wording of the `carbonFlux` depending on whether the total carbon flux is positive or negative. 
- Positive value [link](https://gfw-staging-pr-4511.herokuapp.com/dashboards/country/PRT/?category=climate&dashboardPrompts=eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJ3aWRnZXRTZXR0aW5ncyJdLCJzZXR0aW5ncyI6eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6W10sInNldHRpbmdzIjp7Im9wZW4iOmZhbHNlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5IjoiIn0sIm9wZW4iOnRydWUsInN0ZXBJbmRleCI6MCwic3RlcHNLZXkiOiJ3aWRnZXRTZXR0aW5ncyJ9LCJvcGVuIjp0cnVlLCJzdGVwc0tleSI6ImRvd25sb2FkRGFzaGJvYXJkU3RhdHMifQ%3D%3D&location=WyJjb3VudHJ5IiwiUFJUIl0%3D&map=eyJjZW50ZXIiOnsibGF0IjozNy40NzE1MjU1MTMyMDU5NCwibG5nIjotMTguNzA5Njg5MTQwMDEwMjN9LCJ6b29tIjozLjg1Njg1NDY3NDg1NzY2NCwiY2FuQm91bmQiOmZhbHNlLCJkYXRhc2V0cyI6W …
> Change carbonFlux widget sentence depending on total carbon flux

- docs/GFW_layer_update_example.ipynb
- docs/GFW_layer_update_template.ipynb
This PR includes notebooks illustrating some of the most common tasks involved in updating and editing GFW map layers. The code is based on the use of Python and the [LMIpy](https://lmipy.readthedocs.io/en/latest/) library, but the concepts explained can be dealt with with other API requests' tools.  
The PR includes 2 notebooks:
- **GFW Layer update example**: serves as a full example of various procedures. 
- **GFW Layer update example**: is an empty template, with the same code as the example, ready to be edited reused for any layer purposes.
> Layer updates code examples

- components/map/components/layer-manager/component.jsx
- yarn.lock
This is a test branch to debug a possible dataset misconfiguration that causes layers to disappear in a very particular scenario. Notes on how to reproduce the original bug below. 
- When Planet imagery is displayed with any other dataset, we’re finding that toggling PTW will cause that dataset to disappear. It will appear if that dataset is toggled on after PTW is toggled on or if the datasets are rearranged in the legend.
- When Planet is displayed, the PTW icons disappear when zooming in past zoom level 8. 
- Occurs across the following browsers: Edge, Edge in Private, Chrome, and Chrome incognito.
The layer configuration changes that seem to fix the bug can be found here: https://github.com/Vizzuality/gfw/pull/4533/commits/10065b93de5470ff0c3929f9a471f9e945f5db88 .
At the moment, this …
> [FLAG-685] Planet obscures data layers

- components/widgets/fires/fire-alerts-simple/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
- components/widgets/forest-change/tree-loss-drivers/selectors.js
- components/widgets/forest-change/tree-loss-primary/index.js
- services/analysis-cached.js
Deploying hotfixes:
#4536 
#4539 
#4535 
#4538
> Deploy to PROD

- components/satellite-basemaps/planet-selectors.js
Renaming planet mosaic names in dropdown as requested.
_Before_
_After_
> FLAG-762: Update planet mosaic names

- components/satellite-basemaps/planet-selectors.js
- components/widgets/utils/config.js
https://github.com/Vizzuality/gfw/pull/4550
> PROD deploy 2023-05-05 11:32am EST

- components/widgets/fires/burned-area-cumulative/index.js
- components/widgets/fires/burned-area-ranked/index.js
Updating alert for burned areas:
> FLAG-777: update alert label

- components/ui/datepicker/component.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/selectors.js
> FLAG-593: update limit startDate

- components/ui/datepicker/component.js
- components/widgets/fires/burned-area-cumulative/index.js
- components/widgets/fires/burned-area-ranked/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/selectors.js
https://github.com/Vizzuality/gfw/pull/4553
https://github.com/Vizzuality/gfw/pull/4555
> PROD Deploy 2023-05-12 10:04am EST

- components/widgets/forest-change/tree-cover-gain/index.js
Until we have an update from Data API with a bigger range we should use this solution to be more accurate in our info
- Check the widget https://gfw.global/3J39LtR
> [FLAG-804] Update the Tree Cover Gain widget to show data for 2000 to 2012

- components/aoi-card/component.jsx
> FLAG-417: fix monthly typo

- layouts/home/config.js
Updating Card info in home page
> FLAG-312: update carousel card info

- components/charts/components/chart-tooltip/component.jsx
adding a fix to handle `undefined` in the data array for the tooltip chart
> FLAG-786: fix labelFormat

- pages/api/metadata/[...params].js
> fix(metadata-params): replace proxy middleware with network request

- components/widgets/forest-change/net-change/index.js
- data/categories.json
- changing the sort order of net change widget
- changing order of sections in forest change tab
- adding a new alert to the net change widget
new sort order in summary:
new sort order in forest change tab:
> FLAG-811: change sort order

- components/map-menu/components/menu-tile/component.jsx
- components/map/components/legend/components/layer-select-menu/component.jsx
- components/map/components/legend/components/layer-toggle/component.jsx
- components/map/components/popup/components/boundary-sentence/component.jsx
- components/satellite-basemaps/component.jsx
- components/ui/button/component.jsx
- components/ui/toggle/component.jsx
- components/widget/components/widget-header/component.jsx
- components/widget/components/widget-header/components/widget-download-button/component.jsx
- components/widget/components/widget-header/components/widget-info-button/component.jsx
- components/widget/components/widget-header/components/widget-map-button/component.jsx
- components/widget/components/widget-header/components/widget-settings-button/component.jsx
- components/widget/components/widget-header/components/widget-share-button/component.jsx
- layouts/dashboards/components/header/component.jsx
- pages/_document.js
> FLAG-819: add layer name to id to track events

- components/satellite-basemaps/component.jsx
- components/ui/checkbox/component.jsx
adding id to Checkbox component
> FLAG-819: add id prop

- components/analysis/components/chose-analysis/component.jsx
- components/map/components/legend/components/layer-toggle/component.jsx
- components/ui/dropdown/component.jsx
- components/ui/dropdown/components/item/component.jsx
- layouts/map/components/map-controls/component.jsx
> FLAG-838: add ids for medium priority GA4 events

- components/analysis/components/chose-analysis/component.jsx
- components/map/components/legend/components/layer-toggle/component.jsx
- components/ui/dropdown/component.jsx
- components/ui/dropdown/components/item/component.jsx
- layouts/map/components/map-controls/component.jsx
- services/analysis-cached.js
https://github.com/wri/gfw/pull/4609
> PROD Deploy 2023-06-28 06:19pm EST

- layouts/dashboards/components/header/component.jsx
> FLAG-839: change indonesia's text

- components/widget/components/widget-header/components/widget-download-button/component.jsx
- components/widget/components/widget-header/components/widget-info-button/component.jsx
- components/widget/components/widget-header/components/widget-map-button/component.jsx
- components/widget/components/widget-header/components/widget-settings-button/component.jsx
- components/widget/components/widget-header/components/widget-share-button/component.jsx
> FLAG-819: add custom class for tracking

- components/widget/components/widget-header/components/widget-download-button/component.jsx
- components/widget/components/widget-header/components/widget-info-button/component.jsx
- components/widget/components/widget-header/components/widget-map-button/component.jsx
- components/widget/components/widget-header/components/widget-settings-button/component.jsx
- components/widget/components/widget-header/components/widget-share-button/component.jsx
- layouts/dashboards/components/header/component.jsx
https://github.com/wri/gfw/pull/4613
> PROD Deploy 2023-06-30 12:53pm EST

- layouts/dashboards/components/header/component.jsx
> FLAG-843: add text for IDN

- layouts/dashboards/components/header/component.jsx
https://github.com/wri/gfw/pull/4617
> PROD Deploy 2023-07-04 11:06am EST

- components/map-geostore/component.jsx
Workaround to prevent the page from breaking on some broken AOIs
> FLAG-835: workaround to avoid page break

- layouts/about/partners/partners.js
Remove NEA logo from funders section of About page
> [FLAG-846] Remove NEA logo

- components/widgets/forest-change/tree-loss-primary/index.js
Display static image only in summary for IDN
> FLAG-852: display static image only in summary for IDN

- components/spinner/readme.md
> fix jekyll build

- components/header/config.js
- data/rewrites.json
> FLAG-858: fix too many redirects issue in blog

- components/map/components/legend/components/layer-statement/config.js
> FLAG-810: update tooltip text

- components/header/config.js
- package.json
- yarn.lock
Updating config for revamped header
https://github.com/wri/gfw/assets/127868788/3f493433-0d01-46e5-8812-abdce0788e22
> FLAG-823: update nav items

- components/legend/components/legend-list-item/index.js
- components/map/components/legend/components/layer-toggle/component.jsx
- components/widget/component.jsx
> FLAG-842: add data-component-type attr

- components/legend/components/legend-list-item/index.js
- components/map/components/legend/component.jsx
- components/map/components/legend/components/layer-toggle/component.jsx
- components/widget/component.jsx
https://github.com/wri/gfw/pull/4655
> PROD Deploy 2023-08-03 01:28pm EST

- components/widgets/forest-change/tree-cover-gain/index.js
- services/analysis-cached.js
Updating year range for tree cover gain
Updating WHERE clause
> FLAG-826: fix sql query and update years

- pages/_document.js
Removing the GTM script for staging
> FLAG-808: track GA only in production

- pages/_document.js
- pages/dashboards/[[...location]].js
https://github.com/wri/gfw/pull/4578
> PROD Deploy 2023-08-21 11:36am EST

- components/widgets/forest-change/tree-loss-primary/index.js
> fix IDN dashboard widget for summary

- components/widgets/forest-change/tree-loss-primary/index.js
- pages/_document.js
https://github.com/wri/gfw/pull/4668
> PROD Deploy 2023-08-21 02:13pm

- components/widgets/forest-change/tree-loss-primary/index.js
> fix(dashboard): IDN widget, validation incorrect

- components/widgets/forest-change/tree-loss-primary/index.js
https://github.com/wri/gfw/pull/4670
> PROD Deploy 2023-08-21 01:56pm

- .eslintrc.json
- .github/workflows/ci.yml
- __mocks__/fileMock.js
- __mocks__/styleMock.js
- jest.config.js
- jest.setup.js
- next.config.js
- package.json
- utils/__tests__/format.spec.js
- utils/format.spec.js
- yarn.lock
We would like to create a testing environment where we can try out unit tests before implementing them alongside various features/bugs.
Eventually, if we’re working on a new feature, we’ll want to add unit tests to our code. Some of our reasons for doing this: 
- New features without tests coverage are prone to errors 
- Code without tests are legacy by definition
> [FLAG-773] Create test environment and the first tests

- components/widgets/forest-change/integrated-alerts-ranked/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
> FLAG:886: add survey link

- components/widgets/fires/tree-loss-fires-annual/index.js
- services/analysis-cached.js
> Revert "FLAG-900: Undefined year causing an error in the TCL due to Fires widget in protected and some custom area dashboards"

- components/map-menu/components/sections/explore/sections.js
The [email sign-up link for Places to Watch](https://www.globalforestwatch.org/map/?map=eyJkYXRhc2V0cyI6W3siZGF0YXNldCI6ImdsYWQtZGVmb3Jlc3RhdGlvbi1hbGVydHMiLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJsYXllcnMiOlsiZGVmb3Jlc3RhdGlvbi1hbGVydHMtZ2xhZCIsInBsYWNlcy10by13YXRjaCJdfSx7ImRhdGFzZXQiOiJwb2xpdGljYWwtYm91bmRhcmllcyIsImxheWVycyI6WyJkaXNwdXRlZC1wb2xpdGljYWwtYm91bmRhcmllcyIsInBvbGl0aWNhbC1ib3VuZGFyaWVzIl0sIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9XX0%3D&mapMenu=eyJtZW51U2VjdGlvbiI6ImV4cGxvcmUiLCJleHBsb3JlVHlwZSI6InBsYWNlc1RvV2F0Y2giLCJwdHdUeXBlIjoibW9uZ2FiYXkifQ%3D%3D&mapPrompts=eyJvcGVuIjp0cnVlLCJzdGVwc0tleSI6InJlY2VudEltYWdlcnkiLCJzdGVwc0luZGV4IjowfQ%3D%3D&utm_campaign=socialmedia&utm_medium=globalforests&utm_source=instagram&utm_term=753e28ce-11d8-4933-9ddb-ef9383b59109) (1st screenshot) …
> chore(ssl): add ssl to places to watch link

- .env.sample
- .gitignore
- components/header/component.jsx
- components/map-menu/components/sections/explore/sections.js
- fixtures/notifications/index.js
- pages/dashboards/[[...location]].js
- pages/grants-and-fellowships/[section].js
- pages/index.js
- pages/map/[[...location]].js
- pages/my-gfw.js
- services/__tests__/notifications.spec.js
- services/notifications.js
- wrappers/fullscreen/component.jsx
- wrappers/page/component.jsx
https://github.com/wri/gfw/pull/4686
> PROD Deploy 2023-09-08 11:54am EST

- components/legend/components/legend-item-types/legend-item-type-basic/legend-item-type-basic-item/index.js
- components/map/components/layer-manager/component.jsx
#4695: Issues turning the satellite imagery toggle on and off
> PROD Deploy 2023-09-20 07:11am EST

- pages/about.js
- pages/search.js
> feat(notice-board): integrate notice board in about and search pages

- package.json
- yarn.lock
> bump gfw-components to 3.5.0

- package.json
- yarn.lock
https://github.com/wri/gfw/pull/4728
> PROD Deploy 2023-11-14 1:53pm EST

- components/widgets/land-cover/fao-cover/index.js
- components/widgets/land-cover/fao-cover/selectors.js
> fix(fao-cover): validate null and 0

- components/widgets/climate/emissions-deforestation-drivers/selectors.js
- components/widgets/climate/emissions-deforestation/selectors.js
- components/widgets/fires/tree-loss-fires-annual/selectors.js
- components/widgets/forest-change/tree-loss-drivers/selectors.js
- components/widgets/forest-change/tree-loss-primary/selectors.js
- components/widgets/forest-change/tree-loss/selectors.js
> FLAG-986 | Adjust warning sentence to DRC TCL / emissions widgets

- package.json
- utils/request.js
- yarn.lock
> chore(axios): bump axios to 1.6.7

- components/header/config.js
- package.json
- yarn.lock
Remove Community Forum links from header and footer and bumping GFW Components version
> FLAG-1028: remove Community Forum link and bump gfw components version

- data/dashboard-summary-sentence.js
This PR adds a download link to the summary and forest change pages with data from the TCL 2023 update.
> FLAG-1047: add 2023 TCL download link in sentences

- components/widgets/fires/tree-loss-fires-annual/index.js
- components/widgets/fires/tree-loss-fires-annual/selectors.js
- components/widgets/fires/tree-loss-fires-proportion/index.js
- components/widgets/fires/tree-loss-fires-proportion/selectors.js
> FLAG-1075: tcl map widgets

- components/widgets/forest-change/tree-loss-drivers/index.js
- services/get-where-query.js
> FLAG-1077: use widgetId to add a specific clause in SQL query

- layouts/dashboards/components/header/component.jsx
> FLAG-1091: update IDN number in dashboard

- components/error-message/component.jsx
- components/error-message/styles.scss
- pages/dashboards/[[...location]].js
- services/areas.js
- utils/request.js
- wrappers/page/component.jsx
ONGOING
[FLAG-973](https://gfw.atlassian.net/browse/FLAG-973)
> [FLAG-973] Private saved areas are not accessible in a users own my gfw account

- components/analysis/components/chose-analysis/component.jsx
- components/analysis/components/download-data/component.jsx
- components/map/components/attributions/attributions-content/component.jsx
- package.json
- yarn.lock
Updating terms url across the web application.
> FLAG-1097: replace terms of service url

- components/widgets/forest-change/tree-loss-primary/index.js
- pages/_document.js
https://github.com/wri/gfw/pull/4800
> PROD Deploy 2024-05-21 2:37pm EST

- pages/_document.js
Updating osano script and consent
> Update osano script for the correct one and add consent script

- components/widgets/forest-change/tree-loss-primary/index.js
- pages/_document.js
https://github.com/wri/gfw/pull/4802
> PROD Deploy 2024-05-21 04:45pm EST

- layouts/topics/config/biodiversity.js
When you scroll down to the biodiversity interactive element on this page: [Effects of Forests on Biodiversity | Deforestation & Biodiversity Loss | GFW](https://www.globalforestwatch.org/topics/biodiversity/#slides/3). Make sure you are in Recovery state, as pictured in the screenshot below. Click on the “i” icon. The blog link leads you to [GLAD Alerts Help Protect Sumatra’s Leuser Rainforest Ecosystem | Users In Action | Global Forest Watch Blog](https://www.globalforestwatch.org/blog/people/glad-alerts-help-protect-sumatras-leuser-rainforest-ecosystem/) , which is incorrect. It should lead to https://www.globalforestwatch.org/blog/data-and-research/worlds-last-intact-forests-are-becoming-increasingly-fragmented/.
> [FLAG-973] Broken blog link in the biodiversity interactive element

- components/map/components/legend/components/timeline/index.js
- components/map/components/legend/components/timeline/selectors.js
- components/slider/index.js
- components/timestep/index.js
- providers/datasets-provider/actions.js
FE counterpart to enable #4754
[FLAG-1016](https://gfw.atlassian.net/browse/FLAG-1016)
> [FLAG-1016][FE] Data/tree gain 5y decoding FE changes

- pages/_document.js
> Temporary hide cookie preferences link

- components/widgets/fires/fires-alerts-cumulative/selectors.js
- components/widgets/fires/fires-alerts/selectors.js
> [FLAG-1149] Alert count for "all" confidence alerts in cumulative fire alerts widget does not match download

- components/ui/dynamic-sentence/component.jsx
> FLAG-1164: account for undefined object in props

- components/legend/components/legend-item-toolbar/legend-item-button-info/index.js
> FLAG-1143: add span element and data action attribute to info button

- components/legend/components/legend-item-toolbar/legend-item-button-info/index.js
- components/ui/dynamic-sentence/component.jsx
https://github.com/wri/gfw/pull/4841
> PROD Deploy 2024-'8-07 02:48pm EST

- components/analysis/components/chose-analysis/upload-shape-modal/component.jsx
fix typo from feautures to features
> [FLAG-1166]  fix typo from feautures to features

- components/widgets/forest-change/tree-loss/index.js
- services/analysis-cached.js
The query of the widgethttps://gfw.global/4e4K0Xq, has undefined for the year, likely from an undefined JavaScript variable:
> [FLAG-1193] Error in the query of TCL widget within some custom areas

- components/footer/component.jsx
- package.json
- pages/_document.js
- yarn.lock
> FLAG-1037: Add preferences link to Footer

- pages/_document.js
> FLAG-1037: fix the way osano cookie widget is hidden

- components/footer/component.jsx
- package.json
- pages/_document.js
- yarn.lock
https://github.com/wri/gfw/pull/4857
https://github.com/wri/gfw/pull/4862
> PROD Deploy 2024-10-02 05:25pm EST

- pages/_document.js
adding setTimeout when hiding osano cookie icon
> FLAG-1037: add setTimeout when hiding osano cookie icon

- pages/_document.js
https://github.com/wri/gfw/pull/4866
> PROD Deploy 2024-10-07 12:09pm EST

- components/widgets/forest-change/tree-loss-primary/selectors.js
Small text tweak to the treeLossPct chart legend dotted line item
[FLAG-1110](https://gfw.atlassian.net/browse/FLAG-1110)
[FLAG-1110]: https://gfw.atlassian.net/browse/FLAG-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FLAG-1110] Small text tweak to the treeLossPct chart legend dotted line item

- components/widgets/manifest.js
> [HOTFIX] hide soil organic widget until we have the correct metadata

- components/widgets/manifest.js
https://github.com/wri/gfw/pull/4885
> PROD Deploy 2024-11-13 05:58pm EST

- components/charts/horizontal-bar-chart/custom-tick-component.jsx
- components/widgets/land-cover/ranked-plantations/index.js
- components/widgets/land-cover/ranked-plantations/selectors.js
Update dataset version for Location of Plantations... widget and fix colors
> FLAG-1100: update data version and update CustomTick component to not render hyphen

- components/widgets/forest-change/tree-loss-plantations/index.js
- components/widgets/forest-change/tree-loss-plantations/selectors.js
> FLAG-1156: adjust widget to use natural forest query

- components/widgets/climate/emissions-deforestation-drivers/selectors.js
- components/widgets/forest-change/tree-loss-plantations/selectors.js
https://github.com/wri/gfw/pull/4896
> PROD Deploy 2024-12-10 11:56am EST

- components/map-menu/sections.js
- components/widgets/climate/emissions-deforestation-drivers/selectors.js
- components/widgets/forest-change/tree-loss-plantations/selectors.js
- components/widgets/manifest.js
- providers/datasets-provider/config.js
https://github.com/wri/gfw/pull/4894
> PROD Deploy 2024-12-12 11:15am EST

- components/widgets/land-cover/fao-cover/index.js
- providers/country-data-provider/actions.js
- services/country-links.json
- services/country.js
> [FLAG-1234] Fao countries

- layouts/dashboards/components/header/selectors.js
> FLAG-1118: update download link for global

- components/charts/components/pie-chart-legend/component.jsx
- components/charts/components/pie-chart-legend/styles.scss
- components/widget/components/widget-pie-chart-legend/component.jsx
- components/widget/components/widget-pie-chart-legend/styles.scss
- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
This reverts commit 6b6c12b6847a86da067a8babac635d362b4dc93f, reversing changes made to e56b581defdac73e2e325148f301051f3488a75b.
> Revert "Merge pull request #4910 from wri/feat/grouped-legend-FLAG-1226"

- components/charts/components/pie-chart-legend/component.jsx
- components/charts/components/pie-chart-legend/styles.scss
- components/widget/components/widget-pie-chart-legend/component.jsx
- components/widget/components/widget-pie-chart-legend/styles.scss
- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
- components/widgets/manifest.js
> [FLAG-1226] Grouped Legends

- services/analysis-cached.js
> FLAG-1266: account for null values in getOrganicSoilCarbonGrouped function

- components/widgets/land-cover/ranked-plantations/index.js
- services/analysis-cached.js
> fix(analysis-cached): remove hardcoded dataset version in requests

- components/widgets/land-cover/ranked-plantations/index.js
- services/analysis-cached.js
https://github.com/wri/gfw/pull/4935
> PROD Deploy 2025-02-20 11:58am EST

- components/map/basemaps.js
- components/satellite-basemaps/component.jsx
- components/satellite-basemaps/selectors.js
Making Google Satellite Imagery on top of the list and making it as default title in the map.
_BEFORE_
_AFTER_
> FLAG-1272: make google satellite basemap as default

- components/satellite-basemaps/component.jsx
Fix undefined basemap in component
> fix(satellite-basemaps): account for undefined basemap in component

- components/satellite-basemaps/component.jsx
> fix(aoi): add check for planetPeriods in setMapBasemap

- data/metadata.json
> chore(metadata): add umd_glad_landsat_alerts metadata to the safe path list

- components/aoi-card/component.jsx
- components/map-menu/components/sections/my-gfw/component.jsx
- components/modals/outdated-area/OutdatedAreaModal.js
- layouts/my-gfw/components/areas-table/component.jsx
> FLAG-1273: display outdated areas warning and modal for gadm 3.6 areas

- data/metadata.json
This PR updates the metadata.json file to remove old identifiers and add new ones.
> Metadata.json changes

- data/metadata-exception.json
> fix(metadata): add satellite-imagery metadata

- layouts/home/config.js
> FLAG-1323: update gfw pro image in carousel

- components/charts/composed-chart/styles.scss
- components/widgets/component.jsx
- layouts/home/config.js
https://github.com/wri/gfw/pull/4979
> PROD Deploy 2025-04-23 01:18pm EST

- utils/request.js
> fix(cache): remove interceptor to remove cache

- components/satellite-basemaps/component.jsx
- components/satellite-basemaps/styles.scss
- layouts/home/config.js
> FLAG-1326: add planet blog and survey map as a dummy planet imagery option

- services/analysis-cached.js
> fix(cache): remove timestamp from natural forest requests

- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
- components/widgets/forest-change/tree-loss-drivers/index.js
- components/widgets/manifest.js
- pages/api/data/[...params].js
- services/analysis-cached.js
- services/datamart.js
- utils/request.js
https://github.com/wri/gfw/pull/4966
> PROD Deploy 2025-05-07 01:35pm

- components/widgets/forest-change/tree-loss-primary/index.js
- layouts/dashboards/components/header/component.jsx
- services/sentences.js
> FLAG-1325: remove custom IDN image and caveats

- components/legend/components/legend-item-types/legend-item-type-basic/styles.scss
[JIRA ticket
](https://gfw.atlassian.net/browse/FLAG-1231?focusedCommentId=41310)
> [FLAG-1231] add padding to grouped legend

- services/sentences.js
> FLAG-1325: update IDN sentence to be just like the other countries

- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation-drivers/selectors.js
NOTE: this widget remains hidden until TCL launch
> feat(FLAG-1225): update emission by dominant driver widget to be piechart instead of time series

- components/legend/components/legend-item-types/legend-item-type-basic/styles.scss
- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation-drivers/selectors.js
https://github.com/wri/gfw/pull/5001
> PROD Deploy 2025-05-16 07:25 EST

- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation-drivers/selectors.js
- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
- data/colors.json
- data/tsc-loss-categories.json
- services/datamart.js
> FLAG-1292: update carbon emissions and tcl drivers widgets to use datamart and 2024's data

- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation-drivers/selectors.js
- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
> BUGFIXES: TCL and emission by drivers bugfixes

- components/charts/components/pie-chart-legend/component.jsx
- components/charts/components/pie-chart-legend/styles.scss
- components/charts/pie-chart/component.jsx
> update grouped lengeds style and pir chart size

- components/widgets/climate/carbon-flux/index.js
- components/widgets/climate/emissions-deforestation-drivers/index.js
- components/widgets/climate/emissions-deforestation/index.js
- pages/api/widget-metadata/[...params].js
- utils/request.js
> feat(metadata): update metadata for tcl widgets

- components/recent-imagery/components/recent-imagery-settings/component.jsx
The date selector is buggy and sometimes prevents users from selecting a new month/year, closing rapidly.
Steps to Reproduce:
Select [Landsat 8 / Sentinel 2](https://gfw.global/41JtbvY) from the list of available imagery options.
The most recent imagery will be selected by default. 
While the imagery is loading or shortly after it loads, click on the current date to open the calendar. 
If the user clicks the green arrows to move forward or back in time, the calendar will jump back to the original month.
However, if the user waits a while before interacting with the calendar, it works as expected.
> [FLAG-1302] Landsat 8 / Sentinel 2: date selector prevents user from selecting a new month/year 

- data/dashboard-summary-sentence.js
We will add a download link (https://gfw2-data.s3.amazonaws.com/country-pages/country_stats/download/2024/global_05212025.xlsx) to the Summary and Forest Change descriptions on the dashboards.
To each paragraph, we will add the following sentence for download: “Download global statistics by country here.” Specifics are below.
Explore interactive charts and maps that summarize key statistics about global forests. Statistics and global rankings – including rates of forest change, forest extent and drivers of deforestation – can be customized, easily shared and downloaded for offline use. [Download global statistics by country here.](https://gfw2-data.s3.amazonaws.com/country-pages/country_stats/download/2024/global_05212025.xlsx)
Explore interactive charts and maps that summarize global …
> [FLAG-1117] Add the global data download link to the summary and forest change descriptions 

- components/forms/contact/component.jsx
- pages/api/ortto/index.js
> FLAG-1207: update contact us form and send request to ortto

- components/forms/contact/component.jsx
https://github.com/wri/gfw/pull/5033
> PROD Deploy 2025-06-25 02:57pm EST

- components/legend/components/legend-item-toolbar/legend-item-button-info/index.js
- components/legend/components/legend-item-toolbar/legend-item-button-info/utils.js
> FLAG-1258: add custom tooltips

- components/ui/dynamic-sentence/component.jsx
- components/widgets/climate/carbon-flux/index.js
- components/widgets/climate/emissions-deforestation/index.js
- components/widgets/fires/burned-area-cumulative/index.js
- components/widgets/fires/burned-area-ranked/index.js
- components/widgets/fires/burned-area/index.js
- components/widgets/fires/fire-alerts-simple/index.js
- components/widgets/fires/fire-alerts-simple/selectors.js
- components/widgets/fires/fires-alerts-cumulative/index.js
- components/widgets/fires/fires-alerts-historical-weekly/index.js
- components/widgets/fires/fires-alerts-historical/index.js
- components/widgets/fires/fires-alerts/index.js
- components/widgets/fires/fires-ranked/index.js
- components/widgets/fires/fires-within/index.js
- components/widgets/fires/tree-loss-fires-annual/index.js
- components/widgets/fires/tree-loss-fires-proportion/index.js
- components/widgets/forest-change/glad-alerts-simple/index.js
- components/widgets/forest-change/glad-alerts/index.js
- components/widgets/forest-change/glad-ranked/index.js
- components/widgets/forest-change/integrated-alerts-ranked/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/selectors.js
- components/widgets/forest-change/tree-loss-plantations/index.js
- components/widgets/land-cover/natural-forest/index.js
- components/widgets/land-cover/ranked-forest-types/index.js
- components/widgets/land-cover/tree-cover-located/index.js
- components/widgets/selectors.js
- components/widgets/utils/config.js
- data/forest-types.js
- services/get-where-query.js
Add Natural Forest intersection option in forest-types.
> FLAG-1157: add natural forest option

- LICENSE
- components/ui/dynamic-sentence/component.jsx
- components/widgets/climate/carbon-flux/index.js
- components/widgets/climate/emissions-deforestation/index.js
- components/widgets/fires/burned-area-cumulative/index.js
- components/widgets/fires/burned-area-ranked/index.js
- components/widgets/fires/burned-area/index.js
- components/widgets/fires/fire-alerts-simple/selectors.js
- components/widgets/fires/fires-alerts-cumulative/index.js
- components/widgets/fires/fires-alerts-historical-weekly/index.js
- components/widgets/fires/fires-alerts-historical/index.js
- components/widgets/fires/fires-alerts/index.js
- components/widgets/fires/fires-ranked/index.js
- components/widgets/fires/fires-within/index.js
- components/widgets/fires/tree-loss-fires-annual/index.js
- components/widgets/fires/tree-loss-fires-proportion/index.js
- components/widgets/forest-change/glad-alerts-simple/index.js
- components/widgets/forest-change/glad-alerts/index.js
- components/widgets/forest-change/glad-ranked/index.js
- components/widgets/forest-change/integrated-alerts-ranked/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/selectors.js
- components/widgets/forest-change/tree-loss-plantations/index.js
- components/widgets/land-cover/natural-forest/index.js
- components/widgets/land-cover/ranked-forest-types/index.js
- components/widgets/land-cover/tree-cover-located/index.js
- components/widgets/manifest.js
- components/widgets/selectors.js
- components/widgets/utils/config.js
- data/forest-types.js
- services/get-where-query.js
https://github.com/wri/gfw/pull/4921
> PROD Deploy 2025-07-10 03:07pm EST

- pages/_document.js
> FLAG-1194: Hide Do not sell list item from osano drawer

- pages/_document.js
https://github.com/wri/gfw/pull/5051
> PROD Deploy 2025-07-16 02:00pm EST

- pages/_document.js
> FLAG-1194: add osano onUiChanged event to correctly hide Do Not Sell list item

- components/widgets/forest-change/_tree-loss-drivers/index.js
- components/widgets/forest-change/_tree-loss-drivers/selectors.js
- data/metadata-exception.json
- data/metadata.json
- data/tsc-loss-categories.json
- services/datamart.js
> [FAG-1356] Enable TCL by dominant driver for analysis of protected areas and custom areas

- components/widgets/climate/emissions-deforestation/index.js
- components/widgets/climate/emissions-deforestation/selectors.js
- components/widgets/forest-change/integrated-deforestation-alerts/index.js
- components/widgets/forest-change/integrated-deforestation-alerts/selectors.js
- components/widgets/forest-change/tree-loss-global/index.js
- data/datasets.js
- data/land-categories.js
- data/layers.js
> FLAG-831: add global peatlands

- components/widgets/forest-change/tree-cover-gain-simple/index.js
- services/analysis-cached.js
See Slack thread: https://gfwlcl.slack.com/archives/C01U7FF3Y3V/p1755781016690479
> [FLAG-1359]: Fix AOI analysis for tree cover gain

- components/widgets/component.jsx
> FLAG-1362: add width to align empty widget in edge cases

- components/analysis/component.jsx
- components/widgets/component.jsx
https://github.com/wri/gfw/pull/5091
> PROD Deploy 2025-09-05 01:40pm EST

- components/widgets/component.jsx
- components/widgets/forest-change/_tree-loss-drivers/index.js
https://github.com/wri/gfw/pull/5093
> PROD Deploy 2025-09-05 12:13pm EST

- components/widgets/fires/fires-alerts-historical-daily/selectors.js
> [FLAG-1268] Fix Fire Alerts Count widget and other widgets to display correct date on hover when no alerts are present 

- components/widgets/forest-change/_tree-loss-drivers/index.js
> FLAG-1363: add check for aoi in tree cover by dominant driver in download

- components/widgets/forest-change/_tree-loss-drivers/index.js
- wrappers/embed/styles.scss
https://github.com/wri/gfw/pull/5101
> PROD Deploy 2025-09-19 05:16pm EST
